// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c005e0105870bbbc "Mountain Futures (copy) (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Mobile' // Variant
}} Props

 */
import { className, css, fonts } from "../chunks/chunk-ZVSW4UDK.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "../chunks/chunk-W3IXBODR.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "../chunks/chunk-E2DSRDMQ.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "../chunks/chunk-XOYYYZYZ.js";
import { routes } from "../chunks/chunk-MCZURAGM.js";

// virtual:global/footer
import { Fragment as Fragment4 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/4oEfnyQYkcAdzYlae9nq/1RwbmZFGAYWdPaxp9ye7/vzcVpw93U.js
import { jsx as _jsx3, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts3,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider,
	ControlType as ControlType3,
	cx as cx3,
	getFonts,
	getFontsFromSharedStyle as getFontsFromSharedStyle3,
	getLoadingLazyAtYPosition,
	Image,
	Link as Link3,
	ResolveLinks,
	RichText as RichText3,
	SmartComponentScopedContainer,
	useActiveVariantCallback as useActiveVariantCallback3,
	useComponentViewport as useComponentViewport3,
	useLocaleInfo as useLocaleInfo3,
	useRouter,
	useVariantState as useVariantState3,
	withCSS as withCSS3,
} from "unframer";
import {
	LayoutGroup as LayoutGroup3,
	motion as motion3,
	MotionConfigContext as MotionConfigContext3,
} from "unframer";
import * as React3 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/2Xwcio92ewlIBBDNonwp/RyAh52YJYjcnhf8Mpldv/IBAwBvK4_.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["Twp5ZOxhJ", "PUF3sj0l1", "HB5NH2WSL"];
var serializationHash = "framer-6dPVS";
var variantClassNames = {
	HB5NH2WSL: "framer-v-1uous2a",
	PUF3sj0l1: "framer-v-105ikdb",
	Twp5ZOxhJ: "framer-v-1f2msf8",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.4,
	ease: [0.08, 0.78, 0.56, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Hover In": "PUF3sj0l1",
	Default: "Twp5ZOxhJ",
	Mobile: "HB5NH2WSL",
};
var getProps = ({ color, height, id, link, newTab, text, width, ...props }) => {
	return {
		...props,
		BYNIrUSxY: text ?? props.BYNIrUSxY ?? "Button Text",
		r6RvIcK3K:
			color ??
			props.r6RvIcK3K ??
			"var(--token-38406790-1041-404b-8965-34452f5c8f25, rgb(53, 228, 228))",
		sfse768LG: link ?? props.sfse768LG,
		UXzOZZMPJ: newTab ?? props.UXzOZZMPJ,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "Twp5ZOxhJ",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		BYNIrUSxY,
		sfse768LG,
		UXzOZZMPJ,
		r6RvIcK3K,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Twp5ZOxhJ",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnteri69cmo = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		setVariant("PUF3sj0l1");
	});
	const onMouseLeavemchysw = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		setVariant("Twp5ZOxhJ");
	});
	const sharedStyleClassNames = [className4];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						motionChild={true}
						nodeId={"Twp5ZOxhJ"}
						scopeId={"IBAwBvK4_"}
						{...addPropertyOverrides(
							{
								HB5NH2WSL: {
									href: sfse768LG,
								},
								PUF3sj0l1: {
									href: sfse768LG,
									openInNewTab: UXzOZZMPJ,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-1f2msf8", className5, classNames)} framer-13hrk3n`}
							data-framer-name={"Default"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"Twp5ZOxhJ"}
							onMouseEnter={onMouseEnteri69cmo}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									HB5NH2WSL: {
										"data-framer-name": "Mobile",
										"data-highlight": void 0,
										onMouseEnter: void 0,
									},
									PUF3sj0l1: {
										"data-framer-name": "Hover In",
										onMouseLeave: onMouseLeavemchysw,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-1oosgla"}
								data-framer-name={"Button Wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"acgNWGTQq"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1u8c35c"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"LB8c1WuTz"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-38406790-1041-404b-8965-34452f5c8f25, rgb(53, 228, 228))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
										"--variable-reference-r6RvIcK3K-IBAwBvK4_": r6RvIcK3K,
									}}
									text={BYNIrUSxY}
									variants={{
										HB5NH2WSL: {
											"--extracted-r6o4lv":
												"var(--variable-reference-r6RvIcK3K-IBAwBvK4_)",
											"--variable-reference-r6RvIcK3K-IBAwBvK4_": r6RvIcK3K,
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											HB5NH2WSL: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1me2k9"}
															data-styles-preset={"T6JrQgVZg"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--variable-reference-r6RvIcK3K-IBAwBvK4_))",
															}}
														>
															{"Button Text"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1me2k9"}
											data-styles-preset={"T6JrQgVZg"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-38406790-1041-404b-8965-34452f5c8f25, rgb(53, 228, 228)))",
											}}
										>
											{"Button Text"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<motion.div
									className={"framer-2v2o7k"}
									data-framer-name={"Line"}
									layoutDependency={layoutDependency}
									layoutId={"q79Jw5nwz"}
									style={{
										backgroundColor:
											"var(--token-43eac8f6-6121-473c-88d1-781f7c603ff3, rgb(185, 255, 255))",
									}}
								/>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-6dPVS.framer-13hrk3n, .framer-6dPVS .framer-13hrk3n { display: block; }",
	".framer-6dPVS.framer-1f2msf8 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-6dPVS .framer-1oosgla { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-6dPVS .framer-1u8c35c { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 2; }",
	".framer-6dPVS .framer-2v2o7k { bottom: 0px; flex: none; height: 1px; left: -60px; overflow: hidden; position: absolute; width: 53px; z-index: 2; }",
	".framer-6dPVS.framer-v-105ikdb.framer-1f2msf8, .framer-6dPVS.framer-v-1uous2a.framer-1f2msf8 { text-decoration: none; }",
	".framer-6dPVS.framer-v-105ikdb .framer-2v2o7k { left: 1px; right: 0px; width: unset; }",
	...css4,
];
var FramerIBAwBvK4_ = withCSS(Component, css5, "framer-6dPVS");
var stdin_default = FramerIBAwBvK4_;
FramerIBAwBvK4_.displayName = "Footer Underline Link";
FramerIBAwBvK4_.defaultProps = {
	height: 20.25,
	width: 94.05,
};
addPropertyControls(FramerIBAwBvK4_, {
	variant: {
		options: ["Twp5ZOxhJ", "PUF3sj0l1", "HB5NH2WSL"],
		optionTitles: ["Default", "Hover In", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	BYNIrUSxY: {
		defaultValue: "Button Text",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	sfse768LG: {
		title: "Link",
		type: ControlType.Link,
	},
	UXzOZZMPJ: {
		defaultValue: false,
		title: "New Tab",
		type: ControlType.Boolean,
	},
	r6RvIcK3K: {
		defaultValue:
			'var(--token-38406790-1041-404b-8965-34452f5c8f25, rgb(53, 228, 228)) /* {"name":"MF accent blue"} */',
		title: "Color",
		type: ControlType.Color,
	},
});
addFonts(
	FramerIBAwBvK4_,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts4),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/q8QAJ4U4o4J0hHhJ7NqO/3lrUwWjkniE1U88ct59u/wkfq7ysz3.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	Link as Link2,
	RichText as RichText2,
	useActiveVariantCallback as useActiveVariantCallback2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";
var cycleOrder2 = ["QGgIfef0Z", "c0dquppYU", "Sv2cYODtY"];
var serializationHash2 = "framer-h9tvQ";
var variantClassNames2 = {
	c0dquppYU: "framer-v-1eo80hu",
	QGgIfef0Z: "framer-v-rawqu6",
	Sv2cYODtY: "framer-v-1iv86dq",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	delay: 0,
	duration: 0.6,
	ease: [0.08, 0.78, 0.56, 1],
	type: "tween",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	Default: "QGgIfef0Z",
	Hover: "c0dquppYU",
	Mobile: "Sv2cYODtY",
};
var getProps2 = ({ height, id, link, text, width, ...props }) => {
	return {
		...props,
		BYNIrUSxY: text ?? props.BYNIrUSxY ?? "Button Text",
		F3zKmwx_W: link ?? props.F3zKmwx_W,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "QGgIfef0Z",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		BYNIrUSxY,
		F3zKmwx_W,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "QGgIfef0Z",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback2(baseVariant);
	const onMouseEnterbfy0q5 = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		setVariant("c0dquppYU");
	});
	const onMouseLeave6jxa73 = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		setVariant("QGgIfef0Z");
	});
	const sharedStyleClassNames = [className3];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<Link2
						motionChild={true}
						nodeId={"QGgIfef0Z"}
						scopeId={"wkfq7ysz3"}
						{...addPropertyOverrides2(
							{
								c0dquppYU: {
									href: F3zKmwx_W,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx2(scopingClassNames, "framer-rawqu6", className5, classNames)} framer-25017l`}
							data-framer-name={"Default"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"QGgIfef0Z"}
							onMouseEnter={onMouseEnterbfy0q5}
							ref={refBinding}
							style={{
								backdropFilter: "blur(3px)",
								WebkitBackdropFilter: "blur(3px)",
								...style,
							}}
							{...addPropertyOverrides2(
								{
									c0dquppYU: {
										"data-framer-name": "Hover",
										onMouseLeave: onMouseLeave6jxa73,
									},
									Sv2cYODtY: {
										"data-framer-name": "Mobile",
										"data-highlight": void 0,
										onMouseEnter: void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion2.div
								className={"framer-1ip05r8"}
								data-framer-name={"Button Body"}
								layoutDependency={layoutDependency}
								layoutId={"Ejl9LZ4nS"}
								style={{
									backdropFilter: "blur(5px)",
									backgroundColor:
										"var(--token-38406790-1041-404b-8965-34452f5c8f25, rgb(53, 228, 228))",
									borderBottomLeftRadius: 22,
									borderBottomRightRadius: 22,
									borderTopLeftRadius: 22,
									borderTopRightRadius: 22,
									WebkitBackdropFilter: "blur(5px)",
								}}
							>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-188opaw"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"doC2s_1t2"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-88fd9b68-42f9-4676-b8dd-60b51ccd638a, rgb(39, 46, 63))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={BYNIrUSxY}
									variants={{
										c0dquppYU: {
											"--extracted-r6o4lv":
												"var(--token-ad0dbc1a-e59a-47ab-8ef3-f598c1c19141, rgb(255, 255, 255))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides2(
										{
											c0dquppYU: {
												children: (
													<React2.Fragment>
														<motion2.p
															className={"framer-styles-preset-1tix7ms"}
															data-styles-preset={"PNrJZBqkc"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-ad0dbc1a-e59a-47ab-8ef3-f598c1c19141, rgb(255, 255, 255)))",
															}}
														>
															{"Button Text"}
														</motion2.p>
													</React2.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-1tix7ms"}
											data-styles-preset={"PNrJZBqkc"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-88fd9b68-42f9-4676-b8dd-60b51ccd638a, rgb(39, 46, 63)))",
											}}
										>
											{"Button Text"}
										</motion2.p>
									</React2.Fragment>
								</RichText2>
							</motion2.div>
						</motion2.a>
					</Link2>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-h9tvQ.framer-25017l, .framer-h9tvQ .framer-25017l { display: block; }",
	".framer-h9tvQ.framer-rawqu6 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-h9tvQ .framer-1ip05r8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 10px 16px 10px 16px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-h9tvQ .framer-188opaw { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-h9tvQ.framer-v-1eo80hu.framer-rawqu6 { text-decoration: none; }",
	...css3,
];
var Framerwkfq7ysz3 = withCSS2(Component2, css6, "framer-h9tvQ");
var stdin_default2 = Framerwkfq7ysz3;
Framerwkfq7ysz3.displayName = "Secondary";
Framerwkfq7ysz3.defaultProps = {
	height: 41.7,
	width: 102.45,
};
addPropertyControls2(Framerwkfq7ysz3, {
	variant: {
		options: ["QGgIfef0Z", "c0dquppYU", "Sv2cYODtY"],
		optionTitles: ["Default", "Hover", "Mobile"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	BYNIrUSxY: {
		defaultValue: "Button Text",
		displayTextArea: false,
		title: "Text",
		type: ControlType2.String,
	},
	F3zKmwx_W: {
		title: "Link",
		type: ControlType2.Link,
	},
});
addFonts2(
	Framerwkfq7ysz3,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle2(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/4oEfnyQYkcAdzYlae9nq/1RwbmZFGAYWdPaxp9ye7/vzcVpw93U.js
var SecondaryFonts = getFonts(stdin_default2);
var FooterUnderlineLinkFonts = getFonts(stdin_default);
var cycleOrder3 = ["HLtzNlJv0", "eKPIUhuMd", "KSYecJg7z"];
var serializationHash3 = "framer-34ZDN";
var variantClassNames3 = {
	eKPIUhuMd: "framer-v-5rr6ub",
	HLtzNlJv0: "framer-v-l0br6o",
	KSYecJg7z: "framer-v-ye0vsa",
};
function addPropertyOverrides3(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition13 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition3 = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext3);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext3.Provider value={contextValue}>
			{children}
		</MotionConfigContext3.Provider>
	);
};
var Variants3 = motion3.create(React3.Fragment);
var humanReadableVariantMap3 = {
	Desktop: "HLtzNlJv0",
	Mobile: "KSYecJg7z",
	Tablet: "eKPIUhuMd",
};
var getProps3 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap3[props.variant] ?? props.variant ?? "HLtzNlJv0",
	};
};
var createLayoutDependency3 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo3();
	const componentViewport = useComponentViewport3();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState3({
		cycleOrder: cycleOrder3,
		defaultVariant: "HLtzNlJv0",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames3,
	});
	const layoutDependency = createLayoutDependency3(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback3(baseVariant);
	const onTap1rghmbm = activeVariantCallback(async (...args) => {
		setVariant("eKPIUhuMd");
	});
	const sharedStyleClassNames = [className, className2, className3];
	const scopingClassNames = cx3(serializationHash3, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup3 id={layoutId ?? defaultLayoutId}>
			<Variants3 animate={variants} initial={false}>
				<Transition3 value={transition13}>
					<Image
						{...restProps}
						{...gestureHandlers}
						as={"footer"}
						background={{
							alt: "",
							fit: "fill",
							loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
							pixelHeight: 1458,
							pixelWidth: 3e3,
							positionX: "right",
							positionY: "bottom",
							sizes: componentViewport?.width || "100vw",
							src: "https://framerusercontent.com/images/PaaiN39wMK7hNYlKc5RY6I3rOk.jpg?width=3000&height=1458",
							srcSet:
								"https://framerusercontent.com/images/PaaiN39wMK7hNYlKc5RY6I3rOk.jpg?scale-down-to=512&width=3000&height=1458 512w,https://framerusercontent.com/images/PaaiN39wMK7hNYlKc5RY6I3rOk.jpg?scale-down-to=1024&width=3000&height=1458 1024w,https://framerusercontent.com/images/PaaiN39wMK7hNYlKc5RY6I3rOk.jpg?scale-down-to=2048&width=3000&height=1458 2048w,https://framerusercontent.com/images/PaaiN39wMK7hNYlKc5RY6I3rOk.jpg?width=3000&height=1458 3000w",
						}}
						className={cx3(
							scopingClassNames,
							"framer-l0br6o",
							className5,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"HLtzNlJv0"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides3(
							{
								eKPIUhuMd: {
									"data-framer-name": "Tablet",
									background: {
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											componentViewport?.y || 0,
										),
										pixelHeight: 1458,
										pixelWidth: 3e3,
										positionX: "right",
										positionY: "bottom",
										sizes: componentViewport?.width || "100vw",
										src: "https://framerusercontent.com/images/PaaiN39wMK7hNYlKc5RY6I3rOk.jpg?width=3000&height=1458",
									},
								},
								KSYecJg7z: {
									"data-framer-name": "Mobile",
									background: {
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											componentViewport?.y || 0,
										),
										pixelHeight: 1458,
										pixelWidth: 3e3,
										positionX: "64.6%",
										positionY: "97%",
										sizes: componentViewport?.width || "100vw",
										src: "https://framerusercontent.com/images/PaaiN39wMK7hNYlKc5RY6I3rOk.jpg?width=3000&height=1458",
									},
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion3.div
							className={"framer-691i0w"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"XpssHnuOT"}
						>
							<motion3.div
								className={"framer-1oul79c"}
								data-framer-name={"Content Wrap"}
								layoutDependency={layoutDependency}
								layoutId={"x6KeYUAH2"}
							>
								<motion3.div
									className={"framer-ji5s00"}
									data-framer-name={"Wrapper"}
									layoutDependency={layoutDependency}
									layoutId={"cgo7YUc68"}
								>
									<motion3.div
										className={"framer-1mtirf4"}
										data-framer-name={"Footer Item"}
										layoutDependency={layoutDependency}
										layoutId={"ClDoIrqJ5"}
										{...addPropertyOverrides3(
											{
												eKPIUhuMd: {
													"data-highlight": true,
													onTap: onTap1rghmbm,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<RichText3
											__fromCanvasComponent={true}
											className={"framer-ltb8o5"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"z0qw37q9T"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-ad0dbc1a-e59a-47ab-8ef3-f598c1c19141, rgb(255, 255, 255))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React3.Fragment>
												<motion3.p
													className={"framer-styles-preset-rwcd89"}
													data-styles-preset={"fVNgQUCuM"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-ad0dbc1a-e59a-47ab-8ef3-f598c1c19141, rgb(255, 255, 255)))",
													}}
												>
													{
														"Help us create lasting impact in mountain regions. Support research, innovation, and community-focused solutions."
													}
												</motion3.p>
											</React3.Fragment>
										</RichText3>
										<ResolveLinks
											links={[
												{
													href: {
														webPageId: "ifpwmzD2L",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "ifpwmzD2L",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "ifpwmzD2L",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks) => (
												<ComponentViewportProvider
													height={41}
													y={
														(componentViewport?.y || 0) +
														32 +
														(((componentViewport?.height || 547) - 64 - 483) /
															2 +
															0 +
															0) +
														0 +
														0 +
														0 +
														0 +
														0 +
														0 +
														165.5
													}
													{...addPropertyOverrides3(
														{
															eKPIUhuMd: {
																y:
																	(componentViewport?.y || 0) +
																	25 +
																	(((componentViewport?.height || 444) -
																		50 -
																		394) /
																		2 +
																		0 +
																		0) +
																	0 +
																	0 +
																	0 +
																	0 +
																	0 +
																	1 +
																	165.5,
															},
															KSYecJg7z: {
																y:
																	(componentViewport?.y || 0) +
																	24 +
																	(((componentViewport?.height || 200) -
																		49 -
																		673.2) /
																		2 +
																		0 +
																		0) +
																	0 +
																	0 +
																	0 +
																	0 +
																	0 +
																	0 +
																	0 +
																	165.5,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														className={"framer-m2t44-container"}
														layoutDependency={layoutDependency}
														layoutId={"p8Q9NRqo_-container"}
														nodeId={"p8Q9NRqo_"}
														rendersWithMotion={true}
														scopeId={"vzcVpw93U"}
													>
														{_jsx3(stdin_default2, {
															BYNIrUSxY: "Work with us",
															F3zKmwx_W: resolvedLinks[0],
															height: "100%",
															id: "p8Q9NRqo_",
															layoutId: "p8Q9NRqo_",
															variant: "QGgIfef0Z",
															width: "100%",
															...addPropertyOverrides3(
																{
																	eKPIUhuMd: {
																		F3zKmwx_W: resolvedLinks[1],
																	},
																	KSYecJg7z: {
																		F3zKmwx_W: resolvedLinks[2],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
									</motion3.div>
									<motion3.div
										className={"framer-1t6pt8p"}
										layoutDependency={layoutDependency}
										layoutId={"mXekzujQw"}
									>
										<motion3.div
											className={"framer-11cz6xf"}
											data-framer-name={"Footer Block"}
											layoutDependency={layoutDependency}
											layoutId={"AjEy9Blns"}
										>
											<motion3.div
												className={"framer-kr517v"}
												data-framer-name={"Link Wrapper"}
												layoutDependency={layoutDependency}
												layoutId={"xK29H2u1B"}
											>
												<RichText3
													__fromCanvasComponent={true}
													className={"framer-1toqzog"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"J548myBzQ"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-ad0dbc1a-e59a-47ab-8ef3-f598c1c19141, rgb(255, 255, 255))",
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React3.Fragment>
														<motion3.p
															className={"framer-styles-preset-16bupuy"}
															data-styles-preset={"pJrILY7rY"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-ad0dbc1a-e59a-47ab-8ef3-f598c1c19141, rgb(255, 255, 255)))",
															}}
														>
															{"Pages"}
														</motion3.p>
													</React3.Fragment>
												</RichText3>
												<ResolveLinks
													links={[
														{
															href: {
																webPageId: "augiA20Il",
															},
															implicitPathVariables: void 0,
														},
														{
															href: {
																webPageId: "augiA20Il",
															},
															implicitPathVariables: void 0,
														},
														{
															href: {
																webPageId: "augiA20Il",
															},
															implicitPathVariables: void 0,
														},
													]}
												>
													{(resolvedLinks1) => (
														<ComponentViewportProvider
															height={20}
															y={
																(componentViewport?.y || 0) +
																32 +
																(((componentViewport?.height || 547) -
																	64 -
																	483) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																0 +
																0 +
																0 +
																0 +
																0 +
																28
															}
															{...addPropertyOverrides3(
																{
																	eKPIUhuMd: {
																		y:
																			(componentViewport?.y || 0) +
																			25 +
																			(((componentViewport?.height || 444) -
																				50 -
																				394) /
																				2 +
																				0 +
																				0) +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			28,
																	},
																	KSYecJg7z: {
																		y:
																			(componentViewport?.y || 0) +
																			24 +
																			(((componentViewport?.height || 200) -
																				49 -
																				673.2) /
																				2 +
																				0 +
																				0) +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			254.5 +
																			10 +
																			0 +
																			0 +
																			0 +
																			28,
																	},
																},
																baseVariant,
																gestureVariant,
															)}
														>
															<SmartComponentScopedContainer
																className={"framer-1ynl0vo-container"}
																layoutDependency={layoutDependency}
																layoutId={"w6AHBYru6-container"}
																nodeId={"w6AHBYru6"}
																rendersWithMotion={true}
																scopeId={"vzcVpw93U"}
															>
																{_jsx3(stdin_default, {
																	BYNIrUSxY: "Home",
																	height: "100%",
																	id: "w6AHBYru6",
																	layoutId: "w6AHBYru6",
																	r6RvIcK3K:
																		"var(--token-43eac8f6-6121-473c-88d1-781f7c603ff3, rgb(185, 255, 255))",
																	sfse768LG: resolvedLinks1[0],
																	UXzOZZMPJ: false,
																	variant: "Twp5ZOxhJ",
																	width: "100%",
																	...addPropertyOverrides3(
																		{
																			eKPIUhuMd: {
																				sfse768LG: resolvedLinks1[1],
																			},
																			KSYecJg7z: {
																				r6RvIcK3K:
																					"var(--token-38406790-1041-404b-8965-34452f5c8f25, rgb(53, 228, 228))",
																				sfse768LG: resolvedLinks1[2],
																				variant: "HB5NH2WSL",
																			},
																		},
																		baseVariant,
																		gestureVariant,
																	),
																})}
															</SmartComponentScopedContainer>
														</ComponentViewportProvider>
													)}
												</ResolveLinks>
												<ResolveLinks
													links={[
														{
															href: {
																webPageId: "EpXpYwtEx",
															},
															implicitPathVariables: void 0,
														},
														{
															href: {
																webPageId: "EpXpYwtEx",
															},
															implicitPathVariables: void 0,
														},
														{
															href: {
																webPageId: "EpXpYwtEx",
															},
															implicitPathVariables: void 0,
														},
													]}
												>
													{(resolvedLinks2) => (
														<ComponentViewportProvider
															height={20}
															y={
																(componentViewport?.y || 0) +
																32 +
																(((componentViewport?.height || 547) -
																	64 -
																	483) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																0 +
																0 +
																0 +
																0 +
																0 +
																52
															}
															{...addPropertyOverrides3(
																{
																	eKPIUhuMd: {
																		y:
																			(componentViewport?.y || 0) +
																			25 +
																			(((componentViewport?.height || 444) -
																				50 -
																				394) /
																				2 +
																				0 +
																				0) +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			52,
																	},
																	KSYecJg7z: {
																		y:
																			(componentViewport?.y || 0) +
																			24 +
																			(((componentViewport?.height || 200) -
																				49 -
																				673.2) /
																				2 +
																				0 +
																				0) +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			254.5 +
																			10 +
																			0 +
																			0 +
																			0 +
																			52,
																	},
																},
																baseVariant,
																gestureVariant,
															)}
														>
															<SmartComponentScopedContainer
																className={"framer-utgt-container"}
																layoutDependency={layoutDependency}
																layoutId={"Lhp46bMo9-container"}
																nodeId={"Lhp46bMo9"}
																rendersWithMotion={true}
																scopeId={"vzcVpw93U"}
															>
																{_jsx3(stdin_default, {
																	BYNIrUSxY: "Expertise",
																	height: "100%",
																	id: "Lhp46bMo9",
																	layoutId: "Lhp46bMo9",
																	r6RvIcK3K:
																		"var(--token-38406790-1041-404b-8965-34452f5c8f25, rgb(53, 228, 228))",
																	sfse768LG: resolvedLinks2[0],
																	UXzOZZMPJ: false,
																	variant: "Twp5ZOxhJ",
																	width: "100%",
																	...addPropertyOverrides3(
																		{
																			eKPIUhuMd: {
																				sfse768LG: resolvedLinks2[1],
																			},
																			KSYecJg7z: {
																				sfse768LG: resolvedLinks2[2],
																				variant: "HB5NH2WSL",
																			},
																		},
																		baseVariant,
																		gestureVariant,
																	),
																})}
															</SmartComponentScopedContainer>
														</ComponentViewportProvider>
													)}
												</ResolveLinks>
												<ResolveLinks
													links={[
														{
															href: {
																webPageId: "hG6TrYH62",
															},
															implicitPathVariables: void 0,
														},
														{
															href: {
																webPageId: "hG6TrYH62",
															},
															implicitPathVariables: void 0,
														},
														{
															href: {
																webPageId: "hG6TrYH62",
															},
															implicitPathVariables: void 0,
														},
													]}
												>
													{(resolvedLinks3) => (
														<ComponentViewportProvider
															height={20}
															y={
																(componentViewport?.y || 0) +
																32 +
																(((componentViewport?.height || 547) -
																	64 -
																	483) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																0 +
																0 +
																0 +
																0 +
																0 +
																76
															}
															{...addPropertyOverrides3(
																{
																	eKPIUhuMd: {
																		y:
																			(componentViewport?.y || 0) +
																			25 +
																			(((componentViewport?.height || 444) -
																				50 -
																				394) /
																				2 +
																				0 +
																				0) +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			76,
																	},
																	KSYecJg7z: {
																		y:
																			(componentViewport?.y || 0) +
																			24 +
																			(((componentViewport?.height || 200) -
																				49 -
																				673.2) /
																				2 +
																				0 +
																				0) +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			254.5 +
																			10 +
																			0 +
																			0 +
																			0 +
																			76,
																	},
																},
																baseVariant,
																gestureVariant,
															)}
														>
															<SmartComponentScopedContainer
																className={"framer-jaigek-container"}
																layoutDependency={layoutDependency}
																layoutId={"Yt74wu3kU-container"}
																nodeId={"Yt74wu3kU"}
																rendersWithMotion={true}
																scopeId={"vzcVpw93U"}
															>
																{_jsx3(stdin_default, {
																	BYNIrUSxY: "Resources",
																	height: "100%",
																	id: "Yt74wu3kU",
																	layoutId: "Yt74wu3kU",
																	r6RvIcK3K:
																		"var(--token-38406790-1041-404b-8965-34452f5c8f25, rgb(53, 228, 228))",
																	sfse768LG: resolvedLinks3[0],
																	UXzOZZMPJ: false,
																	variant: "Twp5ZOxhJ",
																	width: "100%",
																	...addPropertyOverrides3(
																		{
																			eKPIUhuMd: {
																				sfse768LG: resolvedLinks3[1],
																			},
																			KSYecJg7z: {
																				sfse768LG: resolvedLinks3[2],
																				variant: "HB5NH2WSL",
																			},
																		},
																		baseVariant,
																		gestureVariant,
																	),
																})}
															</SmartComponentScopedContainer>
														</ComponentViewportProvider>
													)}
												</ResolveLinks>
												<ResolveLinks
													links={[
														{
															href: {
																webPageId: "RYDHx0ZEa",
															},
															implicitPathVariables: void 0,
														},
														{
															href: {
																webPageId: "RYDHx0ZEa",
															},
															implicitPathVariables: void 0,
														},
														{
															href: {
																webPageId: "RYDHx0ZEa",
															},
															implicitPathVariables: void 0,
														},
													]}
												>
													{(resolvedLinks4) => (
														<ComponentViewportProvider
															height={20}
															y={
																(componentViewport?.y || 0) +
																32 +
																(((componentViewport?.height || 547) -
																	64 -
																	483) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																0 +
																0 +
																0 +
																0 +
																0 +
																100
															}
															{...addPropertyOverrides3(
																{
																	eKPIUhuMd: {
																		y:
																			(componentViewport?.y || 0) +
																			25 +
																			(((componentViewport?.height || 444) -
																				50 -
																				394) /
																				2 +
																				0 +
																				0) +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			100,
																	},
																	KSYecJg7z: {
																		y:
																			(componentViewport?.y || 0) +
																			24 +
																			(((componentViewport?.height || 200) -
																				49 -
																				673.2) /
																				2 +
																				0 +
																				0) +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			254.5 +
																			10 +
																			0 +
																			0 +
																			0 +
																			100,
																	},
																},
																baseVariant,
																gestureVariant,
															)}
														>
															<SmartComponentScopedContainer
																className={"framer-1iqj0ig-container"}
																layoutDependency={layoutDependency}
																layoutId={"OrxDAKk0Z-container"}
																nodeId={"OrxDAKk0Z"}
																rendersWithMotion={true}
																scopeId={"vzcVpw93U"}
															>
																{_jsx3(stdin_default, {
																	BYNIrUSxY: "About",
																	height: "100%",
																	id: "OrxDAKk0Z",
																	layoutId: "OrxDAKk0Z",
																	r6RvIcK3K:
																		"var(--token-38406790-1041-404b-8965-34452f5c8f25, rgb(53, 228, 228))",
																	sfse768LG: resolvedLinks4[0],
																	UXzOZZMPJ: false,
																	variant: "Twp5ZOxhJ",
																	width: "100%",
																	...addPropertyOverrides3(
																		{
																			eKPIUhuMd: {
																				sfse768LG: resolvedLinks4[1],
																			},
																			KSYecJg7z: {
																				sfse768LG: resolvedLinks4[2],
																				variant: "HB5NH2WSL",
																			},
																		},
																		baseVariant,
																		gestureVariant,
																	),
																})}
															</SmartComponentScopedContainer>
														</ComponentViewportProvider>
													)}
												</ResolveLinks>
												<ResolveLinks
													links={[
														{
															href: {
																webPageId: "ifpwmzD2L",
															},
															implicitPathVariables: void 0,
														},
														{
															href: {
																webPageId: "ifpwmzD2L",
															},
															implicitPathVariables: void 0,
														},
														{
															href: {
																webPageId: "ifpwmzD2L",
															},
															implicitPathVariables: void 0,
														},
													]}
												>
													{(resolvedLinks5) => (
														<ComponentViewportProvider
															height={20}
															y={
																(componentViewport?.y || 0) +
																32 +
																(((componentViewport?.height || 547) -
																	64 -
																	483) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																0 +
																0 +
																0 +
																0 +
																0 +
																124
															}
															{...addPropertyOverrides3(
																{
																	eKPIUhuMd: {
																		y:
																			(componentViewport?.y || 0) +
																			25 +
																			(((componentViewport?.height || 444) -
																				50 -
																				394) /
																				2 +
																				0 +
																				0) +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			124,
																	},
																	KSYecJg7z: {
																		y:
																			(componentViewport?.y || 0) +
																			24 +
																			(((componentViewport?.height || 200) -
																				49 -
																				673.2) /
																				2 +
																				0 +
																				0) +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			254.5 +
																			10 +
																			0 +
																			0 +
																			0 +
																			124,
																	},
																},
																baseVariant,
																gestureVariant,
															)}
														>
															<SmartComponentScopedContainer
																className={"framer-h53xyx-container"}
																layoutDependency={layoutDependency}
																layoutId={"C89dGBScl-container"}
																nodeId={"C89dGBScl"}
																rendersWithMotion={true}
																scopeId={"vzcVpw93U"}
															>
																{_jsx3(stdin_default, {
																	BYNIrUSxY: "Contact",
																	height: "100%",
																	id: "C89dGBScl",
																	layoutId: "C89dGBScl",
																	r6RvIcK3K:
																		"var(--token-38406790-1041-404b-8965-34452f5c8f25, rgb(53, 228, 228))",
																	sfse768LG: resolvedLinks5[0],
																	UXzOZZMPJ: false,
																	variant: "Twp5ZOxhJ",
																	width: "100%",
																	...addPropertyOverrides3(
																		{
																			eKPIUhuMd: {
																				sfse768LG: resolvedLinks5[1],
																			},
																			KSYecJg7z: {
																				sfse768LG: resolvedLinks5[2],
																				variant: "HB5NH2WSL",
																			},
																		},
																		baseVariant,
																		gestureVariant,
																	),
																})}
															</SmartComponentScopedContainer>
														</ComponentViewportProvider>
													)}
												</ResolveLinks>
											</motion3.div>
										</motion3.div>
										<motion3.div
											className={"framer-1bf1dni"}
											data-framer-name={"Footer Block"}
											layoutDependency={layoutDependency}
											layoutId={"rhDpgtI8b"}
										>
											<motion3.div
												className={"framer-ktwulr"}
												data-framer-name={"Footer Block"}
												layoutDependency={layoutDependency}
												layoutId={"xX256t1V9"}
											>
												<RichText3
													__fromCanvasComponent={true}
													className={"framer-8ym1q7"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"ABI4W1Lln"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-ad0dbc1a-e59a-47ab-8ef3-f598c1c19141, rgb(255, 255, 255))",
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React3.Fragment>
														<motion3.p
															className={"framer-styles-preset-16bupuy"}
															data-styles-preset={"pJrILY7rY"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-ad0dbc1a-e59a-47ab-8ef3-f598c1c19141, rgb(255, 255, 255)))",
															}}
														>
															{"Legal"}
														</motion3.p>
													</React3.Fragment>
												</RichText3>
												<ResolveLinks
													links={[
														{
															href: {
																webPageId: "JpGx6ZfHf",
															},
															implicitPathVariables: void 0,
														},
														{
															href: {
																webPageId: "JpGx6ZfHf",
															},
															implicitPathVariables: void 0,
														},
														{
															href: {
																webPageId: "JpGx6ZfHf",
															},
															implicitPathVariables: void 0,
														},
													]}
												>
													{(resolvedLinks6) => (
														<ComponentViewportProvider
															height={20}
															y={
																(componentViewport?.y || 0) +
																32 +
																(((componentViewport?.height || 547) -
																	64 -
																	483) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																0 +
																0 +
																0 +
																0 +
																0 +
																27
															}
															{...addPropertyOverrides3(
																{
																	eKPIUhuMd: {
																		y:
																			(componentViewport?.y || 0) +
																			25 +
																			(((componentViewport?.height || 444) -
																				50 -
																				394) /
																				2 +
																				0 +
																				0) +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			27,
																	},
																	KSYecJg7z: {
																		y:
																			(componentViewport?.y || 0) +
																			24 +
																			(((componentViewport?.height || 200) -
																				49 -
																				673.2) /
																				2 +
																				0 +
																				0) +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			254.5 +
																			10 +
																			0 +
																			0 +
																			0 +
																			27,
																	},
																},
																baseVariant,
																gestureVariant,
															)}
														>
															<SmartComponentScopedContainer
																className={"framer-1hqzdrn-container"}
																layoutDependency={layoutDependency}
																layoutId={"v88Dzk5mO-container"}
																nodeId={"v88Dzk5mO"}
																rendersWithMotion={true}
																scopeId={"vzcVpw93U"}
															>
																{_jsx3(stdin_default, {
																	BYNIrUSxY: "Privacy policy",
																	height: "100%",
																	id: "v88Dzk5mO",
																	layoutId: "v88Dzk5mO",
																	r6RvIcK3K:
																		"var(--token-38406790-1041-404b-8965-34452f5c8f25, rgb(53, 228, 228))",
																	sfse768LG: resolvedLinks6[0],
																	UXzOZZMPJ: true,
																	variant: "Twp5ZOxhJ",
																	width: "100%",
																	...addPropertyOverrides3(
																		{
																			eKPIUhuMd: {
																				sfse768LG: resolvedLinks6[1],
																			},
																			KSYecJg7z: {
																				sfse768LG: resolvedLinks6[2],
																				variant: "HB5NH2WSL",
																			},
																		},
																		baseVariant,
																		gestureVariant,
																	),
																})}
															</SmartComponentScopedContainer>
														</ComponentViewportProvider>
													)}
												</ResolveLinks>
											</motion3.div>
										</motion3.div>
									</motion3.div>
								</motion3.div>
								<motion3.div
									className={"framer-didmk4"}
									data-framer-name={"End"}
									layoutDependency={layoutDependency}
									layoutId={"dVORhDhr3"}
								>
									<Link3
										href={{
											webPageId: "augiA20Il",
										}}
										motionChild={true}
										nodeId={"HNnTARCoR"}
										openInNewTab={false}
										scopeId={"vzcVpw93U"}
									>
										<motion3.a
											className={"framer-j15gzc framer-13gm34l"}
											data-framer-name={"Logo Wrapper"}
											layoutDependency={layoutDependency}
											layoutId={"HNnTARCoR"}
										>
											<motion3.div
												className={"framer-1y5a6m8"}
												data-framer-name={"Logo"}
												layoutDependency={layoutDependency}
												layoutId={"vLUBVtjDM"}
											>
												<Image
													background={{
														alt: "",
														fit: "fit",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																32 +
																(((componentViewport?.height || 547) -
																	64 -
																	483) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																395.5 +
																49 +
																0 +
																0 +
																0,
														),
														pixelHeight: 197,
														pixelWidth: 757,
														positionX: "center",
														positionY: "center",
														sizes: "206px",
														src: "https://framerusercontent.com/images/tZS1kRjh82lEc711UshTuiiGWw.png?width=757&height=197",
														srcSet:
															"https://framerusercontent.com/images/tZS1kRjh82lEc711UshTuiiGWw.png?scale-down-to=512&width=757&height=197 512w,https://framerusercontent.com/images/tZS1kRjh82lEc711UshTuiiGWw.png?width=757&height=197 757w",
													}}
													className={"framer-kng59d"}
													layoutDependency={layoutDependency}
													layoutId={"T1QPad7eS"}
													{...addPropertyOverrides3(
														{
															eKPIUhuMd: {
																background: {
																	alt: "",
																	fit: "fit",
																	loading: getLoadingLazyAtYPosition(
																		(componentViewport?.y || 0) +
																			25 +
																			(((componentViewport?.height || 444) -
																				50 -
																				394) /
																				2 +
																				0 +
																				0) +
																			0 +
																			0 +
																			0 +
																			300.5 +
																			28 +
																			0 +
																			0 +
																			5.5,
																	),
																	pixelHeight: 197,
																	pixelWidth: 757,
																	positionX: "center",
																	positionY: "center",
																	sizes: "243px",
																	src: "https://framerusercontent.com/images/tZS1kRjh82lEc711UshTuiiGWw.png?width=757&height=197",
																	srcSet:
																		"https://framerusercontent.com/images/tZS1kRjh82lEc711UshTuiiGWw.png?scale-down-to=512&width=757&height=197 512w,https://framerusercontent.com/images/tZS1kRjh82lEc711UshTuiiGWw.png?width=757&height=197 757w",
																},
															},
															KSYecJg7z: {
																background: {
																	alt: "",
																	fit: "fit",
																	loading: getLoadingLazyAtYPosition(
																		(componentViewport?.y || 0) +
																			24 +
																			(((componentViewport?.height || 200) -
																				49 -
																				673.2) /
																				2 +
																				0 +
																				0) +
																			0 +
																			0 +
																			0 +
																			460.5 +
																			49 +
																			0 +
																			6 +
																			3.5,
																	),
																	pixelHeight: 197,
																	pixelWidth: 757,
																	positionX: "center",
																	positionY: "center",
																	sizes: "191px",
																	src: "https://framerusercontent.com/images/tZS1kRjh82lEc711UshTuiiGWw.png?width=757&height=197",
																	srcSet:
																		"https://framerusercontent.com/images/tZS1kRjh82lEc711UshTuiiGWw.png?scale-down-to=512&width=757&height=197 512w,https://framerusercontent.com/images/tZS1kRjh82lEc711UshTuiiGWw.png?width=757&height=197 757w",
																},
															},
														},
														baseVariant,
														gestureVariant,
													)}
												/>
											</motion3.div>
										</motion3.a>
									</Link3>
									<motion3.div
										className={"framer-z4yo8m"}
										data-framer-name={"Wrap"}
										layoutDependency={layoutDependency}
										layoutId={"zO2JnN9IQ"}
									>
										<motion3.div
											className={"framer-14dqgzc"}
											data-framer-name={"Time Wrapper"}
											layoutDependency={layoutDependency}
											layoutId={"PBm6Gst4d"}
										/>
										<RichText3
											__fromCanvasComponent={true}
											className={"framer-oalyor"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"yWwvJOHVU"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-ad0dbc1a-e59a-47ab-8ef3-f598c1c19141, rgb(255, 255, 255))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React3.Fragment>
												<motion3.p
													className={"framer-styles-preset-1tix7ms"}
													data-styles-preset={"PNrJZBqkc"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-ad0dbc1a-e59a-47ab-8ef3-f598c1c19141, rgb(255, 255, 255)))",
													}}
												>
													{"\xA92025 Mountain Futures"}
												</motion3.p>
											</React3.Fragment>
										</RichText3>
									</motion3.div>
								</motion3.div>
							</motion3.div>
						</motion3.div>
					</Image>
				</Transition3>
			</Variants3>
		</LayoutGroup3>
	);
});
var css7 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-34ZDN.framer-13gm34l, .framer-34ZDN .framer-13gm34l { display: block; }",
	".framer-34ZDN.framer-l0br6o { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 32px 55px 32px 45px; position: relative; width: 1200px; will-change: var(--framer-will-change-filter-override, filter); }",
	".framer-34ZDN .framer-691i0w { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: center; max-width: 1200px; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-34ZDN .framer-1oul79c { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 189px; height: 483px; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-34ZDN .framer-ji5s00 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-34ZDN .framer-1mtirf4 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; max-width: 400px; overflow: hidden; padding: 0px; position: relative; width: 1px; z-index: 1; }",
	".framer-34ZDN .framer-ltb8o5 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-34ZDN .framer-m2t44-container, .framer-34ZDN .framer-1ynl0vo-container, .framer-34ZDN .framer-utgt-container, .framer-34ZDN .framer-jaigek-container, .framer-34ZDN .framer-1iqj0ig-container, .framer-34ZDN .framer-h53xyx-container, .framer-34ZDN .framer-1hqzdrn-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-34ZDN .framer-1t6pt8p { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-34ZDN .framer-11cz6xf, .framer-34ZDN .framer-1bf1dni { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-34ZDN .framer-kr517v, .framer-34ZDN .framer-ktwulr { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-34ZDN .framer-1toqzog { flex: none; height: 24px; position: relative; white-space: pre-wrap; width: 67px; word-break: break-word; word-wrap: break-word; }",
	".framer-34ZDN .framer-8ym1q7 { flex: none; height: 23px; position: relative; white-space: pre-wrap; width: 73px; word-break: break-word; word-wrap: break-word; }",
	".framer-34ZDN .framer-didmk4 { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 49px 0px 49px 0px; position: relative; width: 100%; }",
	".framer-34ZDN .framer-j15gzc { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-34ZDN .framer-1y5a6m8 { align-content: center; align-items: center; aspect-ratio: 3.3217391304347825 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 62px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 206px; }",
	".framer-34ZDN .framer-kng59d { flex: none; height: 62px; position: relative; width: 206px; z-index: 1; }",
	".framer-34ZDN .framer-z4yo8m { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-34ZDN .framer-14dqgzc { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: 23px; justify-content: flex-start; min-width: 127px; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-34ZDN .framer-oalyor { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-34ZDN.framer-v-5rr6ub.framer-l0br6o { padding: 25px 21px 25px 21px; width: 810px; }",
	".framer-34ZDN.framer-v-5rr6ub .framer-691i0w { padding: 0px 45px 0px 0px; }",
	".framer-34ZDN.framer-v-5rr6ub .framer-1oul79c { align-content: flex-start; align-items: flex-start; gap: 92px; height: 394px; order: 0; }",
	".framer-34ZDN.framer-v-5rr6ub .framer-1mtirf4 { cursor: pointer; max-width: 314px; padding: 1px 0px 1px 0px; }",
	".framer-34ZDN.framer-v-5rr6ub .framer-1t6pt8p { gap: 63px; }",
	".framer-34ZDN.framer-v-5rr6ub .framer-didmk4 { padding: 28px 0px 0px 0px; }",
	".framer-34ZDN.framer-v-5rr6ub .framer-j15gzc { align-content: flex-start; align-items: flex-start; }",
	".framer-34ZDN.framer-v-5rr6ub .framer-1y5a6m8 { height: var(--framer-aspect-ratio-supported, 73px); width: 243px; }",
	".framer-34ZDN.framer-v-5rr6ub .framer-kng59d { flex: 0.9 0 0px; width: 1px; }",
	".framer-34ZDN.framer-v-ye0vsa.framer-l0br6o { padding: 24px 16px 25px 16px; width: 320px; }",
	".framer-34ZDN.framer-v-ye0vsa .framer-691i0w { gap: 14px; }",
	".framer-34ZDN.framer-v-ye0vsa .framer-1oul79c { gap: 42px; height: min-content; }",
	".framer-34ZDN.framer-v-ye0vsa .framer-ji5s00 { flex-direction: column; gap: 48px; justify-content: flex-start; }",
	".framer-34ZDN.framer-v-ye0vsa .framer-1mtirf4 { flex: none; order: 0; width: 100%; }",
	".framer-34ZDN.framer-v-ye0vsa .framer-1t6pt8p { gap: 48px; justify-content: flex-start; order: 1; padding: 10px 0px 10px 0px; width: 100%; }",
	".framer-34ZDN.framer-v-ye0vsa .framer-11cz6xf, .framer-34ZDN.framer-v-ye0vsa .framer-1bf1dni { flex-direction: column; gap: 24px; }",
	".framer-34ZDN.framer-v-ye0vsa .framer-didmk4 { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 0px; justify-content: flex-start; }",
	".framer-34ZDN.framer-v-ye0vsa .framer-j15gzc { padding: 6px 0px 6px 0px; width: 100%; }",
	".framer-34ZDN.framer-v-ye0vsa .framer-1y5a6m8 { aspect-ratio: unset; height: 69px; width: 191px; }",
	".framer-34ZDN.framer-v-ye0vsa .framer-kng59d { flex: 1 0 0px; order: 0; width: 1px; }",
	".framer-34ZDN.framer-v-ye0vsa .framer-z4yo8m { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 0px; }",
	".framer-34ZDN.framer-v-ye0vsa .framer-14dqgzc { height: 12px; }",
	...css,
	...css2,
	...css3,
];
var FramervzcVpw93U = withCSS3(Component3, css7, "framer-34ZDN");
var stdin_default3 = FramervzcVpw93U;
FramervzcVpw93U.displayName = "Global/Footer";
FramervzcVpw93U.defaultProps = {
	height: 547,
	width: 1200,
};
addPropertyControls3(FramervzcVpw93U, {
	variant: {
		options: ["HLtzNlJv0", "eKPIUhuMd", "KSYecJg7z"],
		optionTitles: ["Desktop", "Tablet", "Mobile"],
		title: "Variant",
		type: ControlType3.Enum,
	},
});
addFonts3(
	FramervzcVpw93U,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...SecondaryFonts,
		...FooterUnderlineLinkFonts,
		...getFontsFromSharedStyle3(fonts),
		...getFontsFromSharedStyle3(fonts2),
		...getFontsFromSharedStyle3(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:global/footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "KSYecJg7z",
	md: "eKPIUhuMd",
	xl: "HLtzNlJv0",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var footer_default = ComponentWithRoot;
export { footer_default as default };
