// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c005e0105870bbbc "Mountain Futures (copy) (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Open' | 'Close' // Variant
}} Props

 */
import { routes } from "../chunks/chunk-MCZURAGM.js";

// virtual:accordion/accordion-close
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/2dAxlB2eN0otbxuOxGRZ/tfWyZseDNTNZCtOb6tiN/m3Ff0S3yj.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["fGLKpeUZ0", "zHD6Jle7K"];
var serializationHash = "framer-2ToF1";
var variantClassNames = {
	fGLKpeUZ0: "framer-v-1c3fdz4",
	zHD6Jle7K: "framer-v-s1tbt9",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var transition2 = {
	delay: 0,
	duration: 1,
	ease: [0.16, 1, 0.3, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Close: "zHD6Jle7K",
	Open: "fGLKpeUZ0",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "fGLKpeUZ0",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "fGLKpeUZ0",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							zHD6Jle7K: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1c3fdz4",
							className,
							classNames,
						)}
						data-framer-name={"Open"}
						layoutDependency={layoutDependency}
						layoutId={"fGLKpeUZ0"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-9fb4e60d-e27b-4970-96aa-c60f2b4ed70f, rgb(228, 228, 228))",
							borderBottomLeftRadius: 11,
							borderBottomRightRadius: 11,
							borderTopLeftRadius: 11,
							borderTopRightRadius: 11,
							rotate: 0,
							...style,
						}}
						variants={{
							zHD6Jle7K: {
								rotate: 45,
							},
						}}
						{...addPropertyOverrides(
							{
								zHD6Jle7K: {
									"data-framer-name": "Close",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-rr9wor"}
							layoutDependency={layoutDependency}
							layoutId={"ASfo14YDI"}
						>
							<motion.div
								className={"framer-f5bkko"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"gCLJcVaLG"}
								style={{
									backgroundColor:
										"var(--token-875c8959-f9ae-4048-a6ad-65d811feb19f, rgb(30, 30, 31))",
									rotate: 0,
								}}
								variants={{
									zHD6Jle7K: {
										rotate: 180,
									},
								}}
							/>
							<motion.div
								className={"framer-1s63vkp"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"DGe56zT86"}
								style={{
									backgroundColor:
										"var(--token-875c8959-f9ae-4048-a6ad-65d811feb19f, rgb(30, 30, 31))",
									rotate: 90,
								}}
								variants={{
									zHD6Jle7K: {
										rotate: 270,
									},
								}}
							/>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-2ToF1.framer-5i66t3, .framer-2ToF1 .framer-5i66t3 { display: block; }",
	".framer-2ToF1.framer-1c3fdz4 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 22px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 22px; }",
	".framer-2ToF1 .framer-rr9wor { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-2ToF1 .framer-f5bkko { flex: none; height: 1px; overflow: hidden; position: relative; width: 13px; }",
	".framer-2ToF1 .framer-1s63vkp { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 1px; top: 0px; z-index: 1; }",
];
var Framerm3Ff0S3yj = withCSS(Component, css, "framer-2ToF1");
var stdin_default = Framerm3Ff0S3yj;
Framerm3Ff0S3yj.displayName = "Accordion / Accordion Close";
Framerm3Ff0S3yj.defaultProps = {
	height: 22,
	width: 22,
};
addPropertyControls(Framerm3Ff0S3yj, {
	variant: {
		options: ["fGLKpeUZ0", "zHD6Jle7K"],
		optionTitles: ["Open", "Close"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	Framerm3Ff0S3yj,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:accordion/accordion-close
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "fGLKpeUZ0",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AccordionCloseFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var accordion_close_default = ComponentWithRoot;
export { accordion_close_default as default };
