#!/bin/bash
# Mountain Futures News Update
#
# Fetches candidates, uses Claude Code to filter/write posts,
# then creates a PR for review. Nothing publishes without your approval.
#
# Usage:
#   ./scripts/update-news.sh              # default 30 day lookback
#   LOOKBACK_DAYS=90 ./scripts/update-news.sh  # custom lookback

set -euo pipefail

# Allow running from cron or from within Claude Code
unset CLAUDECODE 2>/dev/null || true

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_DIR"

CANDIDATES_FILE=$(mktemp /tmp/news-candidates.XXXXX.json)
FILTERED_FILE=$(mktemp /tmp/news-filtered.XXXXX.json)
NEWS_JSON="$REPO_DIR/src/data/news.json"

cleanup() { rm -f "$CANDIDATES_FILE" "$FILTERED_FILE"; }
trap cleanup EXIT

echo "=== Step 1: Fetching candidates ==="
python3 scripts/fetch-news.py > "$CANDIDATES_FILE"

NUM_CANDIDATES=$(python3 -c "import json; print(len(json.load(open('$CANDIDATES_FILE'))))")
echo "Found $NUM_CANDIDATES new candidates"

if [ "$NUM_CANDIDATES" = "0" ]; then
    echo "No new candidates. Nothing to do."
    exit 0
fi

echo ""
echo "=== Step 2: Claude Code filtering and post generation ==="

# Build prompt file (avoids shell escaping issues with large JSON)
PROMPT_FILE=$(mktemp /tmp/news-prompt.XXXXX.txt)
cat > "$PROMPT_FILE" <<PROMPT
You are curating a news feed for Mountain Futures (mountainfutures.ch), a Swiss
consultancy by Joel Fiddes and Simon Allen focused on cryosphere science, mountain
hazards, and climate adaptation.

Key topics: snow monitoring (SnowMapper), glacial lake outburst floods (GLOFs),
cryosphere observation (CROMO-ADAPT), climate downscaling (TopoPyScale),
mountain hazard assessment, Central Asia, Himalaya, Andes.

EXISTING news posts (do NOT duplicate):
$(cat "$NEWS_JSON")

NEW candidates from automated search:
$(cat "$CANDIDATES_FILE")

INSTRUCTIONS:
1. STRICTLY filter: only include items directly about Mountain Futures' work, their
   named people (Joel Fiddes, Simon Allen — the cryosphere researchers, not other
   people with the same name), or their specific projects/topics.
2. REJECT generic climate/mountain news and papers by unrelated authors.
3. For accepted items, write a clean 1-2 sentence summary.

CRITICAL: When in doubt, EXCLUDE. Do NOT fabricate information.

Output ONLY a valid JSON array. Each item:
{"title": "<clean title>", "date": "<YYYY-MM-DD>", "summary": "<factual summary>", "link": "<URL>", "tags": ["tag1", "tag2"]}

If nothing is relevant, output: []
PROMPT

claude -p "$(cat "$PROMPT_FILE")" --output-format text > "$FILTERED_FILE"
rm -f "$PROMPT_FILE"

# Extract JSON array from Claude output (may contain extra text)
python3 -c "
import re, json
text = open('$FILTERED_FILE').read().strip()
# Try to find a JSON array in the output
match = re.search(r'\[.*\]', text, re.DOTALL)
if match:
    # Validate it's actual JSON
    try:
        parsed = json.loads(match.group())
        open('$FILTERED_FILE', 'w').write(json.dumps(parsed, indent=2))
    except json.JSONDecodeError:
        open('$FILTERED_FILE', 'w').write('[]')
else:
    open('$FILTERED_FILE', 'w').write('[]')
"

# Validate JSON output
if ! python3 -c "import json; json.load(open('$FILTERED_FILE'))" 2>/dev/null; then
    echo "Error: Claude output is not valid JSON:"
    cat "$FILTERED_FILE"
    exit 1
fi

NUM_POSTS=$(python3 -c "import json; print(len(json.load(open('$FILTERED_FILE'))))")
echo "Claude approved $NUM_POSTS items"

if [ "$NUM_POSTS" = "0" ]; then
    echo "No relevant items. Nothing to do."
    exit 0
fi

echo ""
echo "=== Step 3: Merging into news.json ==="

python3 -c "
import json
existing = json.load(open('$NEWS_JSON'))
new_posts = json.load(open('$FILTERED_FILE'))
existing_links = {item['link'] for item in existing}
added = [p for p in new_posts if p['link'] not in existing_links]
merged = added + existing
merged.sort(key=lambda x: x['date'], reverse=True)
with open('$NEWS_JSON', 'w') as f:
    json.dump(merged, f, indent=2, ensure_ascii=False)
    f.write('\n')
print(f'Added {len(added)} new items. Total: {len(merged)}')
for p in added:
    print(f'  + {p[\"title\"]}')
"

# Check if anything actually changed
if git diff --quiet src/data/news.json; then
    echo "No new items after dedup. Nothing to do."
    exit 0
fi

echo ""
echo "=== Step 4: Creating PR ==="

BRANCH="news-update-$(date +%Y%m%d-%H%M)"
git checkout -b "$BRANCH"
git add src/data/news.json
git commit -m "$(cat <<'EOF'
Add new items to news feed

Co-Authored-By: Claude Opus 4.6 <noreply@anthropic.com>
EOF
)"
git push origin "$BRANCH"

gh pr create \
    --title "News feed update $(date +%Y-%m-%d)" \
    --body "$(cat <<'EOF'
## New items found by automated search

Review the changes below. **Edit or remove any items** before merging.
Merging this PR will publish the items and trigger a site deploy.

---
*Generated by `scripts/update-news.sh`*
EOF
)" \
    --base main \
    --head "$BRANCH"

# Open PR in browser for review
PR_URL=$(gh pr view "$BRANCH" --json url -q '.url')
echo "Opening PR for review..."
open "$PR_URL"

# Also show a macOS notification
osascript -e "display notification \"$NUM_POSTS new items ready for review\" with title \"Mountain Futures News\" sound name \"Glass\""

# Switch back to main
git checkout main

echo ""
echo "Done! Review the PR on GitHub, edit if needed, then merge to publish."
