#!/bin/bash
# Mountain Futures News Update
#
# Fetches candidates, uses Claude Code to filter/write posts,
# then creates a PR for review. Nothing publishes without your approval.
#
# Usage:
#   ./scripts/update-news.sh              # default 30 day lookback
#   LOOKBACK_DAYS=90 ./scripts/update-news.sh  # custom lookback

set -euo pipefail

# Allow running from cron or from within Claude Code
unset CLAUDECODE 2>/dev/null || true

# cron runs with a minimal PATH (/usr/bin:/bin) — claude and gh are not on it.
# Without this the script dies at Step 2 with "claude: command not found".
export PATH="$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"

echo "=== Run started $(date '+%Y-%m-%d %H:%M:%S') ==="

# Fail loudly and early if a required tool is missing
for cmd in claude gh git python3; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        echo "Error: required command '$cmd' not found in PATH ($PATH)" >&2
        exit 1
    fi
done

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_DIR"

# Note: macOS BSD mktemp only randomizes trailing X's — no suffix after them.
CANDIDATES_FILE=$(mktemp /tmp/news-candidates.XXXXXX)
FILTERED_FILE=$(mktemp /tmp/news-filtered.XXXXXX)
NEWS_JSON="$REPO_DIR/src/data/news.json"

cleanup() { rm -f "$CANDIDATES_FILE" "$FILTERED_FILE"; }
trap cleanup EXIT

echo "=== Step 1: Fetching candidates ==="
python3 scripts/fetch-news.py > "$CANDIDATES_FILE"

NUM_CANDIDATES=$(python3 -c "import json; print(len(json.load(open('$CANDIDATES_FILE'))))")
echo "Found $NUM_CANDIDATES new candidates"

if [ "$NUM_CANDIDATES" = "0" ]; then
    echo "No new candidates. Nothing to do."
    exit 0
fi

echo ""
echo "=== Step 2: Filtering candidates ==="

# The prompt and both backends (Anthropic API when ANTHROPIC_API_KEY is set,
# otherwise the local claude CLI) live in filter-news.py, shared with the
# GitHub Action so the two cannot drift apart.
python3 scripts/filter-news.py "$CANDIDATES_FILE" "$NEWS_JSON" > "$FILTERED_FILE"

NUM_POSTS=$(python3 -c "import json; print(len(json.load(open('$FILTERED_FILE'))))")
echo "Approved $NUM_POSTS items"

if [ "$NUM_POSTS" = "0" ]; then
    echo "No relevant items. Nothing to do."
    exit 0
fi

echo ""
echo "=== Step 3: Merging into news.json ==="
python3 scripts/merge-news.py "$FILTERED_FILE" "$NEWS_JSON" || true


if git diff --quiet src/data/news.json; then
    echo "No new items after dedup. Nothing to do."
    exit 0
fi

echo ""
echo "=== Step 4: Creating PR ==="

BRANCH="news-update-$(date +%Y%m%d-%H%M)"
git checkout -b "$BRANCH"
git add src/data/news.json
git commit -m "$(cat <<'EOF'
Add new items to news feed

Co-Authored-By: Claude Opus 4.6 <noreply@anthropic.com>
EOF
)"
git push origin "$BRANCH"

gh pr create \
    --title "News feed update $(date +%Y-%m-%d)" \
    --body "$(cat <<'EOF'
## New items found by automated search

Review the changes below. **Edit or remove any items** before merging.
Merging this PR will publish the items and trigger a site deploy.

---
*Generated by `scripts/update-news.sh`*
EOF
)" \
    --base main \
    --head "$BRANCH"

# Open PR in browser for review
PR_URL=$(gh pr view "$BRANCH" --json url -q '.url')
echo "Opening PR for review..."
open "$PR_URL"

# Also show a macOS notification
osascript -e "display notification \"$NUM_POSTS new items ready for review\" with title \"Mountain Futures News\" sound name \"Glass\""

# Switch back to main
git checkout main

echo ""
echo "Done! Review the PR on GitHub, edit if needed, then merge to publish."
