// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c005e0105870bbbc "Mountain Futures (copy) (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Loading' | 'Disabled' | 'Success' | 'Error' // Variant
}} Props

 */
import { routes } from "../chunks/chunk-MCZURAGM.js";

// virtual:buttons/form
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/nXBQV2JNjmQbgPbsmlwr/wSlOdLFkUgrd8O8JB1He/w5VYyzHHp.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var enabledGestures = {
	XQIiyY64o: {
		hover: true,
		pressed: true,
	},
};
var cycleOrder = [
	"XQIiyY64o",
	"FicfZskJZ",
	"C2SMrqnri",
	"q9meynh2v",
	"cGUAmQ_kL",
];
var serializationHash = "framer-19zgL";
var variantClassNames = {
	C2SMrqnri: "framer-v-1nhc9e4",
	cGUAmQ_kL: "framer-v-1pmalml",
	FicfZskJZ: "framer-v-8fqvon",
	q9meynh2v: "framer-v-vzugs4",
	XQIiyY64o: "framer-v-1wcl1k",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.2,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var transition2 = {
	delay: 0,
	duration: 1,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "XQIiyY64o",
	Disabled: "C2SMrqnri",
	Error: "cGUAmQ_kL",
	Loading: "FicfZskJZ",
	Success: "q9meynh2v",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "XQIiyY64o",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "XQIiyY64o",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "FicfZskJZ") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "FicfZskJZ") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.button
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1wcl1k",
							className,
							classNames,
						)}
						data-framer-name={"Default"}
						data-reset={"button"}
						layoutDependency={layoutDependency}
						layoutId={"XQIiyY64o"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-43eac8f6-6121-473c-88d1-781f7c603ff3, rgb(185, 255, 255))",
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							opacity: 1,
							...style,
						}}
						variants={{
							"XQIiyY64o-hover": {
								backgroundColor:
									"var(--token-a7c87a03-e4bc-4fee-bd27-763511435b35, rgb(18, 32, 35))",
								opacity: 1,
							},
							"XQIiyY64o-pressed": {
								backgroundColor:
									"var(--token-a7c87a03-e4bc-4fee-bd27-763511435b35, rgb(18, 32, 35))",
								opacity: 1,
							},
							C2SMrqnri: {
								opacity: 0.5,
							},
							cGUAmQ_kL: {
								backgroundColor: "rgba(255, 34, 68, 0.15)",
								opacity: 1,
							},
							q9meynh2v: {
								opacity: 1,
							},
						}}
						{...addPropertyOverrides(
							{
								"XQIiyY64o-hover": {
									"data-framer-name": void 0,
								},
								"XQIiyY64o-pressed": {
									"data-framer-name": void 0,
								},
								C2SMrqnri: {
									"data-framer-name": "Disabled",
								},
								cGUAmQ_kL: {
									"data-framer-name": "Error",
								},
								FicfZskJZ: {
									"data-framer-name": "Loading",
								},
								q9meynh2v: {
									"data-framer-name": "Success",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1g6pffi"}
								fonts={["GF;DM Mono-500"]}
								layoutDependency={layoutDependency}
								layoutId={"eQNxpwZvP"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-a7c87a03-e4bc-4fee-bd27-763511435b35, rgb(18, 32, 35))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								variants={{
									"XQIiyY64o-hover": {
										"--extracted-r6o4lv":
											"var(--token-38406790-1041-404b-8965-34452f5c8f25, rgb(53, 228, 228))",
									},
									"XQIiyY64o-pressed": {
										"--extracted-r6o4lv":
											"var(--token-38406790-1041-404b-8965-34452f5c8f25, rgb(53, 228, 228))",
									},
									C2SMrqnri: {
										"--extracted-r6o4lv":
											"var(--token-8d839ec5-2551-4c63-8fc1-0d549252d6d5, rgb(191, 191, 191))",
									},
									cGUAmQ_kL: {
										"--extracted-r6o4lv": "rgb(255, 34, 68)",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										"XQIiyY64o-hover": {
											children: (
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "R0Y7RE0gTW9uby01MDA=",
															"--framer-font-family": '"DM Mono", monospace',
															"--framer-font-size": "14px",
															"--framer-font-weight": "500",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-38406790-1041-404b-8965-34452f5c8f25, rgb(53, 228, 228)))",
														}}
													>
														{"Submit"}
													</motion.p>
												</React.Fragment>
											),
										},
										"XQIiyY64o-pressed": {
											children: (
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "R0Y7RE0gTW9uby01MDA=",
															"--framer-font-family": '"DM Mono", monospace',
															"--framer-font-size": "14px",
															"--framer-font-weight": "500",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-38406790-1041-404b-8965-34452f5c8f25, rgb(53, 228, 228)))",
														}}
													>
														{"Submit"}
													</motion.p>
												</React.Fragment>
											),
										},
										C2SMrqnri: {
											children: (
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "R0Y7RE0gTW9uby01MDA=",
															"--framer-font-family": '"DM Mono", monospace',
															"--framer-font-size": "14px",
															"--framer-font-weight": "500",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-8d839ec5-2551-4c63-8fc1-0d549252d6d5, rgb(191, 191, 191)))",
														}}
													>
														{"Submit"}
													</motion.p>
												</React.Fragment>
											),
										},
										cGUAmQ_kL: {
											children: (
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "R0Y7R2Vpc3QtNTAw",
															"--framer-font-family":
																'"Geist", "Geist Placeholder", sans-serif',
															"--framer-font-size": "14px",
															"--framer-font-weight": "500",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(255, 34, 68))",
														}}
													>
														{"Something went wrong"}
													</motion.p>
												</React.Fragment>
											),
											fonts: ["GF;Geist-500"],
										},
										q9meynh2v: {
											children: (
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "R0Y7R2Vpc3QtNTAw",
															"--framer-font-family":
																'"Geist", "Geist Placeholder", sans-serif',
															"--framer-font-size": "14px",
															"--framer-font-weight": "500",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-a7c87a03-e4bc-4fee-bd27-763511435b35, rgb(18, 32, 35)))",
														}}
													>
														{"Thank you"}
													</motion.p>
												</React.Fragment>
											),
											fonts: ["GF;Geist-500"],
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--font-selector": "R0Y7RE0gTW9uby01MDA=",
											"--framer-font-family": '"DM Mono", monospace',
											"--framer-font-size": "14px",
											"--framer-font-weight": "500",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-a7c87a03-e4bc-4fee-bd27-763511435b35, rgb(18, 32, 35)))",
										}}
									>
										{"Submit"}
									</motion.p>
								</React.Fragment>
							</RichText>
						)}
						{isDisplayed1() && (
							<motion.div
								className={"framer-1bdzj0b"}
								data-framer-name={"Spinner"}
								layoutDependency={layoutDependency}
								layoutId={"CYTUFhgCz"}
								style={{
									mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
									WebkitMask:
										"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
								}}
							>
								<MotionDivWithFX
									__framer__loop={animation}
									__framer__loopEffectEnabled={true}
									__framer__loopRepeatDelay={0}
									__framer__loopRepeatType={"loop"}
									__framer__loopTransition={transition2}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-nsrlsk"}
									data-framer-name={"Conic"}
									layoutDependency={layoutDependency}
									layoutId={"tZbo5gFov"}
									style={{
										background:
											"conic-gradient(from 0deg at 50% 50%, var(--token-992d3a9c-930b-401c-972e-d2075121c037, rgb(30, 30, 31)) 7.208614864864882deg, rgb(255, 255, 255) 342deg)",
										mask: "none",
										WebkitMask: "none",
									}}
									variants={{
										FicfZskJZ: {
											mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
											WebkitMask:
												"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
										},
									}}
								>
									<motion.div
										className={"framer-8aov5h"}
										data-framer-name={"Rounding"}
										layoutDependency={layoutDependency}
										layoutId={"sdOxODcWz"}
										style={{
											backgroundColor: "rgb(255, 255, 255)",
											borderBottomLeftRadius: 1,
											borderBottomRightRadius: 1,
											borderTopLeftRadius: 1,
											borderTopRightRadius: 1,
										}}
										transformTemplate={transformTemplate1}
									/>
								</MotionDivWithFX>
							</motion.div>
						)}
					</motion.button>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-19zgL.framer-uqstdk, .framer-19zgL .framer-uqstdk { display: block; }",
	".framer-19zgL.framer-1wcl1k { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 40px; justify-content: center; overflow: visible; padding: 8px 16px 8px 16px; position: relative; width: min-content; }",
	".framer-19zgL .framer-1g6pffi { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-19zgL .framer-1bdzj0b { aspect-ratio: 1 / 1; flex: none; gap: 10px; height: var(--framer-aspect-ratio-supported, 20px); overflow: hidden; position: relative; width: 20px; }",
	".framer-19zgL .framer-nsrlsk { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
	".framer-19zgL .framer-8aov5h { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 2px); left: 50%; overflow: visible; position: absolute; top: 0px; width: 2px; }",
	".framer-19zgL.framer-v-8fqvon.framer-1wcl1k, .framer-19zgL.framer-v-1nhc9e4.framer-1wcl1k, .framer-19zgL.framer-v-vzugs4.framer-1wcl1k, .framer-19zgL.framer-v-1pmalml.framer-1wcl1k { cursor: unset; }",
	".framer-19zgL.framer-v-8fqvon .framer-nsrlsk { overflow: hidden; }",
];
var Framerw5VYyzHHp = withCSS(Component, css, "framer-19zgL");
var stdin_default = Framerw5VYyzHHp;
Framerw5VYyzHHp.displayName = "Buttons/Form";
Framerw5VYyzHHp.defaultProps = {
	height: 40,
	width: 82.4,
};
addPropertyControls(Framerw5VYyzHHp, {
	variant: {
		options: ["XQIiyY64o", "FicfZskJZ", "C2SMrqnri", "q9meynh2v", "cGUAmQ_kL"],
		optionTitles: ["Default", "Loading", "Disabled", "Success", "Error"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	Framerw5VYyzHHp,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "DM Mono",
					source: "google",
					style: "normal",
					uiFamilyName: "DM Mono",
					url: "https://fonts.gstatic.com/s/dmmono/v16/aFTR7PB1QTsUX8KYvumzIYGnbKX9Rlk.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Geist",
					source: "google",
					style: "normal",
					uiFamilyName: "Geist",
					url: "https://fonts.gstatic.com/s/geist/v4/gyBhhwUxId8gMGYQMKR3pzfaWI_RruM4mJPby1QNtA.woff2",
					weight: "500",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:buttons/form
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "XQIiyY64o",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FormFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var form_default = ComponentWithRoot;
export { form_default as default };
