// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c005e0105870bbbc "Mountain Futures (copy) (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Mobile' // Variant
 * number?: string // Number
 * jobName?: string // Job Name
 * location?: string // Location
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-ZVSW4UDK.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-E2DSRDMQ.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-XOYYYZYZ.js";
import { routes } from "./chunks/chunk-MCZURAGM.js";

// virtual:careers-row
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/itDKGyS9kjKoUt4yMpYL/vkuuPSMdEQRhK5G3ee46/znyY0hwrW.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	eNiO4wfXh: {
		hover: true,
	},
	OpdfGNKf7: {
		hover: true,
	},
};
var cycleOrder = ["OpdfGNKf7", "eNiO4wfXh"];
var serializationHash = "framer-EUsmN";
var variantClassNames = {
	eNiO4wfXh: "framer-v-nwh6od",
	OpdfGNKf7: "framer-v-jlgy6a",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.6,
	ease: [0.08, 0.78, 0.56, 1],
	type: "tween",
};
var transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "OpdfGNKf7",
	Mobile: "eNiO4wfXh",
};
var getProps = ({ height, id, jobName, location, number, width, ...props }) => {
	return {
		...props,
		InbZJUDv2: location ?? props.InbZJUDv2 ?? "Lonodn, UK",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "OpdfGNKf7",
		weJa9D0o1: jobName ?? props.weJa9D0o1 ?? "Product Manager",
		zr2a_BehH: number ?? props.zr2a_BehH ?? "01",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		zr2a_BehH,
		weJa9D0o1,
		InbZJUDv2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "OpdfGNKf7",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className, className3];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-jlgy6a",
							className4,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"OpdfGNKf7"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "0px",
							"--border-color":
								"var(--token-4a657333-042a-4ee5-8ab0-89f8b6ae1452, rgb(218, 218, 218))",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							...style,
						}}
						{...addPropertyOverrides(
							{
								"eNiO4wfXh-hover": {
									"data-framer-name": void 0,
								},
								"OpdfGNKf7-hover": {
									"data-framer-name": void 0,
								},
								eNiO4wfXh: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1eqva55"}
							data-framer-name={"Wrap"}
							layoutDependency={layoutDependency}
							layoutId={"yFef6Zbxg"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-162shkk"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"fyCUMrja7"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={zr2a_BehH}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-16bupuy"}
										data-styles-preset={"pJrILY7rY"}
									>
										{"01"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-iex1ho"}
								layoutDependency={layoutDependency}
								layoutId={"j9j4qQykI"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-15zcaoq"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"ruvNoyZEo"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={weJa9D0o1}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-rwcd89"}
											data-styles-preset={"fVNgQUCuM"}
										>
											{"Product Manager"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-jzylc6"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"OQ6P8cRpl"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-875c8959-f9ae-4048-a6ad-65d811feb19f, rgb(30, 30, 31))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={InbZJUDv2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-16bupuy"}
											data-styles-preset={"pJrILY7rY"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-875c8959-f9ae-4048-a6ad-65d811feb19f, rgb(30, 30, 31)))",
											}}
										>
											{"Lonodn, UK"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
						<motion.div
							className={"framer-1ie39qb"}
							data-framer-name={"Button Wrapper"}
							layoutDependency={layoutDependency}
							layoutId={"JuXVZSamT"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-6bduap"}
								data-framer-name={"Text"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"cuFEua63h"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1tix7ms"}
										data-styles-preset={"PNrJZBqkc"}
									>
										{"View on Linkedin"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-16chcrb"}
								data-framer-name={"Clip"}
								layoutDependency={layoutDependency}
								layoutId={"PImHYdvzR"}
							>
								<motion.div
									className={"framer-13gs2hj"}
									data-framer-name={"Arrow Wrapper"}
									layoutDependency={layoutDependency}
									layoutId={"IKxethSEg"}
									transformTemplate={transformTemplate1}
								>
									<SVG
										className={"framer-1e05ia4"}
										data-framer-name={"Geist Arrow"}
										layout={"position"}
										layoutDependency={layoutDependency}
										layoutId={"T7GX9RcuV"}
										opacity={1}
										svg={
											'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 16 13"><path d="M 5.261 11.942 L 10.234 6.97 L 0 6.97 L 0 4.992 L 10.272 4.992 L 5.28 0 L 7.68 0 L 13.632 5.971 L 7.661 11.942 Z" transform="translate(0.883 0.032) rotate(-360 6.75 6)" fill="var(--token-425d5885-8b67-4657-91de-de73d3d0dc86, rgb(0, 0, 0))"></path></svg>'
										}
										svgContentId={9220806156}
										withExternalLayout={true}
									/>
									<SVG
										className={"framer-gjyqlr"}
										data-framer-name={"Geist Arrow"}
										layout={"position"}
										layoutDependency={layoutDependency}
										layoutId={"gPAWtUkoD"}
										opacity={1}
										svg={
											'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 16 12.8"><path d="M 5.261 11.942 L 10.234 6.97 L 0 6.97 L 0 4.992 L 10.272 4.992 L 5.28 0 L 7.68 0 L 13.632 5.971 L 7.661 11.942 Z" transform="translate(0.883 0.032) rotate(-360 6.75 6)" fill="var(--token-425d5885-8b67-4657-91de-de73d3d0dc86, rgb(0, 0, 0))"></path></svg>'
										}
										svgContentId={11795098299}
										withExternalLayout={true}
									/>
								</motion.div>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-EUsmN.framer-1yg188c, .framer-EUsmN .framer-1yg188c { display: block; }",
	".framer-EUsmN.framer-jlgy6a { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 48px 0px 48px 0px; position: relative; width: 1040px; }",
	".framer-EUsmN .framer-1eqva55 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-EUsmN .framer-162shkk, .framer-EUsmN .framer-15zcaoq, .framer-EUsmN .framer-jzylc6 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-EUsmN .framer-iex1ho { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-EUsmN .framer-1ie39qb { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 4px 0px 4px 0px; position: relative; width: min-content; }",
	".framer-EUsmN .framer-6bduap { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 2; }",
	".framer-EUsmN .framer-16chcrb { flex: none; gap: 10px; height: 20px; overflow: hidden; position: relative; width: 20px; z-index: 2; }",
	".framer-EUsmN .framer-13gs2hj { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: absolute; right: 0px; top: 50%; width: min-content; }",
	".framer-EUsmN .framer-1e05ia4, .framer-EUsmN .framer-gjyqlr { flex: none; height: 13px; position: relative; width: 16px; }",
	".framer-EUsmN.framer-v-nwh6od.framer-jlgy6a { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 32px; justify-content: flex-start; padding: 32px 0px 32px 0px; width: 390px; }",
	".framer-EUsmN.framer-v-nwh6od .framer-1eqva55 { flex: none; flex-direction: column; gap: 24px; width: 100%; }",
	".framer-EUsmN.framer-v-nwh6od .framer-iex1ho { gap: 16px; }",
	".framer-EUsmN.framer-v-jlgy6a.hover.framer-jlgy6a { padding: 48px 0px 48px 32px; }",
	".framer-EUsmN.framer-v-jlgy6a.hover .framer-13gs2hj { left: 2px; right: unset; }",
	...css2,
	...css,
	...css3,
	'.framer-EUsmN[data-border="true"]::after, .framer-EUsmN [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerznyY0hwrW = withCSS(Component, css4, "framer-EUsmN");
var stdin_default = FramerznyY0hwrW;
FramerznyY0hwrW.displayName = "Careers Row";
FramerznyY0hwrW.defaultProps = {
	height: 164,
	width: 1040,
};
addPropertyControls(FramerznyY0hwrW, {
	variant: {
		options: ["OpdfGNKf7", "eNiO4wfXh"],
		optionTitles: ["Desktop", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	zr2a_BehH: {
		defaultValue: "01",
		title: "Number",
		type: ControlType.String,
	},
	weJa9D0o1: {
		defaultValue: "Product Manager",
		title: "Job Name",
		type: ControlType.String,
	},
	InbZJUDv2: {
		defaultValue: "Lonodn, UK",
		title: "Location",
		type: ControlType.String,
	},
});
addFonts(
	FramerznyY0hwrW,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:careers-row
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "eNiO4wfXh",
	xl: "OpdfGNKf7",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CareersRowFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var careers_row_default = ComponentWithRoot;
export { careers_row_default as default };
