// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c005e0105870bbbc "Mountain Futures (copy) (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Hover In' | 'Mobile' // Variant
 * text?: string // Text
 * link?: string // Link
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-XOYYYZYZ.js";
import { routes } from "./chunks/chunk-MCZURAGM.js";

// virtual:careers-button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/gKdBEV35ivZ0dnXnCf35/l1ka5cysE3t5x28biKyW/LL46uBwCK.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	SVG,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["YN8BfYfj5", "bQFF6pmVp", "uTFrCM6zQ"];
var serializationHash = "framer-xivam";
var variantClassNames = {
	bQFF6pmVp: "framer-v-uxqeuj",
	uTFrCM6zQ: "framer-v-1g162r3",
	YN8BfYfj5: "framer-v-1nicaj6",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.6,
	ease: [0.08, 0.78, 0.56, 1],
	type: "tween",
};
var transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Hover In": "bQFF6pmVp",
	Desktop: "YN8BfYfj5",
	Mobile: "uTFrCM6zQ",
};
var getProps = ({ height, id, link, text, width, ...props }) => {
	return {
		...props,
		BYNIrUSxY: text ?? props.BYNIrUSxY ?? "Button Text",
		F3zKmwx_W: link ?? props.F3zKmwx_W,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "YN8BfYfj5",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		BYNIrUSxY,
		F3zKmwx_W,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "YN8BfYfj5",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnter1ckvd48 = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		setVariant("bQFF6pmVp");
	});
	const onMouseLeave8uq4fw = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		setVariant("YN8BfYfj5");
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						motionChild={true}
						nodeId={"YN8BfYfj5"}
						scopeId={"LL46uBwCK"}
						{...addPropertyOverrides(
							{
								bQFF6pmVp: {
									href: F3zKmwx_W,
								},
								uTFrCM6zQ: {
									href: F3zKmwx_W,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-1nicaj6", className2, classNames)} framer-ut5khq`}
							data-framer-name={"Desktop"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"YN8BfYfj5"}
							onMouseEnter={onMouseEnter1ckvd48}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									bQFF6pmVp: {
										"data-framer-name": "Hover In",
										onMouseLeave: onMouseLeave8uq4fw,
									},
									uTFrCM6zQ: {
										"data-framer-name": "Mobile",
										"data-highlight": void 0,
										onMouseEnter: void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-1rokasa"}
								data-framer-name={"Button Wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"nrmKunhnq"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-gaw2ul"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"dj5UsZVsD"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={BYNIrUSxY}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1tix7ms"}
											data-styles-preset={"PNrJZBqkc"}
										>
											{"Button Text"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<motion.div
									className={"framer-k6d0s6"}
									data-framer-name={"Clip"}
									layoutDependency={layoutDependency}
									layoutId={"l9o37NqfX"}
								>
									<motion.div
										className={"framer-k6tbq8"}
										data-framer-name={"Arrow Wrapper"}
										layoutDependency={layoutDependency}
										layoutId={"ZRg8pC24J"}
										transformTemplate={transformTemplate1}
									>
										<SVG
											className={"framer-1mu5l3s"}
											data-framer-name={"Geist Arrow"}
											layout={"position"}
											layoutDependency={layoutDependency}
											layoutId={"jxKI6tJkE"}
											opacity={1}
											svg={
												'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 16 13"><path d="M 5.261 11.942 L 10.234 6.97 L 0 6.97 L 0 4.992 L 10.272 4.992 L 5.28 0 L 7.68 0 L 13.632 5.971 L 7.661 11.942 Z" transform="translate(0.883 0.032) rotate(-360 6.75 6)" fill="var(--token-16576700-d6fd-4b9f-9ae4-4f307b03cbd5, rgb(17, 17, 17))"></path></svg>'
											}
											svgContentId={9826502469}
											withExternalLayout={true}
										/>
										<SVG
											className={"framer-q8ewvd"}
											data-framer-name={"Geist Arrow"}
											layout={"position"}
											layoutDependency={layoutDependency}
											layoutId={"Y5Fwl7MHK"}
											opacity={1}
											svg={
												'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 16 12.8"><path d="M 5.261 11.942 L 10.234 6.97 L 0 6.97 L 0 4.992 L 10.272 4.992 L 5.28 0 L 7.68 0 L 13.632 5.971 L 7.661 11.942 Z" transform="translate(0.883 0.032) rotate(-360 6.75 6)" fill="var(--token-16576700-d6fd-4b9f-9ae4-4f307b03cbd5, rgb(17, 17, 17))"></path></svg>'
											}
											svgContentId={9471455529}
											withExternalLayout={true}
										/>
									</motion.div>
								</motion.div>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-xivam.framer-ut5khq, .framer-xivam .framer-ut5khq { display: block; }",
	".framer-xivam.framer-1nicaj6 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-xivam .framer-1rokasa { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 4px 0px 4px 0px; position: relative; width: min-content; }",
	".framer-xivam .framer-gaw2ul { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 2; }",
	".framer-xivam .framer-k6d0s6 { flex: none; gap: 10px; height: 20px; overflow: hidden; position: relative; width: 20px; z-index: 2; }",
	".framer-xivam .framer-k6tbq8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: absolute; right: 0px; top: 50%; width: min-content; }",
	".framer-xivam .framer-1mu5l3s, .framer-xivam .framer-q8ewvd { flex: none; height: 13px; position: relative; width: 16px; }",
	".framer-xivam.framer-v-uxqeuj.framer-1nicaj6, .framer-xivam.framer-v-1g162r3.framer-1nicaj6 { text-decoration: none; }",
	".framer-xivam.framer-v-uxqeuj .framer-k6tbq8 { left: 0px; right: unset; }",
	...css,
];
var FramerLL46uBwCK = withCSS(Component, css2, "framer-xivam");
var stdin_default = FramerLL46uBwCK;
FramerLL46uBwCK.displayName = "Careers Button";
FramerLL46uBwCK.defaultProps = {
	height: 28,
	width: 97,
};
addPropertyControls(FramerLL46uBwCK, {
	variant: {
		options: ["YN8BfYfj5", "bQFF6pmVp", "uTFrCM6zQ"],
		optionTitles: ["Desktop", "Hover In", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	BYNIrUSxY: {
		defaultValue: "Button Text",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	F3zKmwx_W: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerLL46uBwCK,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:careers-button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CareersButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var careers_button_default = ComponentWithRoot;
export { careers_button_default as default };
