// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c005e0105870bbbc "Mountain Futures (copy) (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // Title
 * description?: string // Description
 * image?: {src: string, srcSet?: string, alt?: string} // Image
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-ZVSW4UDK.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-XOYYYZYZ.js";
import { routes } from "./chunks/chunk-MCZURAGM.js";

// virtual:data-visual-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/n6Tsc4nV0ELyhac0FMfj/ZS8cYpqYscBo0WuttoeX/YBFAtft7b.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-kFQya";
var variantClassNames = {
	gSc8ouvgR: "framer-v-1b3unkf",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ description, height, id, image, title, width, ...props }) => {
	return {
		...props,
		BB1bptQCp:
			description ??
			props.BB1bptQCp ??
			"Hydra's solutions help clients save on energy costs through optimization and renewable energy.",
		rKWZp0Ym4: image ??
			props.rKWZp0Ym4 ?? {
				pixelHeight: 139,
				pixelWidth: 168,
				src: "https://framerusercontent.com/images/vgPCrep4mVcCKBBQEkQ1L9Ur300.svg",
			},
		u3uODV_em: title ?? props.u3uODV_em ?? "Headline",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		u3uODV_em,
		BB1bptQCp,
		rKWZp0Ym4,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "gSc8ouvgR",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1b3unkf",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"gSc8ouvgR"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-d9340a14-727b-4bd4-bace-fe44143906be, rgb(26, 44, 48))",
							...style,
						}}
					>
						<motion.div
							className={"framer-d3c6fr"}
							data-framer-name={"Top"}
							layoutDependency={layoutDependency}
							layoutId={"mCC4ad_Gs"}
						>
							<Image
								background={{
									alt: "",
									fit: "fit",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											24 +
											0 +
											(0 +
												(Math.max(
													0,
													((componentViewport?.height || 439) - 48 - 147.65) /
														1,
												) *
													1 -
													0 -
													120) /
													2),
									),
									sizes: "120px",
									...toResponsiveImage(rKWZp0Ym4),
									...{
										positionX: "center",
										positionY: "center",
									},
								}}
								className={"framer-12zydux"}
								data-framer-name={"Icon"}
								layoutDependency={layoutDependency}
								layoutId={"mIszib9k0"}
							/>
						</motion.div>
						<motion.div
							className={"framer-mbvdy1"}
							data-framer-name={"Bottom"}
							layoutDependency={layoutDependency}
							layoutId={"rzdWTQPd_"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-6i3a0w"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Z8CRbLKmD"}
								style={{
									"--extracted-a0htzi":
										"var(--token-a5f2dea9-e675-4451-817f-b93e011b3b4d, rgb(225, 252, 173))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={u3uODV_em}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h3
										className={"framer-styles-preset-rwcd89"}
										data-styles-preset={"fVNgQUCuM"}
										style={{
											"--framer-text-color":
												"var(--extracted-a0htzi, var(--token-a5f2dea9-e675-4451-817f-b93e011b3b4d, rgb(225, 252, 173)))",
										}}
									>
										{"Headline"}
									</motion.h3>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-sr3or7"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Ys7zuRX6F"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-a5f2dea9-e675-4451-817f-b93e011b3b4d, rgb(225, 252, 173))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={BB1bptQCp}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1tix7ms"}
										data-styles-preset={"PNrJZBqkc"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-a5f2dea9-e675-4451-817f-b93e011b3b4d, rgb(225, 252, 173)))",
										}}
									>
										{
											"Hydra's solutions help clients save on energy costs through optimization and renewable energy."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-kFQya.framer-1ttk364, .framer-kFQya .framer-1ttk364 { display: block; }",
	".framer-kFQya.framer-1b3unkf { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 439px; justify-content: flex-start; overflow: hidden; padding: 24px; position: relative; width: 370px; }",
	".framer-kFQya .framer-d3c6fr { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 1px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-kFQya .framer-12zydux { flex: none; height: 120px; position: relative; width: 120px; }",
	".framer-kFQya .framer-mbvdy1 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-kFQya .framer-6i3a0w, .framer-kFQya .framer-sr3or7 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	...css,
	...css2,
];
var FramerYBFAtft7b = withCSS(Component, css3, "framer-kFQya");
var stdin_default = FramerYBFAtft7b;
FramerYBFAtft7b.displayName = "Data Visual Card";
FramerYBFAtft7b.defaultProps = {
	height: 439,
	width: 370,
};
addPropertyControls(FramerYBFAtft7b, {
	u3uODV_em: {
		defaultValue: "Headline",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	BB1bptQCp: {
		defaultValue:
			"Hydra's solutions help clients save on energy costs through optimization and renewable energy.",
		displayTextArea: true,
		title: "Description",
		type: ControlType.String,
	},
	rKWZp0Ym4: {
		__defaultAssetReference:
			"data:framer/asset-reference,vgPCrep4mVcCKBBQEkQ1L9Ur300.svg?originalFilename=Graph_2.svg&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerYBFAtft7b,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:data-visual-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders DataVisualCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var data_visual_card_default = ComponentWithRoot;
export { data_visual_card_default as default };
