// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c005e0105870bbbc "Mountain Futures (copy) (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Mobile' // Variant
 * title?: string // Title
 * overview?: string // Overview
 * icon?: {src: string, srcSet?: string, alt?: string} // Icon
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-E2DSRDMQ.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-YULNS5JV.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-XOYYYZYZ.js";
import { routes } from "./chunks/chunk-MCZURAGM.js";

// virtual:focus-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/nb3DEa4KlQzjYbQFqCXE/wDpIhRY0AS0gYMYA7RFL/hS1ai5DiN.js
import {
	jsx as _jsx3,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType3,
	cx,
	Floating,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOverlayState,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import {
	AnimatePresence,
	LayoutGroup,
	motion as motion2,
	MotionConfigContext,
} from "unframer";
import * as React3 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/p8dptk4UIND8hbFWz9V7/Phosphor.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import * as React2 from "react";
import { useState, useEffect, useRef } from "react";
import {
	addPropertyControls,
	ControlType as ControlType2,
	RenderTarget,
} from "unframer";
import { motion } from "unframer";

// /:https://framerusercontent.com/modules/DyldKav0OOAWR3bCAlhK/8c3l9FzyOlGpbPncYhfc/nullstate.js
import { jsx as _jsx } from "react/jsx-runtime";
import * as React from "react";
var containerStyles = {
	width: "100%",
	height: "100%",
	display: "flex",
	justifyContent: "center",
	alignItems: "center",
};
var emptyStateStyle = {
	...containerStyles,
	borderRadius: 6,
	background: "rgba(149, 149, 149, 0.1)",
	border: "1px dashed rgba(149, 149, 149, 0.15)",
	color: "#a5a5a5",
	flexDirection: "column",
};
var NullState = /* @__PURE__ */ React.forwardRef((_, ref) => {
	return <div style={emptyStateStyle} ref={ref} />;
});

// /:https://framerusercontent.com/modules/Qc8yuHkQmGO0kFiSWbkX/rVmMAFttOHuuiwSg6KjZ/House.js
var Component;
var IconInner;
var Icon = (React4) => {
	if (!Component) {
		Component = /* @__PURE__ */ new Map([
			[
				"bold",
				/* @__PURE__ */ React4.createElement(
					React4.Fragment,
					null,
					/* @__PURE__ */ React4.createElement("path", {
						d: "M222.14,105.85l-80-80a20,20,0,0,0-28.28,0l-80,80A19.86,19.86,0,0,0,28,120v96a12,12,0,0,0,12,12h64a12,12,0,0,0,12-12V164h24v52a12,12,0,0,0,12,12h64a12,12,0,0,0,12-12V120A19.86,19.86,0,0,0,222.14,105.85ZM204,204H164V152a12,12,0,0,0-12-12H104a12,12,0,0,0-12,12v52H52V121.65l76-76,76,76Z",
					}),
				),
			],
			[
				"duotone",
				/* @__PURE__ */ React4.createElement(
					React4.Fragment,
					null,
					/* @__PURE__ */ React4.createElement("path", {
						d: "M216,120v96H152V152H104v64H40V120a8,8,0,0,1,2.34-5.66l80-80a8,8,0,0,1,11.32,0l80,80A8,8,0,0,1,216,120Z",
						opacity: "0.2",
					}),
					/* @__PURE__ */ React4.createElement("path", {
						d: "M219.31,108.68l-80-80a16,16,0,0,0-22.62,0l-80,80A15.87,15.87,0,0,0,32,120v96a8,8,0,0,0,8,8h64a8,8,0,0,0,8-8V160h32v56a8,8,0,0,0,8,8h64a8,8,0,0,0,8-8V120A15.87,15.87,0,0,0,219.31,108.68ZM208,208H160V152a8,8,0,0,0-8-8H104a8,8,0,0,0-8,8v56H48V120l80-80,80,80Z",
					}),
				),
			],
			[
				"fill",
				/* @__PURE__ */ React4.createElement(
					React4.Fragment,
					null,
					/* @__PURE__ */ React4.createElement("path", {
						d: "M224,120v96a8,8,0,0,1-8,8H160a8,8,0,0,1-8-8V164a4,4,0,0,0-4-4H108a4,4,0,0,0-4,4v52a8,8,0,0,1-8,8H40a8,8,0,0,1-8-8V120a16,16,0,0,1,4.69-11.31l80-80a16,16,0,0,1,22.62,0l80,80A16,16,0,0,1,224,120Z",
					}),
				),
			],
			[
				"light",
				/* @__PURE__ */ React4.createElement(
					React4.Fragment,
					null,
					/* @__PURE__ */ React4.createElement("path", {
						d: "M217.9,110.1l-80-80a14,14,0,0,0-19.8,0l-80,80A13.92,13.92,0,0,0,34,120v96a6,6,0,0,0,6,6h64a6,6,0,0,0,6-6V158h36v58a6,6,0,0,0,6,6h64a6,6,0,0,0,6-6V120A13.92,13.92,0,0,0,217.9,110.1ZM210,210H158V152a6,6,0,0,0-6-6H104a6,6,0,0,0-6,6v58H46V120a2,2,0,0,1,.58-1.42l80-80a2,2,0,0,1,2.84,0l80,80A2,2,0,0,1,210,120Z",
					}),
				),
			],
			[
				"regular",
				/* @__PURE__ */ React4.createElement(
					React4.Fragment,
					null,
					/* @__PURE__ */ React4.createElement("path", {
						d: "M219.31,108.68l-80-80a16,16,0,0,0-22.62,0l-80,80A15.87,15.87,0,0,0,32,120v96a8,8,0,0,0,8,8h64a8,8,0,0,0,8-8V160h32v56a8,8,0,0,0,8,8h64a8,8,0,0,0,8-8V120A15.87,15.87,0,0,0,219.31,108.68ZM208,208H160V152a8,8,0,0,0-8-8H104a8,8,0,0,0-8,8v56H48V120l80-80,80,80Z",
					}),
				),
			],
			[
				"thin",
				/* @__PURE__ */ React4.createElement(
					React4.Fragment,
					null,
					/* @__PURE__ */ React4.createElement("path", {
						d: "M216.49,111.51l-80-80a12,12,0,0,0-17,0l-80,80A12,12,0,0,0,36,120v96a4,4,0,0,0,4,4h64a4,4,0,0,0,4-4V156h40v60a4,4,0,0,0,4,4h64a4,4,0,0,0,4-4V120A12,12,0,0,0,216.49,111.51ZM212,212H156V152a4,4,0,0,0-4-4H104a4,4,0,0,0-4,4v60H44V120a4,4,0,0,1,1.17-2.83l80-80a4,4,0,0,1,5.66,0l80,80A4,4,0,0,1,212,120Z",
					}),
				),
			],
		]);
		IconInner = React4.forwardRef((props, ref) =>
			/* @__PURE__ */ React4.createElement(
				"g",
				{
					ref,
					...props,
				},
				Component.get(props.weight),
			),
		);
	}
	return IconInner;
};
var House_default = Icon;

// /:https://framerusercontent.com/modules/Ma20hU0GGRxLxZphbywl/OSpwWF91FHPVFyQJjMHt/utils.js
import { useMemo } from "react";
import { ControlType } from "unframer";
var defaultEvents = {
	onClick: {
		type: ControlType.EventHandler,
	},
	onMouseDown: {
		type: ControlType.EventHandler,
	},
	onMouseUp: {
		type: ControlType.EventHandler,
	},
	onMouseEnter: {
		type: ControlType.EventHandler,
	},
	onMouseLeave: {
		type: ControlType.EventHandler,
	},
};
var findByArray = (arr, search) =>
	arr.find((a) => a.toLowerCase().includes(search));
function useIconSelection(
	iconKeys2,
	selectByList,
	iconSearch = "",
	iconSelection,
	lowercaseIconKeyPairs2,
) {
	const iconSearchResult = useMemo(() => {
		if (
			iconSearch == null ||
			(iconSearch === null || iconSearch === void 0
				? void 0
				: iconSearch.length) === 0
		)
			return null;
		const iconSearchTerm = iconSearch.toLowerCase().replace(/-|\s/g, "");
		var _iconSearchTerm;
		const searchResult =
			(_iconSearchTerm = lowercaseIconKeyPairs2[iconSearchTerm]) !== null &&
			_iconSearchTerm !== void 0
				? _iconSearchTerm
				: findByArray(iconKeys2, iconSearchTerm);
		return searchResult;
	}, [iconSelection, iconSearch]);
	const name = selectByList ? iconSelection : iconSearchResult;
	return name;
}

// /:https://framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/p8dptk4UIND8hbFWz9V7/Phosphor.js
var iconKeys = [
	"Acorn",
	"AddressBook",
	"AddressBookTabs",
	"AirTrafficControl",
	"Airplane",
	"AirplaneInFlight",
	"AirplaneLanding",
	"AirplaneTakeoff",
	"AirplaneTaxiing",
	"AirplaneTilt",
	"Airplay",
	"Alarm",
	"Alien",
	"AlignBottom",
	"AlignBottomSimple",
	"AlignCenterVertical",
	"AlignLeft",
	"AlignLeftSimple",
	"AlignRight",
	"AlignRightSimple",
	"AlignTop",
	"AlignTopSimple",
	"AmazonLogo",
	"Ambulance",
	"Anchor",
	"AnchorSimple",
	"AndroidLogo",
	"Angle",
	"AngularLogo",
	"Aperture",
	"AppStoreLogo",
	"AppWindow",
	"AppleLogo",
	"ApplePodcastsLogo",
	"ApproximateEquals",
	"Archive",
	"ArchiveBox",
	"ArchiveTray",
	"Armchair",
	"ArrowArcLeft",
	"ArrowArcRight",
	"ArrowBendDownLeft",
	"ArrowBendDownRight",
	"ArrowBendLeftDown",
	"ArrowBendLeftUp",
	"ArrowBendRightDown",
	"ArrowBendRightUp",
	"ArrowBendUpLeft",
	"ArrowBendUpRight",
	"ArrowCircleDown",
	"ArrowCircleDownLeft",
	"ArrowCircleDownRight",
	"ArrowCircleLeft",
	"ArrowCircleRight",
	"ArrowCircleUp",
	"ArrowCircleUpLeft",
	"ArrowCircleUpRight",
	"ArrowClockwise",
	"ArrowDown",
	"ArrowDownLeft",
	"ArrowDownRight",
	"ArrowElbowDownLeft",
	"ArrowElbowDownRight",
	"ArrowElbowLeft",
	"ArrowElbowLeftDown",
	"ArrowElbowLeftUp",
	"ArrowElbowRight",
	"ArrowElbowRightDown",
	"ArrowElbowRightUp",
	"ArrowElbowUpLeft",
	"ArrowElbowUpRight",
	"ArrowFatDown",
	"ArrowFatLeft",
	"ArrowFatLineDown",
	"ArrowFatLineLeft",
	"ArrowFatLineRight",
	"ArrowFatLineUp",
	"ArrowFatLinesDown",
	"ArrowFatLinesLeft",
	"ArrowFatLinesRight",
	"ArrowFatLinesUp",
	"ArrowFatRight",
	"ArrowFatUp",
	"ArrowLeft",
	"ArrowLineDown",
	"ArrowLineDownLeft",
	"ArrowLineDownRight",
	"ArrowLineLeft",
	"ArrowLineRight",
	"ArrowLineUp",
	"ArrowLineUpLeft",
	"ArrowLineUpRight",
	"ArrowRight",
	"ArrowSquareDown",
	"ArrowSquareDownLeft",
	"ArrowSquareDownRight",
	"ArrowSquareIn",
	"ArrowSquareLeft",
	"ArrowSquareOut",
	"ArrowSquareRight",
	"ArrowSquareUp",
	"ArrowSquareUpLeft",
	"ArrowSquareUpRight",
	"ArrowUDownLeft",
	"ArrowUDownRight",
	"ArrowULeftDown",
	"ArrowULeftUp",
	"ArrowURightDown",
	"ArrowURightUp",
	"ArrowUUpLeft",
	"ArrowUUpRight",
	"ArrowUp",
	"ArrowUpLeft",
	"ArrowUpRight",
	"ArrowsClockwise",
	"ArrowsDownUp",
	"ArrowsHorizontal",
	"ArrowsIn",
	"ArrowsInCardinal",
	"ArrowsInLineVertical",
	"ArrowsInSimple",
	"ArrowsLeftRight",
	"ArrowsMerge",
	"ArrowsOut",
	"ArrowsOutCardinal",
	"ArrowsOutSimple",
	"ArrowsSplit",
	"ArrowsVertical",
	"Article",
	"ArticleMedium",
	"ArticleNyTimes",
	"Asclepius",
	"Asterisk",
	"AsteriskSimple",
	"At",
	"Atom",
	"Avocado",
	"Axe",
	"Baby",
	"BabyCarriage",
	"Backpack",
	"Backspace",
	"Bag",
	"BagSimple",
	"Balloon",
	"Bandaids",
	"Bank",
	"Barbell",
	"Barcode",
	"Barn",
	"Barricade",
	"Baseball",
	"BaseballCap",
	"BaseballHelmet",
	"Basket",
	"Basketball",
	"Bathtub",
	"BatteryCharging",
	"BatteryEmpty",
	"BatteryFull",
	"BatteryHigh",
	"BatteryLow",
	"BatteryMedium",
	"BatteryPlus",
	"BatteryPlusVertical",
	"BatteryVerticalEmpty",
	"BatteryVerticalFull",
	"BatteryVerticalHigh",
	"BatteryVerticalLow",
	"BatteryWarning",
	"BeachBall",
	"Beanie",
	"Bed",
	"BeerBottle",
	"BeerStein",
	"BehanceLogo",
	"Bell",
	"BellRinging",
	"BellSimple",
	"BellSimpleRinging",
	"BellSimpleSlash",
	"BellSimpleZ",
	"BellSlash",
	"BellZ",
	"Belt",
	"BezierCurve",
	"Bicycle",
	"Binary",
	"Binoculars",
	"Biohazard",
	"Bird",
	"Blueprint",
	"Bluetooth",
	"BluetoothConnected",
	"BluetoothSlash",
	"BluetoothX",
	"Boat",
	"Bomb",
	"Bone",
	"Book",
	"BookBookmark",
	"BookOpen",
	"BookOpenText",
	"BookOpenUser",
	"BookUser",
	"Bookmark",
	"BookmarkSimple",
	"Bookmarks",
	"BookmarksSimple",
	"Books",
	"Boot",
	"Boules",
	"BoundingBox",
	"BowlFood",
	"BowlSteam",
	"BowlingBall",
	"BoxArrowDown",
	"BoxArrowUp",
	"BoxingGlove",
	"BracketsAngle",
	"BracketsCurly",
	"BracketsRound",
	"BracketsSquare",
	"Brain",
	"Brandy",
	"Bread",
	"Bridge",
	"Briefcase",
	"BriefcaseMetal",
	"Broadcast",
	"Broom",
	"Browser",
	"Browsers",
	"Bug",
	"BugBeetle",
	"BugDroid",
	"Building",
	"BuildingApartment",
	"BuildingOffice",
	"Buildings",
	"Bulldozer",
	"Bus",
	"Butterfly",
	"CableCar",
	"Cactus",
	"Cake",
	"Calculator",
	"Calendar",
	"CalendarBlank",
	"CalendarCheck",
	"CalendarDot",
	"CalendarDots",
	"CalendarHeart",
	"CalendarMinus",
	"CalendarPlus",
	"CalendarSlash",
	"CalendarStar",
	"CalendarX",
	"CallBell",
	"Camera",
	"CameraPlus",
	"CameraRotate",
	"CameraSlash",
	"Campfire",
	"Car",
	"CarBattery",
	"CarProfile",
	"CarSimple",
	"Cardholder",
	"Cards",
	"CardsThree",
	"CaretCircleDoubleUp",
	"CaretCircleDown",
	"CaretCircleLeft",
	"CaretCircleRight",
	"CaretCircleUp",
	"CaretCircleUpDown",
	"CaretDoubleDown",
	"CaretDoubleLeft",
	"CaretDoubleRight",
	"CaretDoubleUp",
	"CaretDown",
	"CaretLeft",
	"CaretLineDown",
	"CaretLineLeft",
	"CaretLineRight",
	"CaretLineUp",
	"CaretRight",
	"CaretUp",
	"CaretUpDown",
	"Carrot",
	"CashRegister",
	"CassetteTape",
	"CastleTurret",
	"Cat",
	"CellSignalFull",
	"CellSignalHigh",
	"CellSignalLow",
	"CellSignalMedium",
	"CellSignalNone",
	"CellSignalSlash",
	"CellSignalX",
	"CellTower",
	"Certificate",
	"Chair",
	"Chalkboard",
	"ChalkboardSimple",
	"ChalkboardTeacher",
	"Champagne",
	"ChargingStation",
	"ChartBar",
	"ChartBarHorizontal",
	"ChartDonut",
	"ChartLine",
	"ChartLineDown",
	"ChartLineUp",
	"ChartPie",
	"ChartPieSlice",
	"ChartPolar",
	"ChartScatter",
	"Chat",
	"ChatCentered",
	"ChatCenteredDots",
	"ChatCenteredSlash",
	"ChatCenteredText",
	"ChatCircle",
	"ChatCircleDots",
	"ChatCircleSlash",
	"ChatCircleText",
	"ChatDots",
	"ChatSlash",
	"ChatTeardrop",
	"ChatTeardropDots",
	"ChatTeardropSlash",
	"ChatTeardropText",
	"ChatText",
	"Chats",
	"ChatsCircle",
	"ChatsTeardrop",
	"Check",
	"CheckCircle",
	"CheckFat",
	"CheckSquare",
	"CheckSquareOffset",
	"Checkerboard",
	"Checks",
	"Cheers",
	"Cheese",
	"ChefHat",
	"Cherries",
	"Church",
	"Cigarette",
	"CigaretteSlash",
	"Circle",
	"CircleDashed",
	"CircleHalf",
	"CircleHalfTilt",
	"CircleNotch",
	"CirclesFour",
	"CirclesThree",
	"CirclesThreePlus",
	"Circuitry",
	"City",
	"Clipboard",
	"ClipboardText",
	"Clock",
	"ClockAfternoon",
	"ClockClockwise",
	"ClockCountdown",
	"ClockUser",
	"ClosedCaptioning",
	"Cloud",
	"CloudArrowDown",
	"CloudArrowUp",
	"CloudCheck",
	"CloudFog",
	"CloudLightning",
	"CloudMoon",
	"CloudRain",
	"CloudSlash",
	"CloudSnow",
	"CloudSun",
	"CloudWarning",
	"CloudX",
	"Clover",
	"Club",
	"CoatHanger",
	"CodaLogo",
	"Code",
	"CodeBlock",
	"CodeSimple",
	"CodepenLogo",
	"CodesandboxLogo",
	"Coffee",
	"CoffeeBean",
	"Coin",
	"CoinVertical",
	"Coins",
	"Columns",
	"ColumnsPlusLeft",
	"ColumnsPlusRight",
	"Command",
	"Compass",
	"CompassRose",
	"CompassTool",
	"ComputerTower",
	"Confetti",
	"ContactlessPayment",
	"Control",
	"Cookie",
	"CookingPot",
	"Copy",
	"CopySimple",
	"Copyleft",
	"Copyright",
	"CornersIn",
	"CornersOut",
	"Couch",
	"CourtBasketball",
	"Cow",
	"CowboyHat",
	"Cpu",
	"Crane",
	"CraneTower",
	"CreditCard",
	"Cricket",
	"Crop",
	"Cross",
	"Crosshair",
	"CrosshairSimple",
	"Crown",
	"CrownCross",
	"CrownSimple",
	"Cube",
	"CubeFocus",
	"CubeTransparent",
	"CurrencyBtc",
	"CurrencyCircleDollar",
	"CurrencyCny",
	"CurrencyDollar",
	"CurrencyDollarSimple",
	"CurrencyEth",
	"CurrencyEur",
	"CurrencyGbp",
	"CurrencyInr",
	"CurrencyJpy",
	"CurrencyKrw",
	"CurrencyKzt",
	"CurrencyNgn",
	"CurrencyRub",
	"Cursor",
	"CursorClick",
	"CursorText",
	"Cylinder",
	"Database",
	"Desk",
	"Desktop",
	"DesktopTower",
	"Detective",
	"DevToLogo",
	"DeviceMobile",
	"DeviceMobileCamera",
	"DeviceMobileSlash",
	"DeviceMobileSpeaker",
	"DeviceRotate",
	"DeviceTablet",
	"DeviceTabletCamera",
	"DeviceTabletSpeaker",
	"Devices",
	"Diamond",
	"DiamondsFour",
	"DiceFive",
	"DiceFour",
	"DiceOne",
	"DiceSix",
	"DiceThree",
	"DiceTwo",
	"Disc",
	"DiscoBall",
	"DiscordLogo",
	"Divide",
	"Dna",
	"Dog",
	"Door",
	"DoorOpen",
	"Dot",
	"DotOutline",
	"DotsNine",
	"DotsSix",
	"DotsSixVertical",
	"DotsThree",
	"DotsThreeCircle",
	"DotsThreeOutline",
	"DotsThreeVertical",
	"Download",
	"DownloadSimple",
	"Dress",
	"Dresser",
	"DribbbleLogo",
	"Drone",
	"Drop",
	"DropHalf",
	"DropHalfBottom",
	"DropSimple",
	"DropSlash",
	"DropboxLogo",
	"Ear",
	"EarSlash",
	"Egg",
	"EggCrack",
	"Eject",
	"EjectSimple",
	"Elevator",
	"Empty",
	"Engine",
	"Envelope",
	"EnvelopeOpen",
	"EnvelopeSimple",
	"EnvelopeSimpleOpen",
	"Equalizer",
	"Equals",
	"Eraser",
	"EscalatorDown",
	"EscalatorUp",
	"Exam",
	"ExclamationMark",
	"Exclude",
	"ExcludeSquare",
	"Export",
	"Eye",
	"EyeClosed",
	"EyeSlash",
	"Eyedropper",
	"EyedropperSample",
	"Eyeglasses",
	"Eyes",
	"FaceMask",
	"FacebookLogo",
	"Factory",
	"Faders",
	"FadersHorizontal",
	"FalloutShelter",
	"Fan",
	"Farm",
	"FastForward",
	"FastForwardCircle",
	"Feather",
	"FediverseLogo",
	"FigmaLogo",
	"File",
	"FileArchive",
	"FileArrowDown",
	"FileArrowUp",
	"FileAudio",
	"FileC",
	"FileCloud",
	"FileCode",
	"FileCpp",
	"FileCss",
	"FileCsv",
	"FileDashed",
	"FileDoc",
	"FileHtml",
	"FileImage",
	"FileIni",
	"FileJpg",
	"FileJs",
	"FileJsx",
	"FileLock",
	"FileMagnifyingGlass",
	"FileMd",
	"FileMinus",
	"FilePdf",
	"FilePlus",
	"FilePng",
	"FilePpt",
	"FilePy",
	"FileRs",
	"FileSql",
	"FileSvg",
	"FileText",
	"FileTs",
	"FileTsx",
	"FileTxt",
	"FileVideo",
	"FileVue",
	"FileX",
	"FileXls",
	"FileZip",
	"Files",
	"FilmReel",
	"FilmScript",
	"FilmSlate",
	"FilmStrip",
	"Fingerprint",
	"FingerprintSimple",
	"FinnTheHuman",
	"Fire",
	"FireExtinguisher",
	"FireSimple",
	"FireTruck",
	"FirstAid",
	"FirstAidKit",
	"Fish",
	"FishSimple",
	"Flag",
	"FlagBanner",
	"FlagBannerFold",
	"FlagCheckered",
	"FlagPennant",
	"Flame",
	"Flashlight",
	"Flask",
	"FlipHorizontal",
	"FlipVertical",
	"FloppyDisk",
	"FloppyDiskBack",
	"FlowArrow",
	"Flower",
	"FlowerLotus",
	"FlowerTulip",
	"FlyingSaucer",
	"Folder",
	"FolderDashed",
	"FolderLock",
	"FolderMinus",
	"FolderNotch",
	"FolderNotchMinus",
	"FolderNotchOpen",
	"FolderNotchPlus",
	"FolderOpen",
	"FolderPlus",
	"FolderSimple",
	"FolderSimpleDashed",
	"FolderSimpleLock",
	"FolderSimpleMinus",
	"FolderSimplePlus",
	"FolderSimpleStar",
	"FolderSimpleUser",
	"FolderStar",
	"FolderUser",
	"Folders",
	"Football",
	"FootballHelmet",
	"Footprints",
	"ForkKnife",
	"FourK",
	"FrameCorners",
	"FramerLogo",
	"Function",
	"Funnel",
	"FunnelSimple",
	"FunnelSimpleX",
	"FunnelX",
	"GameController",
	"Garage",
	"GasCan",
	"GasPump",
	"Gauge",
	"Gavel",
	"Gear",
	"GearFine",
	"GearSix",
	"GenderFemale",
	"GenderIntersex",
	"GenderMale",
	"GenderNeuter",
	"GenderNonbinary",
	"GenderTransgender",
	"Ghost",
	"Gif",
	"Gift",
	"GitBranch",
	"GitCommit",
	"GitDiff",
	"GitFork",
	"GitMerge",
	"GitPullRequest",
	"GithubLogo",
	"GitlabLogo",
	"GitlabLogoSimple",
	"Globe",
	"GlobeHemisphereEast",
	"GlobeHemisphereWest",
	"GlobeSimple",
	"GlobeSimpleX",
	"GlobeStand",
	"GlobeX",
	"Goggles",
	"Golf",
	"GoodreadsLogo",
	"GoogleCardboardLogo",
	"GoogleChromeLogo",
	"GoogleDriveLogo",
	"GoogleLogo",
	"GooglePhotosLogo",
	"GooglePlayLogo",
	"GooglePodcastsLogo",
	"Gps",
	"GpsFix",
	"GpsSlash",
	"Gradient",
	"GraduationCap",
	"Grains",
	"GrainsSlash",
	"Graph",
	"GraphicsCard",
	"GreaterThan",
	"GreaterThanOrEqual",
	"GridFour",
	"GridNine",
	"Guitar",
	"HairDryer",
	"Hamburger",
	"Hammer",
	"Hand",
	"HandArrowDown",
	"HandArrowUp",
	"HandCoins",
	"HandDeposit",
	"HandEye",
	"HandFist",
	"HandGrabbing",
	"HandHeart",
	"HandPalm",
	"HandPeace",
	"HandPointing",
	"HandSoap",
	"HandSwipeLeft",
	"HandSwipeRight",
	"HandTap",
	"HandWaving",
	"HandWithdraw",
	"Handbag",
	"HandbagSimple",
	"HandsClapping",
	"HandsPraying",
	"Handshake",
	"HardDrive",
	"HardDrives",
	"HardHat",
	"Hash",
	"HashStraight",
	"HeadCircuit",
	"Headlights",
	"Headphones",
	"Headset",
	"Heart",
	"HeartBreak",
	"HeartHalf",
	"HeartStraight",
	"HeartStraightBreak",
	"Heartbeat",
	"Hexagon",
	"HighDefinition",
	"HighHeel",
	"Highlighter",
	"HighlighterCircle",
	"Hockey",
	"Hoodie",
	"Horse",
	"Hospital",
	"Hourglass",
	"HourglassHigh",
	"HourglassLow",
	"HourglassMedium",
	"HourglassSimple",
	"HourglassSimpleHigh",
	"HourglassSimpleLow",
	"House",
	"HouseLine",
	"HouseSimple",
	"Hurricane",
	"IceCream",
	"IdentificationBadge",
	"IdentificationCard",
	"Image",
	"ImageBroken",
	"ImageSquare",
	"Images",
	"ImagesSquare",
	"Infinity",
	"Info",
	"InstagramLogo",
	"Intersect",
	"IntersectSquare",
	"IntersectThree",
	"Intersection",
	"Invoice",
	"Island",
	"Jar",
	"JarLabel",
	"Jeep",
	"Joystick",
	"Kanban",
	"Key",
	"KeyReturn",
	"Keyboard",
	"Keyhole",
	"Knife",
	"Ladder",
	"LadderSimple",
	"Lamp",
	"LampPendant",
	"Laptop",
	"Lasso",
	"LastfmLogo",
	"Layout",
	"Leaf",
	"Lectern",
	"Lego",
	"LegoSmiley",
	"LessThan",
	"LessThanOrEqual",
	"LetterCircleH",
	"LetterCircleP",
	"LetterCircleV",
	"Lifebuoy",
	"Lightbulb",
	"LightbulbFilament",
	"Lighthouse",
	"Lightning",
	"LightningA",
	"LightningSlash",
	"LineSegment",
	"LineSegments",
	"LineVertical",
	"Link",
	"LinkBreak",
	"LinkSimple",
	"LinkSimpleBreak",
	"LinkSimpleHorizontal",
	"LinkedinLogo",
	"LinktreeLogo",
	"LinuxLogo",
	"List",
	"ListBullets",
	"ListChecks",
	"ListDashes",
	"ListHeart",
	"ListMagnifyingGlass",
	"ListNumbers",
	"ListPlus",
	"ListStar",
	"Lock",
	"LockKey",
	"LockKeyOpen",
	"LockLaminated",
	"LockLaminatedOpen",
	"LockOpen",
	"LockSimple",
	"LockSimpleOpen",
	"Lockers",
	"Log",
	"MagicWand",
	"Magnet",
	"MagnetStraight",
	"MagnifyingGlass",
	"MagnifyingGlassMinus",
	"MagnifyingGlassPlus",
	"Mailbox",
	"MapPin",
	"MapPinArea",
	"MapPinLine",
	"MapPinPlus",
	"MapPinSimple",
	"MapPinSimpleArea",
	"MapPinSimpleLine",
	"MapTrifold",
	"MarkdownLogo",
	"MarkerCircle",
	"Martini",
	"MaskHappy",
	"MaskSad",
	"MastodonLogo",
	"MathOperations",
	"MatrixLogo",
	"Medal",
	"MedalMilitary",
	"MediumLogo",
	"Megaphone",
	"MegaphoneSimple",
	"MemberOf",
	"Memory",
	"MessengerLogo",
	"MetaLogo",
	"Meteor",
	"Metronome",
	"Microphone",
	"MicrophoneSlash",
	"MicrophoneStage",
	"Microscope",
	"MicrosoftExcelLogo",
	"MicrosoftOutlookLogo",
	"MicrosoftTeamsLogo",
	"MicrosoftWordLogo",
	"Minus",
	"MinusCircle",
	"MinusSquare",
	"Money",
	"MoneyWavy",
	"Monitor",
	"MonitorArrowUp",
	"MonitorPlay",
	"Moon",
	"MoonStars",
	"Moped",
	"MopedFront",
	"Mosque",
	"Motorcycle",
	"Mountains",
	"Mouse",
	"MouseLeftClick",
	"MouseMiddleClick",
	"MouseRightClick",
	"MouseScroll",
	"MouseSimple",
	"MusicNote",
	"MusicNoteSimple",
	"MusicNotes",
	"MusicNotesMinus",
	"MusicNotesPlus",
	"MusicNotesSimple",
	"NavigationArrow",
	"Needle",
	"Network",
	"NetworkSlash",
	"NetworkX",
	"Newspaper",
	"NewspaperClipping",
	"NotEquals",
	"NotMemberOf",
	"NotSubsetOf",
	"NotSupersetOf",
	"Notches",
	"Note",
	"NoteBlank",
	"NotePencil",
	"Notebook",
	"Notepad",
	"Notification",
	"NotionLogo",
	"NuclearPlant",
	"NumberCircleEight",
	"NumberCircleFive",
	"NumberCircleFour",
	"NumberCircleNine",
	"NumberCircleOne",
	"NumberCircleSeven",
	"NumberCircleSix",
	"NumberCircleThree",
	"NumberCircleTwo",
	"NumberCircleZero",
	"NumberEight",
	"NumberFive",
	"NumberFour",
	"NumberNine",
	"NumberOne",
	"NumberSeven",
	"NumberSix",
	"NumberSquareEight",
	"NumberSquareFive",
	"NumberSquareFour",
	"NumberSquareNine",
	"NumberSquareOne",
	"NumberSquareSeven",
	"NumberSquareSix",
	"NumberSquareThree",
	"NumberSquareTwo",
	"NumberSquareZero",
	"NumberThree",
	"NumberTwo",
	"NumberZero",
	"Numpad",
	"Nut",
	"NyTimesLogo",
	"Octagon",
	"OfficeChair",
	"Onigiri",
	"OpenAiLogo",
	"Option",
	"Orange",
	"OrangeSlice",
	"Oven",
	"Package",
	"PaintBrush",
	"PaintBrushBroad",
	"PaintBrushHousehold",
	"PaintBucket",
	"PaintRoller",
	"Palette",
	"Panorama",
	"Pants",
	"PaperPlane",
	"PaperPlaneRight",
	"PaperPlaneTilt",
	"Paperclip",
	"PaperclipHorizontal",
	"Parachute",
	"Paragraph",
	"Parallelogram",
	"Park",
	"Password",
	"Path",
	"PatreonLogo",
	"Pause",
	"PauseCircle",
	"PawPrint",
	"PaypalLogo",
	"Peace",
	"Pen",
	"PenNib",
	"PenNibStraight",
	"Pencil",
	"PencilCircle",
	"PencilLine",
	"PencilRuler",
	"PencilSimple",
	"PencilSimpleLine",
	"PencilSimpleSlash",
	"PencilSlash",
	"Pentagon",
	"Pentagram",
	"Pepper",
	"Percent",
	"Person",
	"PersonArmsSpread",
	"PersonSimple",
	"PersonSimpleBike",
	"PersonSimpleCircle",
	"PersonSimpleHike",
	"PersonSimpleRun",
	"PersonSimpleSki",
	"PersonSimpleSwim",
	"PersonSimpleTaiChi",
	"PersonSimpleThrow",
	"PersonSimpleWalk",
	"Perspective",
	"Phone",
	"PhoneCall",
	"PhoneDisconnect",
	"PhoneIncoming",
	"PhoneList",
	"PhoneOutgoing",
	"PhonePause",
	"PhonePlus",
	"PhoneSlash",
	"PhoneTransfer",
	"PhoneX",
	"PhosphorLogo",
	"Pi",
	"PianoKeys",
	"PicnicTable",
	"PictureInPicture",
	"PiggyBank",
	"Pill",
	"PingPong",
	"PintGlass",
	"PinterestLogo",
	"Pinwheel",
	"Pipe",
	"PipeWrench",
	"PixLogo",
	"Pizza",
	"Placeholder",
	"Planet",
	"Plant",
	"Play",
	"PlayCircle",
	"PlayPause",
	"Playlist",
	"Plug",
	"PlugCharging",
	"Plugs",
	"PlugsConnected",
	"Plus",
	"PlusCircle",
	"PlusMinus",
	"PlusSquare",
	"PokerChip",
	"PoliceCar",
	"Polygon",
	"Popcorn",
	"Popsicle",
	"PottedPlant",
	"Power",
	"Prescription",
	"Presentation",
	"PresentationChart",
	"Printer",
	"Prohibit",
	"ProhibitInset",
	"ProjectorScreen",
	"ProjectorScreenChart",
	"Pulse",
	"PushPin",
	"PushPinSimple",
	"PushPinSimpleSlash",
	"PushPinSlash",
	"PuzzlePiece",
	"QrCode",
	"Question",
	"QuestionMark",
	"Queue",
	"Quotes",
	"Rabbit",
	"Racquet",
	"Radical",
	"Radio",
	"RadioButton",
	"Radioactive",
	"Rainbow",
	"RainbowCloud",
	"Ranking",
	"ReadCvLogo",
	"Receipt",
	"ReceiptX",
	"Record",
	"Rectangle",
	"RectangleDashed",
	"Recycle",
	"RedditLogo",
	"Repeat",
	"RepeatOnce",
	"ReplitLogo",
	"Resize",
	"Rewind",
	"RewindCircle",
	"RoadHorizon",
	"Robot",
	"Rocket",
	"RocketLaunch",
	"Rows",
	"RowsPlusBottom",
	"RowsPlusTop",
	"Rss",
	"RssSimple",
	"Rug",
	"Ruler",
	"Sailboat",
	"Scales",
	"Scan",
	"ScanSmiley",
	"Scissors",
	"Scooter",
	"Screencast",
	"Screwdriver",
	"Scribble",
	"ScribbleLoop",
	"Scroll",
	"Seal",
	"SealCheck",
	"SealPercent",
	"SealQuestion",
	"SealWarning",
	"Seat",
	"Seatbelt",
	"SecurityCamera",
	"Selection",
	"SelectionAll",
	"SelectionBackground",
	"SelectionForeground",
	"SelectionInverse",
	"SelectionPlus",
	"SelectionSlash",
	"Shapes",
	"Share",
	"ShareFat",
	"ShareNetwork",
	"Shield",
	"ShieldCheck",
	"ShieldCheckered",
	"ShieldChevron",
	"ShieldPlus",
	"ShieldSlash",
	"ShieldStar",
	"ShieldWarning",
	"ShippingContainer",
	"ShirtFolded",
	"ShootingStar",
	"ShoppingBag",
	"ShoppingBagOpen",
	"ShoppingCart",
	"ShoppingCartSimple",
	"Shovel",
	"Shower",
	"Shrimp",
	"Shuffle",
	"ShuffleAngular",
	"ShuffleSimple",
	"Sidebar",
	"SidebarSimple",
	"Sigma",
	"SignIn",
	"SignOut",
	"Signature",
	"Signpost",
	"SimCard",
	"Siren",
	"SketchLogo",
	"SkipBack",
	"SkipBackCircle",
	"SkipForward",
	"SkipForwardCircle",
	"Skull",
	"SkypeLogo",
	"SlackLogo",
	"Sliders",
	"SlidersHorizontal",
	"Slideshow",
	"Smiley",
	"SmileyAngry",
	"SmileyBlank",
	"SmileyMeh",
	"SmileyMelting",
	"SmileyNervous",
	"SmileySad",
	"SmileySticker",
	"SmileyWink",
	"SmileyXEyes",
	"SnapchatLogo",
	"Sneaker",
	"SneakerMove",
	"Snowflake",
	"SoccerBall",
	"Sock",
	"SolarPanel",
	"SolarRoof",
	"SortAscending",
	"SortDescending",
	"SoundcloudLogo",
	"Spade",
	"Sparkle",
	"SpeakerHifi",
	"SpeakerHigh",
	"SpeakerLow",
	"SpeakerNone",
	"SpeakerSimpleHigh",
	"SpeakerSimpleLow",
	"SpeakerSimpleNone",
	"SpeakerSimpleSlash",
	"SpeakerSimpleX",
	"SpeakerSlash",
	"SpeakerX",
	"Speedometer",
	"Sphere",
	"Spinner",
	"SpinnerBall",
	"SpinnerGap",
	"Spiral",
	"SplitHorizontal",
	"SplitVertical",
	"SpotifyLogo",
	"SprayBottle",
	"Square",
	"SquareHalf",
	"SquareHalfBottom",
	"SquareLogo",
	"SquareSplitVertical",
	"SquaresFour",
	"Stack",
	"StackMinus",
	"StackOverflowLogo",
	"StackPlus",
	"StackSimple",
	"Stairs",
	"Stamp",
	"StandardDefinition",
	"Star",
	"StarAndCrescent",
	"StarFour",
	"StarHalf",
	"StarOfDavid",
	"SteamLogo",
	"SteeringWheel",
	"Steps",
	"Stethoscope",
	"Sticker",
	"Stool",
	"Stop",
	"StopCircle",
	"Storefront",
	"Strategy",
	"StripeLogo",
	"Student",
	"SubsetOf",
	"SubsetProperOf",
	"Subtitles",
	"SubtitlesSlash",
	"Subtract",
	"SubtractSquare",
	"Subway",
	"Suitcase",
	"SuitcaseRolling",
	"SuitcaseSimple",
	"Sun",
	"SunDim",
	"SunHorizon",
	"Sunglasses",
	"SupersetOf",
	"SupersetProperOf",
	"Swap",
	"Swatches",
	"SwimmingPool",
	"Sword",
	"Synagogue",
	"Syringe",
	"TShirt",
	"Table",
	"Tabs",
	"Tag",
	"TagChevron",
	"TagSimple",
	"Target",
	"Taxi",
	"TeaBag",
	"TelegramLogo",
	"Television",
	"TelevisionSimple",
	"TennisBall",
	"Tent",
	"Terminal",
	"TerminalWindow",
	"TestTube",
	"TextAUnderline",
	"TextAa",
	"TextAlignCenter",
	"TextAlignJustify",
	"TextAlignLeft",
	"TextAlignRight",
	"TextB",
	"TextColumns",
	"TextH",
	"TextHFive",
	"TextHFour",
	"TextHOne",
	"TextHSix",
	"TextHThree",
	"TextHTwo",
	"TextIndent",
	"TextItalic",
	"TextOutdent",
	"TextStrikethrough",
	"TextSubscript",
	"TextSuperscript",
	"TextT",
	"TextTSlash",
	"TextUnderline",
	"Textbox",
	"Thermometer",
	"ThermometerCold",
	"ThermometerHot",
	"ThermometerSimple",
	"ThreadsLogo",
	"ThreeD",
	"ThumbsDown",
	"ThumbsUp",
	"Ticket",
	"TidalLogo",
	"TiktokLogo",
	"Tilde",
	"Timer",
	"TipJar",
	"Tipi",
	"Tire",
	"ToggleLeft",
	"ToggleRight",
	"Toilet",
	"ToiletPaper",
	"Toolbox",
	"Tooth",
	"Tornado",
	"Tote",
	"ToteSimple",
	"Towel",
	"Tractor",
	"Trademark",
	"TrademarkRegistered",
	"TrafficCone",
	"TrafficSign",
	"TrafficSignal",
	"Train",
	"TrainRegional",
	"TrainSimple",
	"Tram",
	"Translate",
	"Trash",
	"TrashSimple",
	"Tray",
	"TrayArrowDown",
	"TrayArrowUp",
	"TreasureChest",
	"Tree",
	"TreeEvergreen",
	"TreePalm",
	"TreeStructure",
	"TreeView",
	"TrendDown",
	"TrendUp",
	"Triangle",
	"TriangleDashed",
	"Trolley",
	"TrolleySuitcase",
	"Trophy",
	"Truck",
	"TruckTrailer",
	"TumblrLogo",
	"TwitchLogo",
	"TwitterLogo",
	"Umbrella",
	"UmbrellaSimple",
	"Union",
	"Unite",
	"UniteSquare",
	"Upload",
	"UploadSimple",
	"Usb",
	"User",
	"UserCheck",
	"UserCircle",
	"UserCircleCheck",
	"UserCircleDashed",
	"UserCircleGear",
	"UserCircleMinus",
	"UserCirclePlus",
	"UserFocus",
	"UserGear",
	"UserList",
	"UserMinus",
	"UserPlus",
	"UserRectangle",
	"UserSound",
	"UserSquare",
	"UserSwitch",
	"Users",
	"UsersFour",
	"UsersThree",
	"Van",
	"Vault",
	"VectorThree",
	"VectorTwo",
	"Vibrate",
	"Video",
	"VideoCamera",
	"VideoCameraSlash",
	"VideoConference",
	"Vignette",
	"VinylRecord",
	"VirtualReality",
	"Virus",
	"Visor",
	"Voicemail",
	"Volleyball",
	"Wall",
	"Wallet",
	"Warehouse",
	"Warning",
	"WarningCircle",
	"WarningDiamond",
	"WarningOctagon",
	"WashingMachine",
	"Watch",
	"WaveSawtooth",
	"WaveSine",
	"WaveSquare",
	"WaveTriangle",
	"Waveform",
	"WaveformSlash",
	"Waves",
	"Webcam",
	"WebcamSlash",
	"WebhooksLogo",
	"WechatLogo",
	"WhatsappLogo",
	"Wheelchair",
	"WheelchairMotion",
	"WifiHigh",
	"WifiLow",
	"WifiMedium",
	"WifiNone",
	"WifiSlash",
	"WifiX",
	"Wind",
	"Windmill",
	"WindowsLogo",
	"Wine",
	"Wrench",
	"X",
	"XCircle",
	"XLogo",
	"XSquare",
	"Yarn",
	"YinYang",
	"YoutubeLogo",
];
var moduleBaseUrl = "https://framer.com/m/phosphor-icons/";
var weightOptions = ["thin", "light", "regular", "bold", "fill", "duotone"];
var lowercaseIconKeyPairs = iconKeys.reduce((res, key) => {
	res[key.toLowerCase()] = key;
	return res;
}, {});
function Icon2(props) {
	const {
		color,
		selectByList,
		iconSearch,
		iconSelection,
		onClick,
		onMouseDown,
		onMouseUp,
		onMouseEnter,
		onMouseLeave,
		weight,
		mirrored,
	} = props;
	const isMounted = useRef(false);
	const iconKey = useIconSelection(
		iconKeys,
		selectByList,
		iconSearch,
		iconSelection,
		lowercaseIconKeyPairs,
	);
	const [SelectedIcon, setSelectedIcon] = useState(
		iconKey === "Home" ? House_default(React2) : null,
	);
	async function importModule() {
		try {
			const version = "0.0.57";
			const iconModuleUrl = `${moduleBaseUrl}${iconKey}.js@${version}`;
			const module = await import(
				/* webpackIgnore: true */
				/* @vite-ignore */
				iconModuleUrl
			);
			if (isMounted.current) setSelectedIcon(module.default(React2));
		} catch (err) {
			if (isMounted.current) setSelectedIcon(null);
		}
	}
	useEffect(() => {
		isMounted.current = true;
		importModule();
		return () => {
			isMounted.current = false;
		};
	}, [iconKey]);
	const isOnCanvas = RenderTarget.current() === RenderTarget.canvas;
	const emptyState = isOnCanvas ? <NullState /> : null;
	return (
		<motion.div
			style={{
				display: "contents",
			}}
			onClick={onClick}
			onMouseEnter={onMouseEnter}
			onMouseLeave={onMouseLeave}
			onMouseDown={onMouseDown}
			onMouseUp={onMouseUp}
		>
			{SelectedIcon ? (
				<svg
					xmlns={"http://www.w3.org/2000/svg"}
					viewBox={"0 0 256 256"}
					style={{
						userSelect: "none",
						width: "100%",
						height: "100%",
						display: "inline-block",
						fill: color,
						color,
						flexShrink: 0,
						transform: mirrored ? "scale(-1, 1)" : void 0,
					}}
					focusable={"false"}
					color={color}
				>
					<SelectedIcon color={color} weight={weight} />
				</svg>
			) : (
				emptyState
			)}
		</motion.div>
	);
}
Icon2.displayName = "Phosphor";
Icon2.defaultProps = {
	width: 24,
	height: 24,
	iconSelection: "House",
	iconSearch: "House",
	color: "#66F",
	selectByList: true,
	weight: "regular",
	mirrored: false,
};
addPropertyControls(Icon2, {
	selectByList: {
		type: ControlType2.Boolean,
		title: "Select",
		enabledTitle: "List",
		disabledTitle: "Search",
		defaultValue: Icon2.defaultProps.selectByList,
	},
	iconSelection: {
		type: ControlType2.Enum,
		options: iconKeys,
		defaultValue: Icon2.defaultProps.iconSelection,
		title: "Name",
		hidden: ({ selectByList }) => !selectByList,
		description:
			"Find every icon name on the [Phosphor site](https://phosphoricons.com/)",
	},
	iconSearch: {
		type: ControlType2.String,
		title: "Name",
		placeholder: "Menu, Wifi, Box\u2026",
		hidden: ({ selectByList }) => selectByList,
	},
	color: {
		type: ControlType2.Color,
		title: "Color",
		defaultValue: Icon2.defaultProps.color,
	},
	weight: {
		type: ControlType2.Enum,
		title: "Weight",
		optionTitles: weightOptions.map(
			(piece) => piece.charAt(0).toUpperCase() + piece.slice(1),
		),
		options: weightOptions,
		defaultValue: Icon2.defaultProps.weight,
	},
	mirrored: {
		type: ControlType2.Boolean,
		enabledTitle: "Yes",
		disabledTitle: "No",
		defaultValue: Icon2.defaultProps.mirrored,
	},
	...defaultEvents,
});

// /:https://framerusercontent.com/modules/nb3DEa4KlQzjYbQFqCXE/wDpIhRY0AS0gYMYA7RFL/hS1ai5DiN.js
var PhosphorFonts = getFonts(Icon2);
var MotionDivWithFX = withFX(motion2.div);
var enabledGestures = {
	kuybRR4_4: {
		hover: true,
	},
};
var cycleOrder = ["kuybRR4_4", "Gn0ymALys"];
var serializationHash = "framer-XvX2Q";
var variantClassNames = {
	Gn0ymALys: "framer-v-1gljl5s",
	kuybRR4_4: "framer-v-dano12",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.7,
	ease: [0.08, 0.78, 0.56, 1],
	type: "tween",
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var Overlay = ({
	children,
	blockDocumentScrolling,
	dismissWithEsc,
	enabled = true,
}) => {
	const [visible, setVisible] = useOverlayState({
		blockDocumentScrolling,
		dismissWithEsc: enabled && dismissWithEsc,
	});
	return children({
		hide: () => setVisible(false),
		show: () => setVisible(true),
		toggle: () => setVisible(!visible),
		visible: enabled && visible,
	});
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React3.Fragment);
var humanReadableVariantMap = {
	Desktop: "kuybRR4_4",
	Mobile: "Gn0ymALys",
};
var getProps = ({ height, icon, id, overview, title, width, ...props }) => {
	return {
		...props,
		g_945UDcK: icon ??
			props.g_945UDcK ?? {
				alt: "",
				pixelHeight: 125,
				pixelWidth: 125,
				src: "https://framerusercontent.com/images/kXEk5PthLueijJvPsw26V2PcWA.svg?width=125&height=125",
			},
		IHMAQA45k:
			overview ??
			props.IHMAQA45k ??
			"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa",
		mnsQP78No: title ?? props.mnsQP78No ?? "Cloud Infastructure",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "kuybRR4_4",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		mnsQP78No: mnsQP78No2,
		IHMAQA45k: IHMAQA45k2,
		g_945UDcK: g_945UDcK2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "kuybRR4_4",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseDown13elrgn = ({ overlay }) =>
		activeVariantCallback(async (...args) => {
			overlay.show();
		});
	const sharedStyleClassNames = [className, className2, className3];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React3.useRef(null);
	const ref2 = React3.useRef(null);
	const isDisplayed = () => {
		if (baseVariant === "Gn0ymALys") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={{
							webPageId: "EpXpYwtEx",
						}}
						motionChild={true}
						nodeId={"kuybRR4_4"}
						openInNewTab={false}
						scopeId={"hS1ai5DiN"}
					>
						<motion2.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-dano12", className4, classNames)} framer-1wii8no`}
							data-framer-name={"Desktop"}
							layoutDependency={layoutDependency}
							layoutId={"kuybRR4_4"}
							ref={refBinding}
							style={{
								backgroundColor:
									"var(--token-30cfaa59-8f06-49f8-83bf-9dce7a7f9364, rgb(233, 233, 233))",
								...style,
							}}
							{...addPropertyOverrides(
								{
									"kuybRR4_4-hover": {
										"data-framer-name": void 0,
									},
									Gn0ymALys: {
										"data-framer-name": "Mobile",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion2.div
								className={"framer-1hno8i6"}
								data-framer-name={"Button"}
								layoutDependency={layoutDependency}
								layoutId={"lscgGww1C"}
								style={{
									backgroundColor:
										"var(--token-4a657333-042a-4ee5-8ab0-89f8b6ae1452, rgb(218, 218, 218))",
									borderBottomLeftRadius: 18,
									borderBottomRightRadius: 18,
									borderTopLeftRadius: 18,
									borderTopRightRadius: 18,
								}}
							>
								<Overlay blockDocumentScrolling={false} dismissWithEsc={false}>
									{(overlay) => (
										<_Fragment>
											<ComponentViewportProvider>
												<SmartComponentScopedContainer
													className={"framer-c1q9gm-container"}
													id={`${layoutId}-c1q9gm`}
													isAuthoredByUser={true}
													isModuleExternal={true}
													layoutDependency={layoutDependency}
													layoutId={"MG24N_ke3-container"}
													nodeId={"MG24N_ke3"}
													ref={ref1}
													rendersWithMotion={true}
													scopeId={"hS1ai5DiN"}
													style={{
														rotate: 0,
													}}
													variants={{
														"kuybRR4_4-hover": {
															rotate: 180,
														},
													}}
												>
													<Icon2
														color={
															"var(--token-425d5885-8b67-4657-91de-de73d3d0dc86, rgb(0, 0, 0))"
														}
														height={"100%"}
														iconSearch={"House"}
														iconSelection={"Plus"}
														id={"MG24N_ke3"}
														layoutId={"MG24N_ke3"}
														mirrored={false}
														onMouseDown={onMouseDown13elrgn({
															overlay,
														})}
														selectByList={true}
														style={{
															height: "100%",
															width: "100%",
														}}
														weight={"regular"}
														width={"100%"}
													/>
													<AnimatePresence>
														{overlay.visible && (
															<Floating
																alignment={"center"}
																anchorRef={ref1}
																className={cx(scopingClassNames, classNames)}
																collisionDetection={true}
																collisionDetectionPadding={20}
																data-framer-portal-id={`${layoutId}-c1q9gm`}
																offsetX={0}
																offsetY={10}
																onDismiss={overlay.hide}
																placement={"bottom"}
																safeArea={true}
																zIndex={11}
															>
																<MotionDivWithFX
																	__perspectiveFX={false}
																	__smartComponentFX={true}
																	__targetOpacity={1}
																	animate={animation1}
																	className={"framer-oesd8s"}
																	exit={animation}
																	initial={animation2}
																	layoutDependency={layoutDependency}
																	layoutId={"tOgHhsuZ4"}
																	ref={ref2}
																	role={"dialog"}
																	style={{
																		backgroundColor: "rgb(255, 255, 255)",
																		borderBottomLeftRadius: 10,
																		borderBottomRightRadius: 10,
																		borderTopLeftRadius: 10,
																		borderTopRightRadius: 10,
																		boxShadow:
																			"0px 10px 20px 0px rgba(0, 0, 0, 0.05)",
																	}}
																/>
															</Floating>
														)}
													</AnimatePresence>
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										</_Fragment>
									)}
								</Overlay>
							</motion2.div>
							<motion2.div
								className={"framer-oeqthz"}
								data-framer-name={"Overlay"}
								layoutDependency={layoutDependency}
								layoutId={"f8nQ7vg47"}
								style={{
									backgroundColor:
										"var(--token-43eac8f6-6121-473c-88d1-781f7c603ff3, rgb(185, 255, 255))",
									opacity: 0,
								}}
								variants={{
									"kuybRR4_4-hover": {
										opacity: 1,
									},
								}}
							>
								<motion2.div
									className={"framer-erd6y1"}
									data-framer-name={"Label"}
									layoutDependency={layoutDependency}
									layoutId={"OCsawLj74"}
									style={{
										backgroundColor:
											"var(--token-a7c87a03-e4bc-4fee-bd27-763511435b35, rgb(18, 32, 35))",
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-l1qg15"}
										data-framer-name={"Text"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"Qs39u8VAP"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-a5f2dea9-e675-4451-817f-b93e011b3b4d, rgb(225, 252, 173))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										variants={{
											"kuybRR4_4-hover": {
												"--extracted-r6o4lv":
													"var(--token-38406790-1041-404b-8965-34452f5c8f25, rgb(53, 228, 228))",
											},
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												"kuybRR4_4-hover": {
													children: (
														<React3.Fragment>
															<motion2.p
																className={"framer-styles-preset-16bupuy"}
																data-styles-preset={"pJrILY7rY"}
																style={{
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-38406790-1041-404b-8965-34452f5c8f25, rgb(53, 228, 228)))",
																}}
															>
																{"Overview:"}
															</motion2.p>
														</React3.Fragment>
													),
													transformTemplate: transformTemplate1,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React3.Fragment>
											<motion2.p
												className={"framer-styles-preset-16bupuy"}
												data-styles-preset={"pJrILY7rY"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-a5f2dea9-e675-4451-817f-b93e011b3b4d, rgb(225, 252, 173)))",
												}}
											>
												{"Overview:"}
											</motion2.p>
										</React3.Fragment>
									</RichText>
								</motion2.div>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-28gu30"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"dCx6NAlT6"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											"kuybRR4_4-hover": {
												text: IHMAQA45k2,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React3.Fragment>
										<motion2.p
											className={"framer-styles-preset-1tix7ms"}
											data-styles-preset={"PNrJZBqkc"}
										>
											{
												"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa"
											}
										</motion2.p>
									</React3.Fragment>
								</RichText>
							</motion2.div>
							<Image
								background={{
									alt: "",
									fit: "fit",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 420) - 0 - 129.8) / 2 +
												0 +
												0),
									),
									sizes: "75px",
									...toResponsiveImage(g_945UDcK2),
									...{
										positionX: "center",
										positionY: "center",
									},
								}}
								className={"framer-184bks"}
								data-framer-name={"Icon"}
								layoutDependency={layoutDependency}
								layoutId={"pEVLNzmlm"}
								{...addPropertyOverrides(
									{
										Gn0ymALys: {
											background: {
												alt: "",
												fit: "fit",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 420) - 0 - 181) /
															2 +
															0 +
															0),
												),
												sizes: "75px",
												...toResponsiveImage(g_945UDcK2),
												...{
													positionX: "center",
													positionY: "center",
												},
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-vj9m91"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"ts8GLMslW"}
								style={{
									"--extracted-1eung3n": "rgba(0, 0, 0, 0.91)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={mnsQP78No2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React3.Fragment>
									<motion2.h4
										className={"framer-styles-preset-1nyw0o7"}
										data-styles-preset={"tUGyknt9Z"}
										style={{
											"--framer-text-color":
												"var(--extracted-1eung3n, rgba(0, 0, 0, 0.91))",
										}}
									>
										{"Cloud Infastructure"}
									</motion2.h4>
								</React3.Fragment>
							</RichText>
							{isDisplayed() && (
								<RichText
									__fromCanvasComponent={true}
									className={"framer-rvu60v"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"z2WmOVyTX"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React3.Fragment>
										<motion2.p
											className={"framer-styles-preset-16bupuy"}
											data-styles-preset={"pJrILY7rY"}
										>
											{"Learn More"}
										</motion2.p>
									</React3.Fragment>
								</RichText>
							)}
						</motion2.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-XvX2Q.framer-1wii8no, .framer-XvX2Q .framer-1wii8no { display: block; }",
	".framer-XvX2Q.framer-dano12 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: 420px; justify-content: center; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: 350px; }",
	".framer-XvX2Q .framer-1hno8i6 { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 36px); justify-content: center; overflow: hidden; padding: 0px; position: absolute; right: 16px; top: 16px; width: 36px; will-change: var(--framer-will-change-override, transform); z-index: 3; }",
	".framer-XvX2Q .framer-c1q9gm-container { flex: none; height: 16px; position: relative; width: 16px; }",
	".framer-XvX2Q .framer-oesd8s { height: 150px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 200px; will-change: var(--framer-will-change-override, transform); }",
	".framer-XvX2Q .framer-oeqthz { align-content: flex-start; align-items: flex-start; bottom: -420px; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; justify-content: center; left: 0px; overflow: hidden; padding: 32px; position: absolute; right: 0px; top: 420px; z-index: 1; }",
	".framer-XvX2Q .framer-erd6y1 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 8px; position: relative; width: min-content; }",
	".framer-XvX2Q .framer-l1qg15, .framer-XvX2Q .framer-vj9m91 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-XvX2Q .framer-28gu30 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-XvX2Q .framer-184bks { flex: none; height: 75px; position: relative; width: 75px; }",
	".framer-XvX2Q .framer-rvu60v { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 1; }",
	".framer-XvX2Q.framer-v-1gljl5s.framer-dano12 { cursor: unset; }",
	".framer-XvX2Q.framer-v-dano12.hover .framer-oeqthz { bottom: 0px; gap: 24px; top: 0px; }",
	".framer-XvX2Q.framer-v-dano12.hover .framer-erd6y1 { display: block; height: 32px; order: 0; padding: unset; width: 97px; }",
	".framer-XvX2Q.framer-v-dano12.hover .framer-l1qg15 { left: 50%; position: absolute; top: 51%; }",
	".framer-XvX2Q.framer-v-dano12.hover .framer-28gu30 { order: 1; }",
	...css,
	...css2,
	...css3,
];
var FramerhS1ai5DiN = withCSS(Component2, css4, "framer-XvX2Q");
var stdin_default = FramerhS1ai5DiN;
FramerhS1ai5DiN.displayName = "Focus Card";
FramerhS1ai5DiN.defaultProps = {
	height: 420,
	width: 350,
};
addPropertyControls2(FramerhS1ai5DiN, {
	variant: {
		options: ["kuybRR4_4", "Gn0ymALys"],
		optionTitles: ["Desktop", "Mobile"],
		title: "Variant",
		type: ControlType3.Enum,
	},
	mnsQP78No: {
		defaultValue: "Cloud Infastructure",
		displayTextArea: false,
		title: "Title",
		type: ControlType3.String,
	},
	IHMAQA45k: {
		defaultValue:
			"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa",
		displayTextArea: true,
		title: "Overview",
		type: ControlType3.String,
	},
	g_945UDcK: {
		__defaultAssetReference:
			"data:framer/asset-reference,kXEk5PthLueijJvPsw26V2PcWA.svg?originalFilename=enapter-cloud.svg&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,kXEk5PthLueijJvPsw26V2PcWA.svg?originalFilename=enapter-cloud.svg&preferredSize=auto",
		},
		title: "Icon",
		type: ControlType3.ResponsiveImage,
	},
});
addFonts(
	FramerhS1ai5DiN,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PhosphorFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:focus-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "Gn0ymALys",
	xl: "kuybRR4_4",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FocusCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var focus_card_default = ComponentWithRoot;
export { focus_card_default as default };
