// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c005e0105870bbbc "Mountain Futures (copy) (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Loading' | 'Hidden' // Variant
 * click?: Function // Click
}} Props

 */
import { routes } from "./chunks/chunk-MCZURAGM.js";

// virtual:load-more-2
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/aG9jxMV0eQfVMarbJTwJ/G9yXKdhqzBzE5kwmAivT/PCpbMQ9am.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion.div),
);
var cycleOrder = ["Sw5PV3LdJ", "yqEPh5Qk6", "vvTo4yzDr"];
var serializationHash = "framer-aydPC";
var variantClassNames = {
	Sw5PV3LdJ: "framer-v-f4shvb",
	vvTo4yzDr: "framer-v-1kj6006",
	yqEPh5Qk6: "framer-v-1jwjew1",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	duration: 0,
	type: "tween",
};
var transition2 = {
	delay: 0,
	duration: 0.3,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition3 = {
	delay: 0,
	duration: 1,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation2 = {
	opacity: 1,
	rotate: 360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "Sw5PV3LdJ",
	Hidden: "vvTo4yzDr",
	Loading: "yqEPh5Qk6",
};
var getProps = ({ click, height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "Sw5PV3LdJ",
		Wld3NDzSj: click ?? props.Wld3NDzSj,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, Wld3NDzSj, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Sw5PV3LdJ",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapn9xadi = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (Wld3NDzSj) {
			const res = await Wld3NDzSj(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [];
	const isDisplayed = () => {
		if (baseVariant === "vvTo4yzDr") return false;
		return true;
	};
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed1 = () => {
		if (baseVariant === "yqEPh5Qk6") return false;
		return true;
	};
	const isDisplayed2 = () => {
		if (baseVariant === "yqEPh5Qk6") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				{isDisplayed() && (
					<Transition value={transition1}>
						<motion.button
							{...restProps}
							{...gestureHandlers}
							className={cx(
								scopingClassNames,
								"framer-f4shvb",
								className,
								classNames,
							)}
							data-framer-name={"Default"}
							data-highlight={true}
							data-reset={"button"}
							layoutDependency={layoutDependency}
							layoutId={"Sw5PV3LdJ"}
							onTap={onTapn9xadi}
							ref={refBinding}
							style={{
								backgroundColor:
									"var(--token-88fd9b68-42f9-4676-b8dd-60b51ccd638a, rgb(39, 46, 63))",
								borderBottomLeftRadius: 28,
								borderBottomRightRadius: 28,
								borderTopLeftRadius: 28,
								borderTopRightRadius: 28,
								...style,
							}}
							{...addPropertyOverrides(
								{
									yqEPh5Qk6: {
										"data-framer-name": "Loading",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							{isDisplayed1() && (
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1a4rjvf"}
									fonts={["Inter-Medium"]}
									layoutDependency={layoutDependency}
									layoutId={"fgAABRgVC"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-38406790-1041-404b-8965-34452f5c8f25, rgb(53, 228, 228))",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--font-selector": "SW50ZXItTWVkaXVt",
												"--framer-font-size": "14px",
												"--framer-font-weight": "500",
												"--framer-text-alignment": "center",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-38406790-1041-404b-8965-34452f5c8f25, rgb(53, 228, 228)))",
											}}
										>
											{"Load More"}
										</motion.p>
									</React.Fragment>
								</RichText>
							)}
							{isDisplayed2() && (
								<MotionDivWithFXWithOptimizedAppearEffect
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									animate={animation}
									className={"framer-18pnf76"}
									data-framer-appear-id={"18pnf76"}
									data-framer-name={"Spinner"}
									initial={animation1}
									layoutDependency={layoutDependency}
									layoutId={"ymiNPbXws"}
									optimized={true}
									style={{
										mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
										WebkitMask:
											"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
									}}
								>
									<MotionDivWithFX
										__framer__loop={animation2}
										__framer__loopEffectEnabled={true}
										__framer__loopRepeatDelay={0}
										__framer__loopRepeatType={"loop"}
										__framer__loopTransition={transition3}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-9ykoul"}
										data-framer-name={"Conic"}
										layoutDependency={layoutDependency}
										layoutId={"IK2PTRKhb"}
										style={{
											background:
												"conic-gradient(from 0deg at 50% 50%, rgba(255, 255, 255, 0) 0deg, rgb(255, 255, 255) 342deg)",
										}}
									>
										<motion.div
											className={"framer-4xvy5"}
											data-framer-name={"Round"}
											layoutDependency={layoutDependency}
											layoutId={"EUymNFEyu"}
											style={{
												backgroundColor: "rgb(255, 255, 255)",
												borderBottomLeftRadius: 1,
												borderBottomRightRadius: 1,
												borderTopLeftRadius: 1,
												borderTopRightRadius: 1,
											}}
										/>
									</MotionDivWithFX>
								</MotionDivWithFXWithOptimizedAppearEffect>
							)}
						</motion.button>
					</Transition>
				)}
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-aydPC.framer-1qw8ei, .framer-aydPC .framer-1qw8ei { display: block; }",
	".framer-aydPC.framer-f4shvb { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 33px; justify-content: center; padding: 0px; position: relative; width: 100px; }",
	".framer-aydPC .framer-1a4rjvf { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-aydPC .framer-18pnf76 { aspect-ratio: 1 / 1; flex: none; gap: 10px; height: var(--framer-aspect-ratio-supported, 20px); overflow: visible; position: relative; width: 20px; }",
	".framer-aydPC .framer-9ykoul { bottom: 0px; flex: none; gap: 10px; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
	".framer-aydPC .framer-4xvy5 { flex: none; height: 2px; left: calc(50.00000000000002% - 2px / 2); overflow: visible; position: absolute; top: 0px; width: 2px; }",
];
var FramerPCpbMQ9am = withCSS(Component, css, "framer-aydPC");
var stdin_default = FramerPCpbMQ9am;
FramerPCpbMQ9am.displayName = "Load More 2";
FramerPCpbMQ9am.defaultProps = {
	height: 33,
	width: 100,
};
addPropertyControls(FramerPCpbMQ9am, {
	variant: {
		options: ["Sw5PV3LdJ", "yqEPh5Qk6", "vvTo4yzDr"],
		optionTitles: ["Default", "Loading", "Hidden"],
		title: "Variant",
		type: ControlType.Enum,
	},
	Wld3NDzSj: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramerPCpbMQ9am,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/UjlFhCnUjxhNfep4oYBPqnEssyo.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
					weight: "500",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:load-more-2
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "Sw5PV3LdJ",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders LoadMore2FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var load_more_2_default = ComponentWithRoot;
export { load_more_2_default as default };
