// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c005e0105870bbbc "Mountain Futures (copy) (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Mobile' | 'Mobile Right' // Variant
 * text?: string // Text
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-E2DSRDMQ.js";
import { routes } from "./chunks/chunk-MCZURAGM.js";

// virtual:map-location
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/uEfRw7uP6hfKaS2Pxogk/dhtt3WNR0d1fpmj4sWjK/oItj3Yq85.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/1wRluNa547OhmZk5NPlo/EUQOsYkTc7KI6JWOjuH9/S8iK4lF1A.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-YrlAW";
var variantClassNames = {
	W3IlnisLN: "framer-v-3hvggr",
};
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, text, width, ...props }) => {
	return {
		...props,
		sgJLVHIQy: text ?? props.sgJLVHIQy ?? "Tooltip",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		sgJLVHIQy,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "W3IlnisLN",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-3hvggr",
							className2,
							classNames,
						)}
						data-framer-name={"Top"}
						layoutDependency={layoutDependency}
						layoutId={"W3IlnisLN"}
						ref={refBinding}
						style={{
							backdropFilter: "blur(5px)",
							WebkitBackdropFilter: "blur(5px)",
							...style,
						}}
					>
						<motion.div
							className={"framer-1wjnu25"}
							data-framer-name={"Tooltip"}
							layoutDependency={layoutDependency}
							layoutId={"GTPrkrNQC"}
							style={{
								backgroundColor: "rgba(232, 232, 232, 0.75)",
							}}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-14oc3ha"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"oqAyekXPl"}
								style={{
									"--framer-link-current-text-color":
										"var(--token-bd71055c-0a2c-4476-8cc9-4310acba652d, rgb(0, 136, 255))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={sgJLVHIQy}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-16bupuy"}
										data-styles-preset={"pJrILY7rY"}
									>
										{"Tooltip"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-YrlAW.framer-1fn8yt2, .framer-YrlAW .framer-1fn8yt2 { display: block; }",
	".framer-YrlAW.framer-3hvggr { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; padding: 0px; position: relative; width: min-content; }",
	".framer-YrlAW .framer-1wjnu25 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: flex-start; overflow: visible; padding: 8px 10px 8px 10px; position: relative; width: min-content; }",
	".framer-YrlAW .framer-14oc3ha { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	...css,
];
var FramerS8iK4lF1A = withCSS(Component, css2, "framer-YrlAW");
var stdin_default = FramerS8iK4lF1A;
FramerS8iK4lF1A.displayName = "Tooltip";
FramerS8iK4lF1A.defaultProps = {
	height: 32,
	width: 71,
};
addPropertyControls(FramerS8iK4lF1A, {
	sgJLVHIQy: {
		defaultValue: "Tooltip",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
});
addFonts(
	FramerS8iK4lF1A,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/uEfRw7uP6hfKaS2Pxogk/dhtt3WNR0d1fpmj4sWjK/oItj3Yq85.js
var TooltipFonts = getFonts(stdin_default);
var enabledGestures = {
	Zmh7ZkdTK: {
		hover: true,
	},
};
var cycleOrder = ["Zmh7ZkdTK", "sBgeBaa4E", "l1PGzMZWo"];
var serializationHash2 = "framer-7w3QA";
var variantClassNames2 = {
	l1PGzMZWo: "framer-v-1mt1nb1",
	sBgeBaa4E: "framer-v-e68y4b",
	Zmh7ZkdTK: "framer-v-1a7c29q",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap = {
	"Mobile Right": "l1PGzMZWo",
	Desktop: "Zmh7ZkdTK",
	Mobile: "sBgeBaa4E",
};
var getProps2 = ({ height, id, text, width, ...props }) => {
	return {
		...props,
		RjpLX7qDZ: text ?? props.RjpLX7qDZ ?? "Tooltip",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "Zmh7ZkdTK",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		RjpLX7qDZ,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder,
		defaultVariant: "Zmh7ZkdTK",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1a7c29q",
							className2,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"Zmh7ZkdTK"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								"Zmh7ZkdTK-hover": {
									"data-framer-name": void 0,
								},
								l1PGzMZWo: {
									"data-framer-name": "Mobile Right",
								},
								sBgeBaa4E: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider
							height={32}
							y={(componentViewport?.y || 0) + -50}
							{...addPropertyOverrides(
								{
									"Zmh7ZkdTK-hover": {
										y: (componentViewport?.y || 0) + -39,
									},
									l1PGzMZWo: {
										y: (componentViewport?.y || 0) + 0,
									},
									sBgeBaa4E: {
										y: (componentViewport?.y || 0) + -36,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-pwbwkw-container"}
								layoutDependency={layoutDependency}
								layoutId={"kVvPMh2LB-container"}
								nodeId={"kVvPMh2LB"}
								rendersWithMotion={true}
								scopeId={"oItj3Yq85"}
								style={{
									opacity: 0,
								}}
								variants={{
									"Zmh7ZkdTK-hover": {
										opacity: 1,
									},
									l1PGzMZWo: {
										opacity: 1,
									},
									sBgeBaa4E: {
										opacity: 1,
									},
								}}
							>
								{_jsx2(stdin_default, {
									height: "100%",
									id: "kVvPMh2LB",
									layoutId: "kVvPMh2LB",
									sgJLVHIQy: RjpLX7qDZ,
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<motion2.div
							className={"framer-1y67w5s"}
							data-framer-name={"Button"}
							layoutDependency={layoutDependency}
							layoutId={"I1vSSJwuG"}
							style={{
								backgroundColor:
									"var(--token-43eac8f6-6121-473c-88d1-781f7c603ff3, rgb(185, 255, 255))",
								borderBottomLeftRadius: 25,
								borderBottomRightRadius: 25,
								borderTopLeftRadius: 25,
								borderTopRightRadius: 25,
								boxShadow:
									"0px 0.7065919983928324px 2.9676863932498962px -0.625px rgba(0, 0, 0, 0.15), 0px 1.8065619053231785px 7.58756000235735px -1.25px rgba(0, 0, 0, 0.14), 0px 3.6217592146567767px 15.211388701558462px -1.875px rgba(0, 0, 0, 0.14), 0px 6.8655999097303715px 28.835519620867558px -2.5px rgba(0, 0, 0, 0.13), 0px 13.646761411524492px 57.31639792840287px -3.125px rgba(0, 0, 0, 0.1), 0px 30px 126px -3.75px rgba(0, 0, 0, 0.05)",
								opacity: 1,
							}}
							variants={{
								"Zmh7ZkdTK-hover": {
									opacity: 0.8,
								},
							}}
						>
							<motion2.div
								className={"framer-rxbshc"}
								layoutDependency={layoutDependency}
								layoutId={"Rgk0q8duH"}
								style={{
									backgroundColor:
										"var(--token-d9340a14-727b-4bd4-bace-fe44143906be, rgb(26, 44, 48))",
									borderBottomLeftRadius: "100%",
									borderBottomRightRadius: "100%",
									borderTopLeftRadius: "100%",
									borderTopRightRadius: "100%",
								}}
								transformTemplate={transformTemplate1}
							/>
						</motion2.div>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-7w3QA.framer-1362jnr, .framer-7w3QA .framer-1362jnr { display: block; }",
	".framer-7w3QA.framer-1a7c29q { align-content: center; align-items: center; cursor: default; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 40px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 32px; }",
	".framer-7w3QA .framer-pwbwkw-container { flex: none; height: auto; left: -20px; pointer-events: none; position: absolute; top: -50px; width: auto; z-index: 1; }",
	".framer-7w3QA .framer-1y67w5s { flex: 1 0 0px; gap: 10px; height: 100%; overflow: visible; position: relative; width: 1px; }",
	".framer-7w3QA .framer-rxbshc { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 6px); left: 50%; overflow: hidden; position: absolute; top: 50%; width: 6px; will-change: var(--framer-will-change-override, transform); }",
	".framer-7w3QA.framer-v-e68y4b.framer-1a7c29q, .framer-7w3QA.framer-v-1mt1nb1.framer-1a7c29q, .framer-7w3QA.framer-v-1a7c29q.hover.framer-1a7c29q { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 32px); }",
	".framer-7w3QA.framer-v-e68y4b .framer-pwbwkw-container { top: -36px; }",
	".framer-7w3QA.framer-v-1mt1nb1 .framer-pwbwkw-container { left: 34px; top: 0px; }",
	".framer-7w3QA.framer-v-1a7c29q.hover .framer-pwbwkw-container { top: -39px; }",
];
var FrameroItj3Yq85 = withCSS2(Component2, css3, "framer-7w3QA");
var stdin_default2 = FrameroItj3Yq85;
FrameroItj3Yq85.displayName = "Map Location";
FrameroItj3Yq85.defaultProps = {
	height: 32,
	width: 32,
};
addPropertyControls2(FrameroItj3Yq85, {
	variant: {
		options: ["Zmh7ZkdTK", "sBgeBaa4E", "l1PGzMZWo"],
		optionTitles: ["Desktop", "Mobile", "Mobile Right"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	RjpLX7qDZ: {
		defaultValue: "Tooltip",
		displayTextArea: false,
		title: "Text",
		type: ControlType2.String,
	},
});
addFonts2(
	FrameroItj3Yq85,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...TooltipFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:map-location
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "sBgeBaa4E",
	lg: "Zmh7ZkdTK",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MapLocationFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var map_location_default = ComponentWithRoot;
export { map_location_default as default };
