// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c005e0105870bbbc "Mountain Futures (copy) (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Mobile' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-MCZURAGM.js";

// virtual:map
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/9niKSXLGGz2E4cOyplkJ/vT6osQl7xt4OuOjxWLRb/kn09vyFv0.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["TIMaCSTdq", "KJEVV6guu", "atJ67BTuN"];
var serializationHash = "framer-OF8B6";
var variantClassNames = {
	atJ67BTuN: "framer-v-91xw96",
	KJEVV6guu: "framer-v-9ypc4t",
	TIMaCSTdq: "framer-v-1r48gk",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "TIMaCSTdq",
	Mobile: "atJ67BTuN",
	Tablet: "KJEVV6guu",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "TIMaCSTdq",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "TIMaCSTdq",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1ae5saf = activeVariantCallback(async (...args) => {
		setVariant("TIMaCSTdq");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "atJ67BTuN") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1r48gk",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"TIMaCSTdq"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(68, 204, 255)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								atJ67BTuN: {
									"data-framer-name": "Mobile",
								},
								KJEVV6guu: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<motion.div
								className={"framer-qdrwmv"}
								data-framer-name={"Map Interactive"}
								data-highlight={true}
								layoutDependency={layoutDependency}
								layoutId={"zCSpaOnDj"}
								onTap={onTap1ae5saf}
							/>
						)}
						<motion.div
							className={"framer-15slbbd"}
							data-framer-name={"Image Wrapper"}
							layoutDependency={layoutDependency}
							layoutId={"fDH_3vPLy"}
						>
							<Image
								background={{
									alt: "",
									fit: "fit",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											0 +
											(0 +
												((componentViewport?.height || 570) -
													0 -
													0 -
													((componentViewport?.height || 570) - 0 - 0) * 1) /
													2),
									),
									pixelHeight: 570,
									pixelWidth: 1100,
									positionX: "center",
									positionY: "center",
									sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
									src: "https://framerusercontent.com/images/owZBfJ3AnDKaW81Gb4WoW1kL1WA.png?width=1100&height=570",
									srcSet:
										"https://framerusercontent.com/images/owZBfJ3AnDKaW81Gb4WoW1kL1WA.png?scale-down-to=512&width=1100&height=570 512w,https://framerusercontent.com/images/owZBfJ3AnDKaW81Gb4WoW1kL1WA.png?scale-down-to=1024&width=1100&height=570 1024w,https://framerusercontent.com/images/owZBfJ3AnDKaW81Gb4WoW1kL1WA.png?width=1100&height=570 1100w",
								}}
								className={"framer-x2vd0z"}
								data-highlight={true}
								layoutDependency={layoutDependency}
								layoutId={"zCdlCZk71"}
								onTap={onTap1ae5saf}
								{...addPropertyOverrides(
									{
										atJ67BTuN: {
											background: {
												alt: "",
												fit: "fit",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														0 +
														(0 +
															((componentViewport?.height || 373) -
																0 -
																0 -
																((componentViewport?.height || 373) - 0 - 0) *
																	1) /
																2),
												),
												pixelHeight: 570,
												pixelWidth: 1100,
												positionX: "center",
												positionY: "center",
												sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
												src: "https://framerusercontent.com/images/owZBfJ3AnDKaW81Gb4WoW1kL1WA.png?width=1100&height=570",
												srcSet:
													"https://framerusercontent.com/images/owZBfJ3AnDKaW81Gb4WoW1kL1WA.png?scale-down-to=512&width=1100&height=570 512w,https://framerusercontent.com/images/owZBfJ3AnDKaW81Gb4WoW1kL1WA.png?scale-down-to=1024&width=1100&height=570 1024w,https://framerusercontent.com/images/owZBfJ3AnDKaW81Gb4WoW1kL1WA.png?width=1100&height=570 1100w",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-OF8B6.framer-1cnotut, .framer-OF8B6 .framer-1cnotut { display: block; }",
	".framer-OF8B6.framer-1r48gk { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: 570px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1100px; }",
	".framer-OF8B6 .framer-qdrwmv { align-content: center; align-items: center; cursor: pointer; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 1px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 2; }",
	".framer-OF8B6 .framer-15slbbd { align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; justify-content: center; left: 0px; overflow: visible; padding: 0px; position: absolute; right: 0px; top: 0px; z-index: 1; }",
	".framer-OF8B6 .framer-x2vd0z { cursor: pointer; flex: 1 0 0px; height: 100%; position: relative; width: 1px; }",
	".framer-OF8B6.framer-v-9ypc4t.framer-1r48gk { width: 778px; }",
	".framer-OF8B6.framer-v-9ypc4t .framer-qdrwmv { order: 0; }",
	".framer-OF8B6.framer-v-9ypc4t .framer-15slbbd { order: 1; }",
	".framer-OF8B6.framer-v-91xw96.framer-1r48gk { height: 373px; width: 310px; }",
];
var Framerkn09vyFv0 = withCSS(Component, css, "framer-OF8B6");
var stdin_default = Framerkn09vyFv0;
Framerkn09vyFv0.displayName = "Map";
Framerkn09vyFv0.defaultProps = {
	height: 570,
	width: 1100,
};
addPropertyControls(Framerkn09vyFv0, {
	variant: {
		options: ["TIMaCSTdq", "KJEVV6guu", "atJ67BTuN"],
		optionTitles: ["Desktop", "Tablet", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	Framerkn09vyFv0,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:map
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "atJ67BTuN",
	md: "KJEVV6guu",
	xl: "TIMaCSTdq",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MapFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var map_default = ComponentWithRoot;
export { map_default as default };
