// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c005e0105870bbbc "Mountain Futures (copy) (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // Title
 * description?: string // Description
 * number?: string // Number
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-ZVSW4UDK.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-E2DSRDMQ.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-XOYYYZYZ.js";
import { routes } from "./chunks/chunk-MCZURAGM.js";

// virtual:process-item
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/1HhHhkPdbhfYPvmKAb7x/pv3IR3c25IrB8RGE27JC/FE9UD06rO.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-E6S1n";
var variantClassNames = {
	ACQuFRLcB: "framer-v-z6e4gv",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	description,
	height,
	id,
	number,
	title,
	width,
	...props
}) => {
	return {
		...props,
		o8cqVruEu: number ?? props.o8cqVruEu ?? "01",
		wf4B0gy71:
			description ??
			props.wf4B0gy71 ??
			"We take the time to understand your unique needs and goals, listening carefully to your challenges and opportunities. This foundation of trust and understanding enables us to deliver tailored solutions that meet your objectives.",
		ZzfhAtmjk: title ?? props.ZzfhAtmjk ?? "Headline",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		ZzfhAtmjk,
		wf4B0gy71,
		o8cqVruEu,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "ACQuFRLcB",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className, className3];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-z6e4gv",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"ACQuFRLcB"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<motion.div
							className={"framer-oym535"}
							data-framer-name={"Wrap"}
							layoutDependency={layoutDependency}
							layoutId={"kdAbrfNfm"}
						>
							<motion.div
								className={"framer-693wtn"}
								layoutDependency={layoutDependency}
								layoutId={"sHsrOq4tD"}
								style={{
									backgroundColor:
										"var(--token-d9340a14-727b-4bd4-bace-fe44143906be, rgb(26, 44, 48))",
									borderBottomLeftRadius: "100%",
									borderBottomRightRadius: "100%",
									borderTopLeftRadius: "100%",
									borderTopRightRadius: "100%",
								}}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-bhlycu"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"YBEfiuQXG"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-a5f2dea9-e675-4451-817f-b93e011b3b4d, rgb(225, 252, 173))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={o8cqVruEu}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-16bupuy"}
											data-styles-preset={"pJrILY7rY"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-a5f2dea9-e675-4451-817f-b93e011b3b4d, rgb(225, 252, 173)))",
											}}
										>
											{"01"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-6n8qbp"}
								data-border={true}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"dhCbKx7OU"}
								style={{
									"--border-bottom-width": "1px",
									"--border-color":
										"var(--token-4a657333-042a-4ee5-8ab0-89f8b6ae1452, rgb(218, 218, 218))",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-style": "dashed",
									"--border-top-width": "0px",
								}}
							/>
						</motion.div>
						<motion.div
							className={"framer-h9kisi"}
							data-framer-name={"Wrap"}
							layoutDependency={layoutDependency}
							layoutId={"ATWtxkj7L"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-wikeqd"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"iga3lMTMH"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={ZzfhAtmjk}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h3
										className={"framer-styles-preset-rwcd89"}
										data-styles-preset={"fVNgQUCuM"}
									>
										{"Headline"}
									</motion.h3>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-197bhag"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"FOhyyBBaY"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={wf4B0gy71}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1tix7ms"}
										data-styles-preset={"PNrJZBqkc"}
									>
										{
											"We take the time to understand your unique needs and goals, listening carefully to your challenges and opportunities. This foundation of trust and understanding enables us to deliver tailored solutions that meet your objectives."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-E6S1n.framer-1a12vd8, .framer-E6S1n .framer-1a12vd8 { display: block; }",
	".framer-E6S1n.framer-z6e4gv { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 244px; }",
	".framer-E6S1n .framer-oym535 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; max-width: 400px; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-E6S1n .framer-693wtn { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 30px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 30px; }",
	".framer-E6S1n .framer-bhlycu, .framer-E6S1n .framer-wikeqd { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-E6S1n .framer-6n8qbp { flex: 1 0 0px; height: 9px; overflow: hidden; position: relative; width: 1px; }",
	".framer-E6S1n .framer-h9kisi { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-E6S1n .framer-197bhag { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	...css2,
	...css,
	...css3,
	'.framer-E6S1n[data-border="true"]::after, .framer-E6S1n [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerFE9UD06rO = withCSS(Component, css4, "framer-E6S1n");
var stdin_default = FramerFE9UD06rO;
FramerFE9UD06rO.displayName = "Process Item";
FramerFE9UD06rO.defaultProps = {
	height: 242.5,
	width: 244,
};
addPropertyControls(FramerFE9UD06rO, {
	ZzfhAtmjk: {
		defaultValue: "Headline",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	wf4B0gy71: {
		defaultValue:
			"We take the time to understand your unique needs and goals, listening carefully to your challenges and opportunities. This foundation of trust and understanding enables us to deliver tailored solutions that meet your objectives.",
		displayTextArea: true,
		title: "Description",
		type: ControlType.String,
	},
	o8cqVruEu: {
		defaultValue: "01",
		displayTextArea: false,
		title: "Number",
		type: ControlType.String,
	},
});
addFonts(
	FramerFE9UD06rO,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:process-item
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ProcessItemFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var process_item_default = ComponentWithRoot;
export { process_item_default as default };
