// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c005e0105870bbbc "Mountain Futures (copy) (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Mobile' // Variant
 * projectThumb?: {src: string, srcSet?: string, alt?: string} // Project Thumb
 * himalayaCryosphere?: string // Himalaya Cryosphere
 * _2025?: string // 2025
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-NQXJPMXD.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-YULNS5JV.js";
import { routes } from "./chunks/chunk-MCZURAGM.js";

// virtual:project-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/d39a4gAnRa9DwNtvwnT6/tpB29nWIulCznxLOP3CG/L0Ea4VWGA.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	y3DTcrdKJ: {
		hover: true,
	},
};
var cycleOrder = ["y3DTcrdKJ", "c6EYcrmvh"];
var serializationHash = "framer-QnPga";
var variantClassNames = {
	c6EYcrmvh: "framer-v-j3usmk",
	y3DTcrdKJ: "framer-v-q37esy",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.6,
	ease: [0.08, 0.78, 0.56, 1],
	type: "tween",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "y3DTcrdKJ",
	Mobile: "c6EYcrmvh",
};
var getProps = ({
	_2025,
	height,
	himalayaCryosphere,
	id,
	projectThumb,
	width,
	...props
}) => {
	return {
		...props,
		RiprljAsu: himalayaCryosphere ?? props.RiprljAsu ?? "Case Study Name",
		uvH0OIOZE: _2025 ?? props.uvH0OIOZE ?? "Date",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "y3DTcrdKJ",
		zLyYOPkpc: projectThumb ??
			props.zLyYOPkpc ?? {
				alt: "",
				pixelHeight: 1600,
				pixelWidth: 2400,
				src: "https://framerusercontent.com/images/hVtlyE4SBJuG0v23c8yUdx2cqkc.webp?width=2400&height=1600",
				srcSet:
					"https://framerusercontent.com/images/hVtlyE4SBJuG0v23c8yUdx2cqkc.webp?scale-down-to=512&width=2400&height=1600 512w,https://framerusercontent.com/images/hVtlyE4SBJuG0v23c8yUdx2cqkc.webp?scale-down-to=1024&width=2400&height=1600 1024w,https://framerusercontent.com/images/hVtlyE4SBJuG0v23c8yUdx2cqkc.webp?scale-down-to=2048&width=2400&height=1600 2048w,https://framerusercontent.com/images/hVtlyE4SBJuG0v23c8yUdx2cqkc.webp?width=2400&height=1600 2400w",
			},
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		zLyYOPkpc: zLyYOPkpc2,
		RiprljAsu: RiprljAsu2,
		uvH0OIOZE: uvH0OIOZE2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "y3DTcrdKJ",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-q37esy",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"y3DTcrdKJ"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								"y3DTcrdKJ-hover": {
									"data-framer-name": void 0,
								},
								c6EYcrmvh: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1xv7zx4"}
							data-border={true}
							data-framer-name={"Project Info Wrap"}
							layoutDependency={layoutDependency}
							layoutId={"sXUdBJI4I"}
							style={{
								"--border-bottom-width": "0px",
								"--border-color": "rgba(255, 255, 255, 0.5)",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-style": "dotted",
								"--border-top-width": "1px",
							}}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1qlj1is"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"T7lsrrP1e"}
								style={{
									"--extracted-1eung3n":
										"var(--token-ad0dbc1a-e59a-47ab-8ef3-f598c1c19141, rgb(255, 255, 255))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={RiprljAsu2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h4
										className={"framer-styles-preset-1nyw0o7"}
										data-styles-preset={"tUGyknt9Z"}
										style={{
											"--framer-text-color":
												"var(--extracted-1eung3n, var(--token-ad0dbc1a-e59a-47ab-8ef3-f598c1c19141, rgb(255, 255, 255)))",
										}}
									>
										{"Case Study Name"}
									</motion.h4>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1fbd4qq"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"fJzCcjkj8"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-4a657333-042a-4ee5-8ab0-89f8b6ae1452, rgb(201, 201, 201))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={uvH0OIOZE2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1t0inl8"}
										data-styles-preset={"OOfFModLo"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-4a657333-042a-4ee5-8ab0-89f8b6ae1452, rgb(201, 201, 201)))",
										}}
									>
										{"Date"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<motion.div
							className={"framer-1qksnnh"}
							data-framer-name={"Image Wrap"}
							layoutDependency={layoutDependency}
							layoutId={"REw9NxkOe"}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) + 0 + 0,
									),
									pixelHeight: 1600,
									pixelWidth: 2400,
									sizes: componentViewport?.width || "100vw",
									...toResponsiveImage(zLyYOPkpc2),
								}}
								className={"framer-y1zqdd"}
								layoutDependency={layoutDependency}
								layoutId={"nDtidjz01"}
								style={{
									filter: "brightness(0.9) grayscale(0.76)",
									scale: 1,
									WebkitFilter: "brightness(0.9) grayscale(0.76)",
								}}
								variants={{
									"y3DTcrdKJ-hover": {
										filter: "brightness(0.9) grayscale(0)",
										scale: 1.1,
										WebkitFilter: "brightness(0.9) grayscale(0)",
									},
								}}
							/>
							<motion.div
								className={"framer-rg24v"}
								layoutDependency={layoutDependency}
								layoutId={"ctG28iYjJ"}
								style={{
									background:
										"linear-gradient(180deg, rgba(233, 233, 233, 0.03) 0%, rgb(56, 56, 56) 100%)",
								}}
							/>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-QnPga.framer-1ki0pmb, .framer-QnPga .framer-1ki0pmb { display: block; }",
	".framer-QnPga.framer-q37esy { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 74px; height: 334px; justify-content: flex-end; overflow: hidden; padding: 16px; position: relative; width: 461px; }",
	".framer-QnPga .framer-1xv7zx4 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: wrap; gap: 4px 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 6px 0px 0px 0px; position: relative; width: 100%; }",
	".framer-QnPga .framer-1qlj1is, .framer-QnPga .framer-1fbd4qq { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-QnPga .framer-1qksnnh { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; z-index: -1; }",
	".framer-QnPga .framer-y1zqdd { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-filter-override, filter); }",
	".framer-QnPga .framer-rg24v { bottom: 0px; flex: none; height: 198px; left: 0px; overflow: visible; position: absolute; right: 0px; }",
	".framer-QnPga.framer-v-j3usmk.framer-q37esy { cursor: unset; }",
	...css2,
	...css,
	'.framer-QnPga[data-border="true"]::after, .framer-QnPga [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerL0Ea4VWGA = withCSS(Component, css3, "framer-QnPga");
var stdin_default = FramerL0Ea4VWGA;
FramerL0Ea4VWGA.displayName = "Project Card";
FramerL0Ea4VWGA.defaultProps = {
	height: 334,
	width: 461,
};
addPropertyControls(FramerL0Ea4VWGA, {
	variant: {
		options: ["y3DTcrdKJ", "c6EYcrmvh"],
		optionTitles: ["Desktop", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	zLyYOPkpc: {
		__defaultAssetReference:
			"data:framer/asset-reference,hVtlyE4SBJuG0v23c8yUdx2cqkc.webp?originalFilename=zac-wolff-baXCV2qg9Ew-unsplash.webp&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,hVtlyE4SBJuG0v23c8yUdx2cqkc.webp?originalFilename=zac-wolff-baXCV2qg9Ew-unsplash.webp&preferredSize=auto",
		},
		title: "Project Thumb",
		type: ControlType.ResponsiveImage,
	},
	RiprljAsu: {
		defaultValue: "Case Study Name",
		description: "",
		displayTextArea: true,
		title: "Himalaya Cryosphere",
		type: ControlType.String,
	},
	uvH0OIOZE: {
		defaultValue: "Date",
		displayTextArea: false,
		title: "2025",
		type: ControlType.String,
	},
});
addFonts(
	FramerL0Ea4VWGA,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:project-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "c6EYcrmvh",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ProjectCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var project_card_default = ComponentWithRoot;
export { project_card_default as default };
