// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c005e0105870bbbc "Mountain Futures (copy) (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Hover' | 'Mobile' // Variant
 * text?: string // Text
 * link?: string // Link
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-XOYYYZYZ.js";
import { routes } from "./chunks/chunk-MCZURAGM.js";

// virtual:secondary
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/1XxDaTIIJU20xWTCdGqu/JT0LZQd1d3v1AsLpReir/wkfq7ysz3.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["QGgIfef0Z", "c0dquppYU", "Sv2cYODtY"];
var serializationHash = "framer-h9tvQ";
var variantClassNames = {
	c0dquppYU: "framer-v-1eo80hu",
	QGgIfef0Z: "framer-v-rawqu6",
	Sv2cYODtY: "framer-v-1iv86dq",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.6,
	ease: [0.08, 0.78, 0.56, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "QGgIfef0Z",
	Hover: "c0dquppYU",
	Mobile: "Sv2cYODtY",
};
var getProps = ({ height, id, link, text, width, ...props }) => {
	return {
		...props,
		BYNIrUSxY: text ?? props.BYNIrUSxY ?? "Button Text",
		F3zKmwx_W: link ?? props.F3zKmwx_W,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "QGgIfef0Z",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		BYNIrUSxY,
		F3zKmwx_W,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "QGgIfef0Z",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnterbfy0q5 = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		setVariant("c0dquppYU");
	});
	const onMouseLeave6jxa73 = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		setVariant("QGgIfef0Z");
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						motionChild={true}
						nodeId={"QGgIfef0Z"}
						scopeId={"wkfq7ysz3"}
						{...addPropertyOverrides(
							{
								c0dquppYU: {
									href: F3zKmwx_W,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-rawqu6", className2, classNames)} framer-25017l`}
							data-framer-name={"Default"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"QGgIfef0Z"}
							onMouseEnter={onMouseEnterbfy0q5}
							ref={refBinding}
							style={{
								backdropFilter: "blur(3px)",
								WebkitBackdropFilter: "blur(3px)",
								...style,
							}}
							{...addPropertyOverrides(
								{
									c0dquppYU: {
										"data-framer-name": "Hover",
										onMouseLeave: onMouseLeave6jxa73,
									},
									Sv2cYODtY: {
										"data-framer-name": "Mobile",
										"data-highlight": void 0,
										onMouseEnter: void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-1ip05r8"}
								data-framer-name={"Button Body"}
								layoutDependency={layoutDependency}
								layoutId={"Ejl9LZ4nS"}
								style={{
									backdropFilter: "blur(5px)",
									backgroundColor:
										"var(--token-38406790-1041-404b-8965-34452f5c8f25, rgb(53, 228, 228))",
									borderBottomLeftRadius: 22,
									borderBottomRightRadius: 22,
									borderTopLeftRadius: 22,
									borderTopRightRadius: 22,
									WebkitBackdropFilter: "blur(5px)",
								}}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-188opaw"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"doC2s_1t2"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-88fd9b68-42f9-4676-b8dd-60b51ccd638a, rgb(39, 46, 63))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={BYNIrUSxY}
									variants={{
										c0dquppYU: {
											"--extracted-r6o4lv":
												"var(--token-ad0dbc1a-e59a-47ab-8ef3-f598c1c19141, rgb(255, 255, 255))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											c0dquppYU: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1tix7ms"}
															data-styles-preset={"PNrJZBqkc"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-ad0dbc1a-e59a-47ab-8ef3-f598c1c19141, rgb(255, 255, 255)))",
															}}
														>
															{"Button Text"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1tix7ms"}
											data-styles-preset={"PNrJZBqkc"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-88fd9b68-42f9-4676-b8dd-60b51ccd638a, rgb(39, 46, 63)))",
											}}
										>
											{"Button Text"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-h9tvQ.framer-25017l, .framer-h9tvQ .framer-25017l { display: block; }",
	".framer-h9tvQ.framer-rawqu6 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-h9tvQ .framer-1ip05r8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 10px 16px 10px 16px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-h9tvQ .framer-188opaw { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-h9tvQ.framer-v-1eo80hu.framer-rawqu6 { text-decoration: none; }",
	...css,
];
var Framerwkfq7ysz3 = withCSS(Component, css2, "framer-h9tvQ");
var stdin_default = Framerwkfq7ysz3;
Framerwkfq7ysz3.displayName = "Secondary";
Framerwkfq7ysz3.defaultProps = {
	height: 41.7,
	width: 102.45,
};
addPropertyControls(Framerwkfq7ysz3, {
	variant: {
		options: ["QGgIfef0Z", "c0dquppYU", "Sv2cYODtY"],
		optionTitles: ["Default", "Hover", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	BYNIrUSxY: {
		defaultValue: "Button Text",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	F3zKmwx_W: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	Framerwkfq7ysz3,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:secondary
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "Sv2cYODtY",
	xl: "QGgIfef0Z",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SecondaryFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var secondary_default = ComponentWithRoot;
export { secondary_default as default };
