// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c005e0105870bbbc "Mountain Futures (copy) (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-ZVSW4UDK.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-E2DSRDMQ.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-XOYYYZYZ.js";
import { routes } from "./chunks/chunk-MCZURAGM.js";

// virtual:section-contact
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/8oEYLNDigAqCVO5Uobev/eVsDAybFAyVYWRXXYXIO/pz7iat1aX.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	ResolveLinks,
	RichText as RichText2,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useRouter,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/ssMGOTITooX2LnWSTv0c/XILsfb6SNkxAKw52RTvQ/fJd5WHftj.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"Inter",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts4 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/syRNPWzAMIrcJ3wIlPIP43KjQs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/ia3uin3hQWqDrVloC1zEtYHWw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/pKRFNWFoZl77qYCAIp84lN1h944.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css4 = [
	'.framer-QNnJ5 .framer-styles-preset-yifk8q:not(.rich-text-wrapper), .framer-QNnJ5 .framer-styles-preset-yifk8q.rich-text-wrapper p { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 29px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.05em; --framer-line-height: 34px; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-425d5885-8b67-4657-91de-de73d3d0dc86, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-QNnJ5 .framer-styles-preset-yifk8q:not(.rich-text-wrapper), .framer-QNnJ5 .framer-styles-preset-yifk8q.rich-text-wrapper p { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 38px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.05em; --framer-line-height: 34px; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-425d5885-8b67-4657-91de-de73d3d0dc86, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-QNnJ5 .framer-styles-preset-yifk8q:not(.rich-text-wrapper), .framer-QNnJ5 .framer-styles-preset-yifk8q.rich-text-wrapper p { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 31px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.05em; --framer-line-height: 34px; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-425d5885-8b67-4657-91de-de73d3d0dc86, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className4 = "framer-QNnJ5";

// /:https://framerusercontent.com/modules/8QWLx6p74tqc3HILDlhZ/j8TR5DHao24fm8jtKJH2/nE7aLofwL.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["IuDNKR63H", "x20vFQbdH", "AcB5hVtra"];
var serializationHash = "framer-N7rNf";
var variantClassNames = {
	AcB5hVtra: "framer-v-n8hnmg",
	IuDNKR63H: "framer-v-bg9hh3",
	x20vFQbdH: "framer-v-1gkfjr8",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.6,
	ease: [0.08, 0.78, 0.56, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "IuDNKR63H",
	Hover: "x20vFQbdH",
	Mobile: "AcB5hVtra",
};
var getProps = ({ click, height, id, link, text, width, ...props }) => {
	return {
		...props,
		BYNIrUSxY: text ?? props.BYNIrUSxY ?? "Button Text",
		hYruqSCKG: link ?? props.hYruqSCKG,
		NVEphcQnB: click ?? props.NVEphcQnB,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "IuDNKR63H",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		BYNIrUSxY,
		hYruqSCKG,
		NVEphcQnB,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "IuDNKR63H",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapnr4g8n = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (NVEphcQnB) {
			const res = await NVEphcQnB(...args);
			if (res === false) return false;
		}
	});
	const onMouseEntert3swwa = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		setVariant("x20vFQbdH");
	});
	const onMouseLeave1crw1un = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		setVariant("IuDNKR63H");
	});
	const sharedStyleClassNames = [className3];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						motionChild={true}
						nodeId={"IuDNKR63H"}
						scopeId={"nE7aLofwL"}
						{...addPropertyOverrides(
							{
								AcB5hVtra: {
									href: hYruqSCKG,
								},
								x20vFQbdH: {
									href: hYruqSCKG,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-bg9hh3", className5, classNames)} framer-14ls221`}
							data-framer-name={"Default"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"IuDNKR63H"}
							onMouseEnter={onMouseEntert3swwa}
							onTap={onTapnr4g8n}
							ref={refBinding}
							style={{
								backdropFilter: "blur(3px)",
								WebkitBackdropFilter: "blur(3px)",
								...style,
							}}
							{...addPropertyOverrides(
								{
									AcB5hVtra: {
										"data-framer-name": "Mobile",
										onMouseEnter: void 0,
									},
									x20vFQbdH: {
										"data-framer-name": "Hover",
										onMouseLeave: onMouseLeave1crw1un,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-ma81qh"}
								data-framer-name={"Button Body"}
								layoutDependency={layoutDependency}
								layoutId={"qhta0hNEt"}
								style={{
									backgroundColor:
										"var(--token-88fd9b68-42f9-4676-b8dd-60b51ccd638a, rgb(0, 0, 0))",
									borderBottomLeftRadius: 22,
									borderBottomRightRadius: 22,
									borderTopLeftRadius: 22,
									borderTopRightRadius: 22,
								}}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-48vx0z"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"Q8ONU93_R"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-38406790-1041-404b-8965-34452f5c8f25, rgb(53, 228, 228))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={BYNIrUSxY}
									variants={{
										x20vFQbdH: {
											"--extracted-r6o4lv":
												"var(--token-b99cc375-1a62-4d96-9943-2febad019e2a, rgb(230, 238, 246))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											x20vFQbdH: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1tix7ms"}
															data-styles-preset={"PNrJZBqkc"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-b99cc375-1a62-4d96-9943-2febad019e2a, rgb(230, 238, 246)))",
															}}
														>
															{"Button Text"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1tix7ms"}
											data-styles-preset={"PNrJZBqkc"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-38406790-1041-404b-8965-34452f5c8f25, rgb(53, 228, 228)))",
											}}
										>
											{"Button Text"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-N7rNf.framer-14ls221, .framer-N7rNf .framer-14ls221 { display: block; }",
	".framer-N7rNf.framer-bg9hh3 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-N7rNf .framer-ma81qh { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 5px 16px 5px 16px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-N7rNf .framer-48vx0z { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-N7rNf.framer-v-1gkfjr8.framer-bg9hh3, .framer-N7rNf.framer-v-n8hnmg.framer-bg9hh3 { text-decoration: none; }",
	...css3,
];
var FramernE7aLofwL = withCSS(Component, css5, "framer-N7rNf");
var stdin_default = FramernE7aLofwL;
FramernE7aLofwL.displayName = "Primary";
FramernE7aLofwL.defaultProps = {
	height: 28.9,
	width: 102.45,
};
addPropertyControls(FramernE7aLofwL, {
	variant: {
		options: ["IuDNKR63H", "x20vFQbdH", "AcB5hVtra"],
		optionTitles: ["Default", "Hover", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	BYNIrUSxY: {
		defaultValue: "Button Text",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	hYruqSCKG: {
		title: "Link",
		type: ControlType.Link,
	},
	NVEphcQnB: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramernE7aLofwL,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/8oEYLNDigAqCVO5Uobev/eVsDAybFAyVYWRXXYXIO/pz7iat1aX.js
var PrimaryFonts = getFonts(stdin_default);
var MotionDivWithFX = withFX(motion2.div);
var cycleOrder2 = ["kRUZRBaGN", "FnWTGIigj", "SUTgHUvsW"];
var serializationHash2 = "framer-Eh3sZ";
var variantClassNames2 = {
	FnWTGIigj: "framer-v-1tudim3",
	kRUZRBaGN: "framer-v-32yejb",
	SUTgHUvsW: "framer-v-t5lzni",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 25,
};
var transition2 = {
	delay: 0.1,
	duration: 1,
	ease: [0.16, 1, 0.3, 1],
	type: "tween",
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 48,
};
var transition3 = {
	delay: 0.1,
	duration: 1.5,
	ease: [0.31, 1.01, 0.55, 0.97],
	type: "tween",
};
var textEffect = {
	effect: animation1,
	repeat: false,
	startDelay: 0.2,
	threshold: 0,
	tokenization: "line",
	transition: transition3,
	trigger: "onInView",
	type: "appear",
};
var animation2 = {
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 32,
};
var textEffect1 = {
	effect: animation2,
	repeat: false,
	startDelay: 0.2,
	threshold: 0,
	tokenization: "line",
	transition: transition3,
	trigger: "onInView",
	type: "appear",
};
var animation3 = {
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 18,
};
var textEffect2 = {
	effect: animation3,
	repeat: false,
	startDelay: 0.2,
	threshold: 0,
	tokenization: "line",
	transition: transition3,
	trigger: "onInView",
	type: "appear",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	Desktop: "kRUZRBaGN",
	Phone: "SUTgHUvsW",
	Tablet: "FnWTGIigj",
};
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "kRUZRBaGN",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "kRUZRBaGN",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className2, className4, className];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.section
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-32yejb",
							className5,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"kRUZRBaGN"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-b99cc375-1a62-4d96-9943-2febad019e2a, rgb(230, 238, 246))",
							...style,
						}}
						{...addPropertyOverrides2(
							{
								FnWTGIigj: {
									"data-framer-name": "Tablet",
								},
								SUTgHUvsW: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-qv8992"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"qNpchn9EM"}
						>
							<MotionDivWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-1jjsnvy"}
								data-framer-name={"Content Wrap"}
								layoutDependency={layoutDependency}
								layoutId={"mEtrkQ8tZ"}
							>
								<motion2.div
									className={"framer-1n9o46d"}
									data-framer-name={"Wrap"}
									layoutDependency={layoutDependency}
									layoutId={"vLt1rmHM0"}
								>
									<motion2.div
										className={"framer-63a0rq"}
										data-framer-name={"Label"}
										layoutDependency={layoutDependency}
										layoutId={"SOooWFMum"}
										style={{
											backgroundColor:
												"var(--token-43eac8f6-6121-473c-88d1-781f7c603ff3, rgb(185, 255, 255))",
										}}
									>
										<RichText2
											__fromCanvasComponent={true}
											className={"framer-gtfy1d"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"qD514AwyE"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-88fd9b68-42f9-4676-b8dd-60b51ccd638a, rgb(39, 46, 63))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.p
													className={"framer-styles-preset-16bupuy"}
													data-styles-preset={"pJrILY7rY"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-88fd9b68-42f9-4676-b8dd-60b51ccd638a, rgb(39, 46, 63)))",
													}}
												>
													{"Start a project"}
												</motion2.p>
											</React2.Fragment>
										</RichText2>
									</motion2.div>
									<motion2.div
										className={"framer-1cns47i"}
										data-framer-name={"Text Wrap"}
										layoutDependency={layoutDependency}
										layoutId={"woCvWbUvV"}
									>
										<RichText2
											__fromCanvasComponent={true}
											className={"framer-x2ill9"}
											effect={textEffect}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"W6mGYzqhw"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides2(
												{
													FnWTGIigj: {
														children: (
															<React2.Fragment>
																<motion2.p
																	className={"framer-styles-preset-rwcd89"}
																	data-styles-preset={"fVNgQUCuM"}
																	style={{
																		"--framer-text-alignment": "center",
																	}}
																>
																	{
																		"Partner with us to tackle mountain and climate challenges"
																	}
																</motion2.p>
															</React2.Fragment>
														),
														effect: textEffect1,
													},
													SUTgHUvsW: {
														children: (
															<React2.Fragment>
																<motion2.p
																	className={"framer-styles-preset-rwcd89"}
																	data-styles-preset={"fVNgQUCuM"}
																	style={{
																		"--framer-text-alignment": "center",
																	}}
																>
																	{
																		"Partner with us to tackle mountain and climate challenges"
																	}
																</motion2.p>
															</React2.Fragment>
														),
														effect: textEffect2,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React2.Fragment>
												<motion2.h2
													className={"framer-styles-preset-yifk8q"}
													data-styles-preset={"fJd5WHftj"}
													style={{
														"--framer-text-alignment": "center",
													}}
												>
													{
														"Partner with us to tackle mountain and climate challenges"
													}
												</motion2.h2>
											</React2.Fragment>
										</RichText2>
									</motion2.div>
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "ifpwmzD2L",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "ifpwmzD2L",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "ifpwmzD2L",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks) => (
											<ComponentViewportProvider
												height={28}
												y={
													(componentViewport?.y || 0) +
													160 +
													(((componentViewport?.height || 547.9) -
														320 -
														190.2) /
														2 +
														0 +
														0) +
													45 +
													0 +
													0 +
													0 +
													0 +
													117.2
												}
												{...addPropertyOverrides2(
													{
														FnWTGIigj: {
															y:
																(componentViewport?.y || 0) +
																120 +
																(((componentViewport?.height || 429.8) -
																	240 -
																	305.7) /
																	2 +
																	0 +
																	0) +
																45 +
																0 +
																0 +
																0 +
																0 +
																232.7,
														},
														SUTgHUvsW: {
															y:
																(componentViewport?.y || 0) +
																72 +
																(((componentViewport?.height || 200) -
																	144 -
																	321.7) /
																	2 +
																	0 +
																	0) +
																45 +
																0 +
																0 +
																0 +
																0 +
																248.7,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-19bdko7-container"}
													layoutDependency={layoutDependency}
													layoutId={"hfPtPjtb3-container"}
													nodeId={"hfPtPjtb3"}
													rendersWithMotion={true}
													scopeId={"pz7iat1aX"}
												>
													{_jsx2(stdin_default, {
														BYNIrUSxY: "Get In Touch",
														height: "100%",
														hYruqSCKG: resolvedLinks[0],
														id: "hfPtPjtb3",
														layoutId: "hfPtPjtb3",
														variant: "IuDNKR63H",
														width: "100%",
														...addPropertyOverrides2(
															{
																FnWTGIigj: {
																	hYruqSCKG: resolvedLinks[1],
																},
																SUTgHUvsW: {
																	hYruqSCKG: resolvedLinks[2],
																	variant: "AcB5hVtra",
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
								</motion2.div>
							</MotionDivWithFX>
						</motion2.div>
						<motion2.div
							className={"framer-x7g5p4"}
							data-framer-name={"Image Wrapper"}
							layoutDependency={layoutDependency}
							layoutId={"WiF8IEOgB"}
						/>
					</motion2.section>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Eh3sZ.framer-1a2dfz7, .framer-Eh3sZ .framer-1a2dfz7 { display: block; }",
	".framer-Eh3sZ.framer-32yejb { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 160px 16px 160px 16px; position: relative; width: 1200px; }",
	".framer-Eh3sZ .framer-qv8992 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; max-width: 1800px; overflow: hidden; padding: 45px 0px 0px 0px; position: relative; width: 100%; z-index: 1; }",
	".framer-Eh3sZ .framer-1jjsnvy { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-Eh3sZ .framer-1n9o46d { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-Eh3sZ .framer-63a0rq { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 8px; position: relative; width: min-content; }",
	".framer-Eh3sZ .framer-gtfy1d { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-Eh3sZ .framer-1cns47i { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: flex-start; max-width: 600px; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-Eh3sZ .framer-x2ill9 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-Eh3sZ .framer-19bdko7-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-Eh3sZ .framer-x7g5p4 { bottom: -99px; flex: none; height: 118%; left: 0px; overflow: hidden; position: absolute; width: 100%; z-index: 0; }",
	".framer-Eh3sZ.framer-v-1tudim3.framer-32yejb { padding: 120px 24px 120px 24px; width: 810px; }",
	".framer-Eh3sZ.framer-v-1tudim3 .framer-1cns47i { gap: 64px; width: 80%; }",
	".framer-Eh3sZ.framer-v-t5lzni.framer-32yejb { padding: 72px 16px 72px 16px; width: 390px; }",
	".framer-Eh3sZ.framer-v-t5lzni .framer-1n9o46d { gap: 32px; }",
	".framer-Eh3sZ.framer-v-t5lzni .framer-1cns47i { gap: 48px; width: 90%; }",
	...css2,
	...css4,
	...css,
];
var Framerpz7iat1aX = withCSS2(Component2, css6, "framer-Eh3sZ");
var stdin_default2 = Framerpz7iat1aX;
Framerpz7iat1aX.displayName = "Section Contact";
Framerpz7iat1aX.defaultProps = {
	height: 547.9,
	width: 1200,
};
addPropertyControls2(Framerpz7iat1aX, {
	variant: {
		options: ["kRUZRBaGN", "FnWTGIigj", "SUTgHUvsW"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(
	Framerpz7iat1aX,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PrimaryFonts,
		...getFontsFromSharedStyle2(fonts2),
		...getFontsFromSharedStyle2(fonts4),
		...getFontsFromSharedStyle2(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:section-contact
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "SUTgHUvsW",
	md: "FnWTGIigj",
	xl: "kRUZRBaGN",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SectionContactFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var section_contact_default = ComponentWithRoot;
export { section_contact_default as default };
