// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c005e0105870bbbc "Mountain Futures (copy) (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * name?: string // Name
 * position?: string // Position
 * scrollSection?: undefined // Scroll Section
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-E2DSRDMQ.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-YULNS5JV.js";
import { routes } from "./chunks/chunk-MCZURAGM.js";

// virtual:team-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/5rx5ah8tiCb9kjz647eN/FPOrVRkUJX9z9GaaGfIj/o2XO9xn3h.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ImageWithFX = withFX(Image);
var serializationHash = "framer-l4f68";
var variantClassNames = {
	q7ozLp0sb: "framer-v-6oqtrd",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	height,
	id,
	image,
	name1,
	position,
	scrollSection,
	width,
	...props
}) => {
	return {
		...props,
		dLOk7P2wW: image ??
			props.dLOk7P2wW ?? {
				pixelHeight: 2400,
				pixelWidth: 2400,
				src: "https://framerusercontent.com/images/DzMKzaduanmRuAjGVAN9JmqDHgM.webp?scale-down-to=512&width=2400&height=2400",
				srcSet:
					"https://framerusercontent.com/images/DzMKzaduanmRuAjGVAN9JmqDHgM.webp?scale-down-to=512&width=2400&height=2400 512w,https://framerusercontent.com/images/DzMKzaduanmRuAjGVAN9JmqDHgM.webp?scale-down-to=1024&width=2400&height=2400 1024w,https://framerusercontent.com/images/DzMKzaduanmRuAjGVAN9JmqDHgM.webp?scale-down-to=2048&width=2400&height=2400 2048w,https://framerusercontent.com/images/DzMKzaduanmRuAjGVAN9JmqDHgM.webp?width=2400&height=2400 2400w",
			},
		kwzE9eKDb: position ?? props.kwzE9eKDb ?? "Position Title",
		S8l7lc0hk: scrollSection ?? props.S8l7lc0hk,
		v5eBJ_l8J: name1 ?? props.v5eBJ_l8J ?? "First Last",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		dLOk7P2wW,
		v5eBJ_l8J,
		kwzE9eKDb,
		S8l7lc0hk,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "q7ozLp0sb",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-6oqtrd",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"q7ozLp0sb"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<motion.div
							className={"framer-1oaube"}
							data-framer-name={"Wrap"}
							layoutDependency={layoutDependency}
							layoutId={"KMJLLSQ0B"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-avsfok"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"xM577V7e7"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={v5eBJ_l8J}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h4
										className={"framer-styles-preset-1nyw0o7"}
										data-styles-preset={"tUGyknt9Z"}
									>
										{"First Last"}
									</motion.h4>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1plvae7"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Wjf2DnfT0"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={kwzE9eKDb}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-16bupuy"}
										data-styles-preset={"pJrILY7rY"}
									>
										{"Position Title"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<motion.div
							className={"framer-1262kda"}
							data-framer-name={"Image Wrap"}
							layoutDependency={layoutDependency}
							layoutId={"ap7_wBImW"}
						>
							<ImageWithFX
								__framer__styleTransformEffectEnabled={true}
								__framer__transformTargets={[
									{
										target: {
											opacity: 1,
											rotate: 0,
											rotateX: 0,
											rotateY: 0,
											scale: 1.1,
											skewX: 0,
											skewY: 0,
											x: 0,
											y: -15,
										},
									},
									{
										ref: S8l7lc0hk,
										target: {
											opacity: 1,
											rotate: 0,
											rotateX: 0,
											rotateY: 0,
											scale: 1.1,
											skewX: 0,
											skewY: 0,
											x: 0,
											y: 15,
										},
									},
								]}
								__framer__transformTrigger={"onScrollTarget"}
								__framer__transformViewportThreshold={0}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								background={{
									alt: "",
									fit: "fill",
									intrinsicHeight: 2400,
									intrinsicWidth: 2400,
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 390.2) - 0 - 390.2) / 2 +
												53.2 +
												24) +
											0,
									),
									pixelHeight: 2400,
									pixelWidth: 2400,
									sizes: componentViewport?.width || "100vw",
									...toResponsiveImage(dLOk7P2wW),
								}}
								className={"framer-3vg0xs"}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"ClBkYfSA6"}
							/>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-l4f68.framer-1ehjxk2, .framer-l4f68 .framer-1ehjxk2 { display: block; }",
	".framer-l4f68.framer-6oqtrd { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 235px; }",
	".framer-l4f68 .framer-1oaube { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-l4f68 .framer-avsfok, .framer-l4f68 .framer-1plvae7 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-l4f68 .framer-1262kda { aspect-ratio: 0.7507987220447284 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 313px); overflow: hidden; position: relative; width: 100%; }",
	".framer-l4f68 .framer-3vg0xs { aspect-ratio: 0.75 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 313px); left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
	...css2,
	...css,
];
var Framero2XO9xn3h = withCSS(Component, css3, "framer-l4f68");
var stdin_default = Framero2XO9xn3h;
Framero2XO9xn3h.displayName = "Team Card";
Framero2XO9xn3h.defaultProps = {
	height: 390.2,
	width: 235,
};
addPropertyControls(Framero2XO9xn3h, {
	dLOk7P2wW: {
		__defaultAssetReference:
			"data:framer/asset-reference,DzMKzaduanmRuAjGVAN9JmqDHgM.webp?originalFilename=FLORA-Attractive+Man+Shot-920de630.webp&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	v5eBJ_l8J: {
		defaultValue: "First Last",
		displayTextArea: false,
		title: "Name",
		type: ControlType.String,
	},
	kwzE9eKDb: {
		defaultValue: "Position Title",
		displayTextArea: false,
		title: "Position",
		type: ControlType.String,
	},
	S8l7lc0hk: {
		title: "Scroll Section",
		type: ControlType.ScrollSectionRef,
	},
});
addFonts(
	Framero2XO9xn3h,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:team-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TeamCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var team_card_default = ComponentWithRoot;
export { team_card_default as default };
