// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project c005e0105870bbbc "Mountain Futures (copy) (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * testimonialQuote?: string // Testimonial Quote
 * name?: string // Name
 * position?: string // Position
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-ZVSW4UDK.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-E2DSRDMQ.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-XOYYYZYZ.js";
import { routes } from "./chunks/chunk-MCZURAGM.js";

// virtual:testimonial-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/wOfKtxiaQK4AFbHZ8WIF/GKmzguXb4qo4VGecrVF0/lgK86ckMC.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-EgcpM";
var variantClassNames = {
	E_b6jlHpi: "framer-v-1tlyyem",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	height,
	id,
	name1,
	position,
	testimonialQuote,
	width,
	...props
}) => {
	return {
		...props,
		CglgnMs41:
			testimonialQuote ??
			props.CglgnMs41 ??
			"\u201CSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa\u201D",
		sHJs4eber: name1 ?? props.sHJs4eber ?? "First Last",
		xjykwySRW: position ?? props.xjykwySRW ?? "Position Title",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		CglgnMs41,
		sHJs4eber,
		xjykwySRW,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "E_b6jlHpi",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className3, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1tlyyem",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"E_b6jlHpi"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-a7c87a03-e4bc-4fee-bd27-763511435b35, rgb(18, 32, 35))",
							...style,
						}}
					>
						<motion.div
							className={"framer-1lfjdi2"}
							data-framer-name={"Top"}
							layoutDependency={layoutDependency}
							layoutId={"lUy2Lx8R0"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1dlcm3c"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"I1lDDXICZ"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-a5f2dea9-e675-4451-817f-b93e011b3b4d, rgb(225, 252, 173))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={CglgnMs41}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-rwcd89"}
										data-styles-preset={"fVNgQUCuM"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-a5f2dea9-e675-4451-817f-b93e011b3b4d, rgb(225, 252, 173)))",
										}}
									>
										{
											"\u201CSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa\u201D"
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<motion.div
							className={"framer-mqh2jo"}
							data-framer-name={"Bottom"}
							layoutDependency={layoutDependency}
							layoutId={"gB1aDGVmZ"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-459tx8"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"swXmaHT5D"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-a5f2dea9-e675-4451-817f-b93e011b3b4d, rgb(225, 252, 173))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={sHJs4eber}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1tix7ms"}
										data-styles-preset={"PNrJZBqkc"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-a5f2dea9-e675-4451-817f-b93e011b3b4d, rgb(225, 252, 173)))",
										}}
									>
										{"First Last"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-kokbm2"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"XZHDHoHYZ"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-a5f2dea9-e675-4451-817f-b93e011b3b4d, rgb(225, 252, 173))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={xjykwySRW}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-16bupuy"}
										data-styles-preset={"pJrILY7rY"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-a5f2dea9-e675-4451-817f-b93e011b3b4d, rgb(225, 252, 173)))",
										}}
									>
										{"Position Title"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-EgcpM.framer-1o4pjds, .framer-EgcpM .framer-1o4pjds { display: block; }",
	".framer-EgcpM.framer-1tlyyem { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; height: 350px; justify-content: space-between; min-height: 350px; overflow: hidden; padding: 24px; position: relative; width: 349px; }",
	".framer-EgcpM .framer-1lfjdi2 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-EgcpM .framer-1dlcm3c { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-EgcpM .framer-mqh2jo { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-EgcpM .framer-459tx8, .framer-EgcpM .framer-kokbm2 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	...css,
	...css3,
	...css2,
];
var FramerlgK86ckMC = withCSS(Component, css4, "framer-EgcpM");
var stdin_default = FramerlgK86ckMC;
FramerlgK86ckMC.displayName = "Testimonial Card";
FramerlgK86ckMC.defaultProps = {
	height: 350,
	width: 349,
};
addPropertyControls(FramerlgK86ckMC, {
	CglgnMs41: {
		defaultValue:
			"\u201CSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa\u201D",
		displayTextArea: true,
		title: "Testimonial Quote",
		type: ControlType.String,
	},
	sHJs4eber: {
		defaultValue: "First Last",
		displayTextArea: false,
		title: "Name",
		type: ControlType.String,
	},
	xjykwySRW: {
		defaultValue: "Position Title",
		displayTextArea: false,
		title: "Position",
		type: ControlType.String,
	},
});
addFonts(
	FramerlgK86ckMC,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:testimonial-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TestimonialCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"c005e0105870bbbc8e5c294b49f1f8c67a5366d412008cb51faf83259861a0f1"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var testimonial_card_default = ComponentWithRoot;
export { testimonial_card_default as default };
